hedyorg/hedy

static/levels.json
["color is ask" is correct grammar, not "ask color is"]
=> Correct grammar in demo code for Level 2 Ask, en/es 

app.py, static/texts.json, templates/layout.html
=> Word "Level" can now be translated into other languages.

docs/es-level2.md
The game "Earthworms" doesn't seem to exist in Spanish. So @rickbeerendonk and I have slightly changed the text of the exercise instead of doing a pure (language) translation.
=> Added Spanish explanation for Level 2.

CONTRIBUTING.md, StatusOfThings.md
Where are we with translations of all the several things? This page tells you!
=> Project overview file

app.py, coursedata/course/hedy/docs-fr/01-docs.md, coursedata/course/hedy/fr.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/fr.yaml, coursedata/texts.yaml, main/contact-fr.md, main/press-fr.md, main/start-en.md, main/start-fr.md
Hello
After discovering the Hedy introduction yesterday, I found the approach so nice for children that I wanted to make it available for children around here too. 
This PR adds French translations (the Hedy grammar is still in English though, like it is for other languages too)
A second commit also fixes a few typos I spot in the English texts.
Hope this helps, thank you for building this 🙏
=> Add French translations

README.md
Added ' : ' as visual delimeter between design goals and explanations, also moved explanations to new lines to improve readability.
Fixed level 3 heading formating.
Made note italic and separate from actual explanation for level 6.
=> Formating corrections to README

coursedata/level-defaults/pt_br.yaml
Beginning of translations in Brazilian Portuguese
=> Add course levels in Brazilian Portuguese

grammars/level10.txt, grammars/level11.txt, grammars/level12.txt, grammars/level13.txt, grammars/level8.txt, grammars/level9.txt, hedy.py, tests.py
updated backend code for level 8 tm 13. Does also include tests.
=> updated backend code for level 8 tm 13

static/js/app.js, templates/code-page.html
- Closes #96 using Alt+Enter to run the code and shift the focus.
- Passes lang & level as global variables to js.
=> Accessibility

static/js/app.js
=> Fix dangling prompt.

templates/code-page.html, templates/incl-menubar.html, templates/layout.html, templates/level-page.html, templates/main-page.html
- Fixes #8 
- Uses jinja `indent` filter: https://jinja.palletsprojects.com/en/master/templates/?highlight=indent#indent
=> Fix indentations in templates using jinja indent filter

coursedata/level-defaults/en.yaml, coursedata/level-defaults/es.yaml, coursedata/level-defaults/fr.yaml, coursedata/level-defaults/nl.yaml, coursedata/level-defaults/pt_br.yaml
This pull request fixes #114
The demo code for level 7 is incorrectly indented. This pull request remedies that problem in all languages currently available.
=> fix indentation of demo code for level 7

CONTRIBUTING.md
This pull-request is a small improvement to the `CONTRIBUTING.md` text.
Part of a sentence was repeated. Once as normal text and once as a link text. This pull-request removes the normal text.
=> remove repeated text for the texts link

main/menu.json, main/press-en.md, main/press-es.md, main/press-nl.md, main/start-es.md, main/start-fr.md, main/start-nl.md, main/start-pt_br.md
- Adds missing translations for navigation bar.
- Link to try Hedy on the right language.
- Missing press releases in other languages.
=> Add some missing translations

app.py, auth.py, doc/backend.md, templates/admin.html, utils.py
- Use /admin instead of /users
- Proper indexing of user entries.
- Show total programs & users.
=> Admin improvements

coursedata/level-defaults/en.yaml, coursedata/level-defaults/es.yaml, coursedata/level-defaults/fr.yaml, coursedata/level-defaults/nl.yaml, coursedata/level-defaults/pt_br.yaml, main/contact-en.md, main/contact-es.md, main/contact-fr.md, main/contact-nl.md, main/contact-pt_br.md
Closes #130. Also: updates all langs to use new Hedy email address and adds link to Github issues
=> fixes demo code level 7

templates/signup.html
* Birth Year as integer (+placeholder) (Out of habit I gave it a date (did not work) and then an ISO-8601 (which worked)) 
* Mail as appropriate type to call up correct soft keyboard on phones.
=> signup.html: Minor Usability improvements

app.py
=> Allow admin to see all programs

app.py, auth.py, templates/admin.html, templates/programs.html
- Fix bug that didn't allow admin user to see others' programs.
- Add functionality to see list of programs from a user through a link in the admin
- Create `is_admin` helper method to clean up code.
Deployed in alpha already and it seems to work :).
=> Allow admin to easily see others' programs

coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/nl.yaml, coursedata/texts/pt_br.yaml, hedyweb.py, templates/code-page.html
=> Include button to go back to previous level

coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/nl.yaml, coursedata/texts/pt_br.yaml, templates/signup.html
=> Explain why people should create an account

auth.py, doc/backend.md, static/js/app.js, tests_e2e.py
- Closes #129.
- Server now returns the expiry of the session, together with the profile info.
- If the user is logged in and the session is expired, the page is refreshed on the two interactions that can be done without a page refresh: 1) running code; 2) saving code.
- I decided against having a `setInterval` that runs regularly because I feel it is overkill and could create other problems down the road.
- Perhaps it'd be also be a good idea to execute this function when the uses focuses the browser tab back after a while, but am not sure if it's really necessary.
=> When running code or attempting to save, if the session expires, refresh the page.

templates/layout.html
=> Adds "fork me on Github" ribbon

coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/nl.yaml, coursedata/texts/pt_br.yaml, static/js/app.js
- Improves on the solution given to https://github.com/Felienne/hedy/issues/147
=> Show a useful prompt if the user tries to run code while Hedy waits for an answer

app.py, auth.py, doc/backend.md, static/js/auth.js, templates/admin.html, utils.py
- Mark users as teachers in the admin.
- Allow teachers to access programs from other users by link.
=> Teacher users

coursedata/level-defaults/fr.yaml
Reverts Felienne/hedy#231
Seems to be an error in this yaml, need to be checked
=> Revert "Update fr.yaml"

app.py, auth.py, templates/admin.html
- Count programs per user.
- Contains script to add current count to all existing users. The script is idempotent although we should remove it soon to avoid doing a lot of calls to DynamoDB.
- Closes #216
=> Count programs per user

app.py, auth.py, templates/admin.html
Reverts Felienne/hedy#229
This is too expensive to run on Heroku, must be ran locally first!
=> Revert "Count programs per user"

coursedata/course/hedy/fr.yaml, coursedata/level-defaults/fr.yaml
- Fixes the indentation of https://github.com/Felienne/hedy/pull/231
- Closes https://github.com/Felienne/hedy/issues/233
=> Fixes fr.yaml for level 8

coursedata/level-defaults/de.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/es.yaml, coursedata/level-defaults/fr.yaml, coursedata/level-defaults/it.yaml, coursedata/level-defaults/nl.yaml, coursedata/level-defaults/pt_br.yaml, templates/code-page.html
- Use markdown in the intro text to levels.
- Use backticks to show commands in monospace font in explanations.
- Update translations to match the changes done to the Dutch translation.
- Closes #225.
=> Code printing

static/js/app.js
=> If prompt modal is hidden by adding new input to the editor, allow again to run code

app.py, hedy.py, tests/tests_level_01.py, tests/tests_level_02.py, tests/tests_level_03.py, tests/tests_level_04.py, tests/tests_level_05.py, tests/tests_level_06.py, tests/tests_level_07.py, tests/tests_multiple_levels.py
Improves layout of tests for better readability.
=> Refactors tests using textwrap and proper order of arguments in assertEqual

coursedata/course/hedy/docs-en/02-docs.md, coursedata/course/hedy/docs-en/03-docs.md, coursedata/course/hedy/docs-es/02-docs.md, coursedata/course/hedy/docs-es/03-docs.md, coursedata/course/hedy/docs-es/04-docs.md, coursedata/course/hedy/docs-es/05-docs.md, coursedata/course/hedy/docs-es/06-docs.md, coursedata/course/hedy/docs-fr/01-docs.md, coursedata/course/hedy/docs-nl/04-docs.md, coursedata/course/hedy/docs-nl/05-docs.md, coursedata/course/hedy/docs-nl/06-docs.md
- English versions for docs, levels 2 & 3, translated by Marleen Gilsing.
- Spanish versions for docs, levels 3 to 6.
- Small fixes to Dutch and French docs.
- Closes #212 (remaining English translations will be done by Marleen).
=> Translations for docs

app.py, coursedata/texts/de.yaml, coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/it.yaml, coursedata/texts/nl.yaml, coursedata/texts/pt_br.yaml, grammars/level3.lark, grammars/level4.lark, grammars/level5.lark, hedy.py, tests/tests_distance_algo.py, tests/tests_level_03.py
In levels 1 upto 5. I saw in the collected data that after level 4 the error is not common anymore, so I did not allow it in higher levels.
Also refactors the tests a bit for the distance algo
=> fixes #185 by allowing unquoted strings in the grammar for print

app.py
I think the code still works well but it's wrong to have these function names repeated. All functions with repeated names are of my authorship :+1:
=> Fix repeated function names

main/press-en.md, main/press-es.md, main/press-fr.md, main/press-nl.md
Adds a link to a recently published Opensource.com article to the English, Dutch, French, and Spanish press pages.
=> Add Opensource.com article

coursedata/course/hedy/docs-en/02-docs.md, coursedata/course/hedy/docs-en/03-docs.md
- fix a broken image link and its alt. text in level 2
- fix a code line missing a closing back-tick in level 3
- a few other minor grammar fixes
=> minor grammar & markdown fixes in docs-en

coursedata/course/hedy/docs-en/04-docs.md, coursedata/course/hedy/docs-en/05-docs.md, coursedata/course/hedy/docs-en/06-docs.md
Translations done by Marleen Gilsing (thanks Marleen!)
Closes #263
=> Add English docs for levels 4-6

coursedata/level-defaults/en.yaml
=> Update third example to be consistent with others

coursedata/level-defaults/de.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/es.yaml, coursedata/level-defaults/fr.yaml, coursedata/level-defaults/it.yaml, coursedata/level-defaults/nl.yaml, coursedata/level-defaults/pt_br.yaml
@Felienne in this branch you can add the changes to the third example of level 6 in nl and de; I still need to add the changes to it, pt_br and fr.
=> Update example level 6; closes #157.

static/js/app.js
at default initialized at 0 (off)
=> variable to turn on/off highlighter

coursedata/level-defaults/zh.yaml
I translated this material into Chinese again。 
I have one question on line 217, demo_code: "if 5+3 == 8:\n    print('5+3 is indeed 8')\nelse:\n  print('This will not be printed because 5+3 is 8!')", I think a NOT missing in this sentence, it should be print('This will not be printed because 5+3 is NOT 8!')
=> update course data-level defaults-zh

hedy.py, tests/tests_level_07.py
Finally found the issue and now I will go hide in a corner for making dumb mistakes and misunderstanding my own code :D
=> Fixes #297

auth.py, e2e_tests.py
- Adds additional security headers to auth cookies
- Updates/fixes first test of the E2E suite.
@lpmi-13 it seems that the change from the PR only affects session cookies, not the auth cookies. I added the cookie properties manually here.
=> Adds additional security headers to auth cookies

Procfile
Supposedly helps with memory usage
=> Enable gunicorn preloading

.dockerignore, CONTRIBUTING.md, Dockerfile, app.py
- Add a Dockerfile to run the application without needing to install any python dependencies (or even python itself!)
- Update app.py to bind to 0.0.0.0 in DEV mode so it can respond inside a container
- Update Contributing.md with instructions for building and running a containerized version of the webapp
=> add Dockerfile for local development without python

app.py, hedy.py, hedyweb.py, utils.py
=> Revert "refactor: cache Lark parsers"

jsonbin.py
JSONBin is deprecating their v2 API shortly.
Upgrade to the v3 API.
=> fix: upgrade to JSONBin API v3

auth.py, config.py, tests/test_utils.py, utils.py
=> Adjust bcrypt rounds of hashed password on login.

templates/code-page.html
=> Resize editor after closing error or warning box.

main/contact-de.md, main/for-teachers-de.md, main/learn-more-de.md, main/press-de.md, main/start-de.md
This translates texts in the https://github.com/Felienne/hedy/tree/master/main folder to German. 
I couldn't find instructions for the [haunted house assignment](https://github.com/Felienne/hedy/blob/65994e714a9490d95c8a1df841adcd29868c3b69/main/for-teachers-en.md#L241) on the teachers page. Is that correct?
Ref #205
=> translate texts in ./main to German

coursedata/course/hedy/de.yaml, coursedata/level-defaults/de.yaml
This adds the German translations of levels 8-17 to ./coursedata/level-defaults/de.yaml.
=> add levels 8-17 to ./coursedata/level-defaults/de.yaml

coursedata/adventures/en.yaml
I added level 3, 4 and 6 of the restaurant adventure. (I still have to think of level 5) 
I also corrected some misstakes I made in the example codes in level 2.
=> Restaurant lv. 3, 4, 6  + corrected lv 2.

coursedata/level-defaults/zh.yaml
I found a lot of problems on the Hedy website (Chinese version), so I has translated most parts of the document again. I can not find the branch of Chinese translations so I pull the request here now.
=> translated again  zh.yaml

coursedata/course/hedy/en.yaml, coursedata/course/hedy/nl.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml, grammars/level18.lark, grammars/level19.lark, hedy.py, tests/tests_level_18.py, tests/tests_level_19.py, tests/tests_multiple_levels.py
Level 18 and 19 are done. 18 doesn't change a lot but explains how to get a value from a list. Level 19 learns len() (length()) and how to use the for loop to loop through a list.
=> Level 18 19

grammars/level10.lark, grammars/level11.lark, grammars/level12.lark, grammars/level13.lark, grammars/level14.lark, grammars/level15.lark, grammars/level16.lark, grammars/level17.lark, grammars/level9.lark, tests/tests_level_09.py
Fix for Issue: Can only use one elif https://github.com/Felienne/hedy/issues/431
Fixed it by changing the elif? in the lark to (elif)*
=> Fix for the elifs

coursedata/course/hedy/en.yaml, coursedata/course/hedy/nl.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml, grammars/level18.lark, grammars/level20.lark, grammars/level21.lark, grammars/level22.lark, hedy.py, tests/tests_level_20.py, tests/tests_level_21.py, tests/tests_level_22.py, tests/tests_multiple_levels.py
Levels were the same as before but at a different position now. Implements = and ==, != and <= and >=.
=> Level 20, 21 and 22 implemented

app.py, utils.py
- Do not allow starting a non-dev environment without a SECRET_KEY
- Always change to the root Hedy folder when running the code
- Simplify logic for launching the app.
=> Small organizational improvements to `app.py`

coursedata/adventures/nl.yaml
Added level 1-6 for the fortune teller adventure in Dutch
=> added fortune teller 1-6 NL

static/js/auth.js, utils.py
This is a valid and commonly used character in email addresses.
=> chore: support '+' in email addresses

app.py
I don't understand how #375 can happen so now when there is an exception in processing parse we log so we can see what goes on.
=> adding code to log in case parse fails unexpectedly

coursedata/level-defaults/en.yaml
The error was in the start code which resulted in a lot of errors in user programs.
=> Fixed the error where an automatic error was given in level 10 with indents

app.py
@tibiba This might be able to solve our latest issue with GFI
=> Initialize session variables for gfi on POST /parse if not present.

static/js/app.js, static/js/syntaxModesRules.js
lvl 8/9 fixes
en een fix voor lvl 10
=> Fixes until lvl10 syntax highlighter

app.py, e2e_tests.py
If user is not logged in when requesting programs page, redirect them to login.
=> Redirect logged out user from /programs to /login

coursedata/texts/de.yaml, coursedata/texts/el.yaml, coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/hu.yaml, coursedata/texts/it.yaml, coursedata/texts/nl.yaml, coursedata/texts/pt_br.yaml, coursedata/texts/sw.yaml, coursedata/texts/zh.yaml, static/js/app.js, templates/incl-editor-and-output.html
Based on user studies, this is a feature that kids love!
It is probably good if one of the web experts checks this cause I do not know what I am doing :D I am also not sure the tick mark is pretty enough, a bit of CSS might be good there but that is surely out of my reach!
=> feat: Adds the option to read the output aloud in all supported languages

static/js/app.js, static/js/tabs.js, templates/incl-editor-and-output.html
Avoids having to map from a language to a country code,
and gives the kids choice.
=> feat: show a language dropdown with all available voices

static/js/app.js, templates/incl-adventure-tabs.html, templates/incl-editor-and-output.html
Enable syntax highlighting for the editor, and syntax highlight
example code as well (by turning each of them into read-only
Ace editors).
=> feat: enable syntax highlighting

static/js/syntaxModesRules.js
fix voor de issue vanaf lvl 3 die aangekaart was.
=> fix for printing at random

hedy.py
=> loop var should be added to list of vars for proper escaping

hedy.py
seem to get \r\n and that breaks
=> loaded programs on Windows

grammars-Total/level10-Total.lark, grammars-Total/level11-Total.lark, grammars-Total/level12-Total.lark, grammars-Total/level13-Total.lark, grammars-Total/level14-Total.lark, grammars-Total/level15-Total.lark, grammars-Total/level16-Total.lark, grammars-Total/level17-Total.lark, grammars-Total/level18-Total.lark, grammars-Total/level19-Total.lark, grammars-Total/level20-Total.lark, grammars-Total/level21-Total.lark, grammars-Total/level22-Total.lark, grammars-Total/level7-Total.lark, grammars-Total/level8-Total.lark, grammars-Total/level9-Total.lark, grammars/level7-Additions.lark, hedy.py, tests/tests_level_07.py
=> adds end-blocks to level 7

coursedata/level-defaults/es.yaml
=> Fixed a couple of Spanish typos

static/js/syntaxModesRules.js
=> fixes highlighting of print in lvl 3

CITATION.cff
=> Added cff file

coursedata/adventures/en.yaml, coursedata/adventures/nl.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml, grammars-Total/level10-Total.lark, grammars-Total/level11-Total.lark, grammars-Total/level12-Total.lark, grammars-Total/level13-Total.lark, grammars-Total/level14-Total.lark, grammars-Total/level15-Total.lark, grammars-Total/level16-Total.lark, grammars-Total/level17-Total.lark, grammars-Total/level18-Total.lark, grammars-Total/level19-Total.lark, grammars-Total/level20-Total.lark, grammars-Total/level21-Total.lark, grammars-Total/level22-Total.lark, grammars-Total/level4-Total.lark, grammars-Total/level5-Total.lark, grammars-Total/level6-Total.lark, grammars-Total/level7-Total.lark, grammars-Total/level8-1-Total.lark, grammars-Total/level8-Total.lark, grammars-Total/level9-Total.lark, grammars/level4-Additions.lark, tests/tests_level_04.py
This fix addresses #182 
This fix mandates the translations required in #645
=> feat: allows newline in if statement for levels 4 to 6

coursedata/adventures/el.yaml, coursedata/adventures/en.yaml, coursedata/adventures/es.yaml, coursedata/adventures/hu.yaml, coursedata/adventures/nl.yaml, coursedata/adventures/pt_pt.yaml
Because `ask` now can handle variables and `if` can handle newlines, the example code of the calculator could be simplified.
Also fixes some quotes for `ask` that we missed in the adventures.
Should only be merged after #646!!
=> Simplify calculator 

coursedata/level-defaults/en.yaml
=> Fixed 'Level 2: coding example not properly closed'

grammars/level4-Additions.lark, tests/tests_level_04.py, tests/tests_level_06.py
=> Update grammar level 4 

hedy.py, tests/tests_level_01.py
=> Correctly prints incomplete command

website/teacher.py
The link to the saved programs did not work. I think adding the `/` will solve this
=> fix link to latest_shared

coursedata/course/hedy/pt_br.yaml, coursedata/level-defaults/pt_br.yaml
This PR adds the brazilian portuguese (pt-br) translation for the default course of level 8. I've also fixed some linebreak issues with level 7 that prevented it to be correctly rendered.
I intend to slowly translate the remaining levels (maybe two or three per week). Please let me know how do you prefer to receive those: appended to this PR or in separate PRs.
=> Adds brazilian portuguese translation for level 8

coursedata/adventures/nl.yaml
Fixed these mistakes:
Haunted house level 7 and 8 example codes had indentation mistakes
Haunted house level 3 had an English title
Haunted house level 2 had a ! in the example code
Restaurant level 8 typo in Uitdaging
Added Restaurant level 1, 2, 3, 4, 5
=> Added level 1-5 restaurant and typo fixes

coursedata/adventures/en.yaml
Added new levels to the adventures
=> Added restaurant lvl 8 and haunted house lvl 7 8

coursedata/course/hedy/pt_br.yaml, coursedata/level-defaults/pt_br.yaml, coursedata/level-defaults/pt_pt.yaml
This PR adds Brazilian Portuguese translations for level 9, 10 and 11. Thanks @citharoedus for the European Portuguese translation that served as basis for mine!
This also fixes a small translation leftover on the pt-pt code for level 11.
=> Brazilian Portuguese translation for levels 9-11

app.py, coursedata/level-defaults/bn.yaml, coursedata/level-defaults/hi.yaml, grammars/level1.lark
=> Adds Hindi levels 1 to 7

coursedata/course/hedy/pt_br.yaml, coursedata/level-defaults/pt_br.yaml, coursedata/level-defaults/pt_pt.yaml
This PR includes the translation for pt-br for levels 12-16. It also fixes some minor issues on the European Portuguese translation.
=> Adds Brazilian Portuguese translation for levels 12-16

app.py
Accidentally overwrote the code field causing logging of transpiled programs.
=> fix logging (oops)

coursedata/level-defaults/en.yaml, coursedata/level-defaults/pt_pt.yaml
This PR fixes a variable reference in the start code for level 21 in the en and pt-pt translations. I've also checked the other translations and confirmed that this problem only happens with these two instances.
=> Fix reference to undefined variable

website/emails.yaml
Made a small fix, the rest is perfect like this!
=> Change [link] into <a>

app.py, coursedata/texts/en.yaml, coursedata/texts/nl.yaml, hedy.py
Caps lines at 100 in the parser. We could make this progressive later on where we allow more and more lines in later levels, but this should help against server overloads.
=> Cap lines at 100

app.py, hedy.py, tests/tests_level_01.py, tests/tests_level_02.py, tests/tests_level_03.py, tests/tests_level_04.py, tests/tests_level_05.py, tests/tests_level_06.py, tests/tests_level_07.py
Fixes #765
I _think_ this is my first Python contribution ever (if not, the first one was so long ago as to be obviated from my memory). So please do not refrain to let me know where the code can be made more idiomatic.
I've tried to isolate the code that adds the sleep. I've included the commit here for appreciation, but I'm not sure this really helps with maintainability. We can always revert the commit if we want to.
=> Adds slight pause after turtle forward

website/querylog.py
`sys.getloadavg()` doesn't exist on Windows.
=> Fix running on Windows

hedy.py
Fixes the issue found at https://github.com/Felienne/hedy/pull/834#issuecomment-932143066
=> Fix runhedy.py

hedy.py
This allow the removal of a hack to show a nice error message in case of undefined variables.
=> Unwrap VisitError to allow regular exception raising inside transformers

hedy.py
Now using a lookup so we have less ugly duplication at the call site, addresses #860
=> Refactor convert_to_python

coursedata/quiz/quiz_questions_lvl5.yaml, coursedata/quiz/quiz_questions_lvl6.yaml, coursedata/quiz/quiz_questions_lvl7.yaml
I think the '/n' were supposed to be enters so I replaced them with '\n'
=> replace /n with \n in quiz level 7

hedy.py, tests/tests_level_06.py
=> Add var collision prevention

.gitignore, coursedata/yaml_transformer.py, utils.py
Making changes to level content can be tricky, this simple migrater can help
=> Adds transformer for level migration

hedy.py, tests/Tester.py, tests/tests_level_02.py, tests/tests_level_10.py
Turns out we did not catch `\n` properly.
=> Partial fix for #1208

hedy.py
Fixes #1223 (was easier than I thought!)
=> uses ast in further processing

coursedata/adventures/en.yaml, coursedata/adventures/nl.yaml
=> Content level 11 only

coursedata/level-defaults/id.yaml
Translate level 8,9,and 11, also fix endless loop in 13
=> Translate new levels and fix endless loop in 13

archive/level17-Additions.lark, grammars/level1.lark, grammars/level10-Additions.lark, grammars/level13-Additions.lark, grammars/level2-Additions.lark, grammars/level3-Additions.lark, grammars/level4-Additions.lark, grammars/level6-Additions.lark, grammars/level7-Additions.lark, grammars/level9-Additions.lark, hedy.py, tests/test_level_01.py
Fixes #885, allowing comments from level 1
=> Allows comments from level 1

app.py
We used to set an invalid value for the `quiz` page (`"None"`) and
in any case Online Masters wants to embed us.
=> chore: remove `X-Frame-Options`

app.py, quiz.py
The end score is shown as a percetage of the max score so that with different total scores the ratio is still in balance.
**Fix for**
In the quiz of level 6 the maximum score is lower than in previous quizzes. Students think they did a bad job because they get a lower score. Can we show the score as part of the total points they can get, e.g. score: 50 / 70
score 50/70 -> 71 %
=> The end score will be shown as a percentage of the total score/max score * 100

SEMANTICS.md
additions for semantics description in natural language
so far added level 2 and 3, not yet with types. 
Not yet complete.
=> semantics description in natural language additions

tests/Tester.py, tests/test_level_02.py, tests/test_level_06.py, tests/test_level_12.py, tests/test_level_18.py
Executes idea #2 of #1203
Not that this now causes a few tests to fail, I know these will be fixed by @boryanagoncharenko when the type system is strengthened, so we can merge this later (or disable the tests for now and merge this straight away)
=> Run generate Python code as part of multilevel tester

coursedata/adventures/en.yaml, coursedata/adventures/nl.yaml
Some updates to the turtle adventure
=> Updates stairs example (fixes #973) and more fixes to turtle adventure

app.py
Thanks for the tip @TiBiBa! Fixes #1371
=> Use proper lang arg

DESIGN.md, SEMANTICS.md
- Update SEMANTICS.md with information for levels up to 15. I am very much looking forward for this thing to be generated, because it will be out of date in a matter of days.
- Add info about type system to the DESIGN.md
**Fix for**
#1406 
- Read the paragraphs added to the DESIGN.md. Do you understand them? If not, what is missing
- Read the SEMANTICS.md file. Do you see mistakes?
**Checklist**
=> Update level semantics and type system design docs #1406

templates/view-program-page.html
In this PR we add the Hedy level in which the program was created to the program-view page. A feature that can be useful be grading submitted programs and/or get more insight in the created program.
**Fix for**
This PR fixes #1438
Share a program, visit through the copied link and notice that the Hedy level of creation is shown in the header
**Checklist**
=> Add created level to program-view

app.py, hedyweb.py
=> fix: new page loading mechanism crashes on requesting unknown page

tests/test_level_04.py
To make sure we don't break #965 later on
=> Test missing quotes until 17

coursedata/texts/en.yaml
A small typo stopped the confetti from working voor "Sing a song stories"
=> changed song to songs for working confetti

coursedata/adventures/en.yaml, coursedata/adventures/nl.yaml
Mainly changing 'in level x' to 'in this level', so the texts are accurate.
=> Clean up adventures

grammars/level12-Additions.lark, grammars/level14-Additions.lark, grammars/level5-Additions.lark, grammars/level6-Additions.lark, tests/test_level_06.py, tests/test_level_08.py, tests/test_level_11.py, tests/test_level_12.py, tests/test_level_17.py, tests/test_level_18.py
Allows = instead of `is` in comparisions.
=> Further work for #1475

coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml
Describe your changes in detail. Please use present tense without a subject to describe your PR, for example: "Fix**es** issue 123" or "Adds translations of levels 1 to 12 for Polish"
**Fix for**
Describe what issue or discussion your pr concerns
Describe how to run your code to see it is action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example.
**Checklist**
=> Update to the try codes and the introtexts in level 16 and 17

hedy.py, tests/Tester.py, tests/test_level_01.py, tests/test_level_02.py, tests/test_level_03.py, tests/test_level_05.py, tests/test_level_06.py, tests/test_level_07.py, tests/test_level_09.py, tests/test_level_10.py, tests/test_level_11.py, tests/test_level_12.py, tests/test_level_13.py, tests/test_level_15.py, tests/test_level_17.py, tests/test_level_18.py
To be used in program analysis, f.e. by the achievements
=> Adds all_commands function

hedy.py
Now the merger warns for duplicated rules: it tells the rule and the level where it's duplicated. 
**Fix for**
Fixes #1559 
There are no tests for checking the grammar, but you can try duplicating the print rule in, let's say, level 11, and it should output this message:
```
hedy/hedy.py:1645: UserWarning: The rule print is duplicated on level 11. Please check!
```
=> Adding warn message for duplicated rules when merging grammars

app.py, hedy.py, tests/test_level_01.py, tests/test_level_13.py, website/achievements.py
Fixes #1608 
@TiBiBa, you created a small issue in the achievements checking. The first mistake was that you parse an individual line, which works fine for lower levels but once we get indented lines that no longer works. Secondly, you did not wrap the achievements checking iin a try block, allowing the error to escape and block further processing, resulting in a very weird state, a correct program with a parse error. Took me a bit of debugging to find that one!
This PR fixes both issues, but can you check I implemented the right idea for hedy-ious? I am now checking all arguments of prints and checking if there are 10 similar ones, but I am not explicitly checking whether a loop is used, so in principle it is not 100% correct but I guess it will do?
=> Achievement parsing

website/achievements.py
Due to an incorrect argument on the achievements function call to verify submitted programs the user interface was not correctly shown when submitting a program as well as the submitting achievements could not be achieved. In this PR we fix this function call automatically fixing the issue.
**Fix for**
This PR fixes #1649.
Submit a program, notice that the view is updated without re-loading and an submitting achievement is shown if achieved.
=> [FIX] Removed incorrect argument on function calling preventing program submitting

coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml
=> #1610 Explain quotes after if in level 12

coursedata/quizzes/nl.yaml
changed nummer into nummers and nergen into nergens
**Checklist**
=> nummer --> nummers / nergen --> nergens

coursedata/level-defaults/nl.yaml
=> Update nl.yaml changed geta into getal

coursedata/adventures/nl.yaml
=> removed redundant 'hoe je'

coursedata/adventures/nl.yaml
**Translated a few words from English into Dutch.
In example Hedy code lvl 16, choice of weapons not the same as choices (ham vs rauwe ham)
In 'vooruitzicht' added 'dit' to sentence**
=> Translation Eng->NL and minor mistakes

coursedata/quizzes/nl.yaml
=> Very minor spelling fix: aanhanlingstekens ->aanhalingstekens

coursedata/texts/nl.yaml
=> Minor spelling: prive --> privé

coursedata/adventures/en.yaml, coursedata/level-defaults/en.yaml
Translates occurrences of Dutch words I've noticed in English content to English.
**Fix for**
#1827 (at least partially. I haven't read all the content, yet.)
Um … no idea, sorry.
**Checklist**
=> translate Dutch words in English content to English

coursedata/level-defaults/en.yaml
Fix a spelling error.
**Fix for**
(Not filed as an issue, yet, AFAIK. Filing directly as a PR, as the fix is trivial.)
Check on https://www.hedycode.com/hedy/2, first tab ("Level 2"), near the end of the text above the code and output areas.
**Checklist**
=> fix typo "amout" -> "amount"

coursedata/adventures/de.yaml, coursedata/adventures/en.yaml
Replaces "Thanks you" by "Thank you". 
**Fix for**
Not filed as an issue, as this is trivial.
Look at example code in Level 1, tab "Restaurant" in English and German.
**Checklist**
=> replace "Thanks you" by "Thank you"

grammars/level1.lark, grammars/level2-Additions.lark, hedy.py
- Remove TODOs which are no longer relevant
- Transform relevant TODOs to issues #1914 and #1913 
**Partially addressed **
#1632 
Read the #1913  and #1914 and check if they correctly capture the meaning of the removed TODO.
**Checklist**
=> Remove TODOs which are no longer relevant; transform relevant TODOs to issues

coursedata/quizzes/nl.yaml
Changed the wording of one question in the quizzes, fixes #1756
=> Issue #1756

.gitignore
changed the .gitignore back to excluding the complete .vscode folder.
=> reset to exclude complete .vscode folder

grammars/level3-Additions.lark, hedy.py, hedy_translation.py, tests/test_translation_level_03.py, tests/test_translation_level_04.py
=> Translates add, sleep, remove

content/adventures/nl.yaml
This PR fixes #1993.
Describe your changes in detail. Please use present tense without a subject to describe your PR, for example: "Fix**es** issue 123" or "Adds translations of levels 1 to 12 for Polish"
**Fix for**
Describe what issue or discussion your pr concerns
Describe how to run your code to see it is action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example.
**Checklist**
=> [BUG FIX] Fixed typo with incorrect level

content/quizzes/fr.yaml
Translation of the last 2 levels into French, and some small corrections on the previous levels
=> translation quiz 10 & 11 in french

hedy_translation.py, tests/test_translation_level_03.py, tests/test_translation_level_04.py
Oops #1985 had add and sleep in level 4 instead of 3!
=> move add/remove to level 3

content/adventures/nl.yaml, content/level-defaults/nl.yaml
=> Fixed #1996

coursedata/adventures/de.yaml
Provides missing translation for level 15 of 'dice' adventure.
**Fixes < issue or discussion number >**
< If this is a UI change, describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example >
< If this is a language change, add a few tests showing the difference >
**Checklist**
* If you're unsure about any of these, don't hesitate to ask. We're here to help!
=> Translate 'dice' adventue level 15 to German

website/programs.py
< Provide a one line summary of your changes in the Title of the PR >
< Changes in detail > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"
**Fixes < issue or discussion number >**
< If this is a UI change, describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example >
< If this is a language change, add a few tests showing the difference >
**Checklist**
Done? Check if you have it all in …
=> [BUG FIX] Fixes saving of programs

app.py
so we want to fall back to `name` in that case
=> with the weblate changes default_save_name can be empty

static/js/app.ts
#2155 fixed this for saving, but not for sharing. I am not 100% sure it catches all issues but since share is broken on main, I will push this one if it does not break tests, @TiBiBa can see if I missed anything when he is back.
=> Removes old check on share

coursedata/adventures/ar.yaml, coursedata/adventures/bg.yaml, coursedata/adventures/bn.yaml, coursedata/adventures/cs.yaml, coursedata/adventures/de.yaml, coursedata/adventures/el.yaml, coursedata/adventures/en.yaml, coursedata/adventures/es.yaml, coursedata/adventures/fr.yaml, coursedata/adventures/fy.yaml, coursedata/adventures/hi.yaml, coursedata/adventures/hu.yaml, coursedata/adventures/id.yaml, coursedata/adventures/it.yaml, coursedata/adventures/nl.yaml, coursedata/adventures/pt_BR.yaml, coursedata/adventures/pt_pt.yaml, coursedata/adventures/sw.yaml, coursedata/adventures/zh_Hans.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml
I hope I didn't break it by using |- instead of the \n... We'll see...
=> Improved the Dutch levels 1 2 and 3

coursedata/level-defaults/nl.yaml, coursedata/quizzes/nl.yaml
Some text was not translated yet. So I translated the English examples for level 1 to Dutch.
=> translate English examples level 1 to Dutch

tests_e2e.py, website/database.py, website/programs.py
< Provide a one line summary of your changes in the Title of the PR >
< Changes in detail > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"
**Fixes < issue or discussion number >**
< If this is a UI change, describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example >
< If this is a language change, add a few tests showing the difference >
**Checklist**
Done? Check if you have it all in …
=> [BUG FIX] Truly fixes saving bug

coursedata/adventures/nl.yaml
There is currently a problem of over-coloring, and until it is fixed properly, I have replaced the word with a synonym, to get around the problem.
`vraag -> antwoord`
=> vraag become antwoord

coursedata/adventures/nl.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml
All the examples codes are correct and shown on the right side of the screen in both the adventures and the level defaults. 
Fixes #2223 and #2257
=> Example codes clean up nl

coursedata/adventures/en.yaml
< Adds "# finish this code" to the example code provided in Rock - Level 9 so users understand that further code must be written for the program to become fully functional >
**Fixes < #1969 >**
- Go to http://localhost:8080/hedy/9#rock
- Look at the example code provided
**Checklist**
=> Adds clarifying comment to Rock - Level 9

content/adventures/de.yaml, content/adventures/es.yaml, content/pages/for-teachers/de.yaml, content/quizzes/de.yaml, translations/ar/LC_MESSAGES/messages.po, translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/el/LC_MESSAGES/messages.po, translations/es/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fr/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/hi/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/nb_NO/LC_MESSAGES/messages.po, translations/nl/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po
fix merge conflicts on po header files and clean up headers to get them in sync.
=> Fix-weblate-merge-conflict

content/quizzes/nl.yaml
=> fix for #2457

translations/fr/LC_MESSAGES/messages.po
fix merge conflict with weblate
=> Fix-merge-conflict

content/pages/for-teachers/nl.yaml
For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present tense!)
* If this is a UI change: _describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example_
* If this is a language change: _add a few tests showing the difference_
**Checklist**
If you're unsure about any of these, don't hesitate to ask. …
=> [BUG FIX] Removes faulty empty dict from nl for-teachers YAML

app.py, hedy_content.py
Linelength shortened like discussed.
Some unused variables or double lines removed. 
Some Sonarlint hints applied.
=> PEP8 and some Sonarlint hints applied

hedy.py, hedy_translation.py, tests/test_level/test_level_02.py, tests/test_level/test_level_03.py, tests/test_level/test_level_04.py
Refactored tests for level 4
Refactor tests for level 4
**Fixes #2436**
The PR is meant to refactor and address minor bugs related to improving the tests. Examine the changed tests files:
- They should follow the layout described in the beginning of the file
- They should contain no TODOs or commented code (there is a single TODO meant to avoid merge conflict with another PR)
**Checklist**
=> Refactored tests for level 4 #2436

hedy_translation.py
For some reason the translate keywords functionality in `hedy_translation` does seem to crash on some programs, making the explore page unaccessible. In this PR we fix this by surrounding the function with a big ugly try/catch until we figure out the actual issue. This should enable us to update production again as it is already too long behind.
**Fixes**
Deploy to Alpha, verify that the `/explore` page is working again.
=> [BUG FIX] Adds try catch to translation to prevent /explore from crashing

website/database.py
This should hopefully fix Alpha crashing on #2523.
=> [FIX] Specifies sort key on public programs

messages.pot, translations/ar/LC_MESSAGES/messages.po, translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/el/LC_MESSAGES/messages.po, translations/en/LC_MESSAGES/messages.po, translations/es/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fr/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/hi/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/nb_NO/LC_MESSAGES/messages.po, translations/nl/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po
Adds translations that should already be added in #2591.
=> Adds forgotten stop button nl/en translations

content/adventures/en.yaml
Added an easier example to the turtle adventure level 2 to show how you could use variables.
=> Issue #2385

templates/incl-editor-and-output.html
Switched button order when clicking on the debugger. From  ⏩🔁🛑 to 🔁🛑⏩
**Fixes #2732**
Click on the debugger button, check whether the order of the buttons is: 🔁🛑⏩
=> Switched order of debugging buttons

content/adventures/ar.yaml
Making Weblate happy, one commit at a time :D
=> Weblate fix

website/achievements.py
=> Revert "[BUG FIX] Gotta Use Them All achievement is achievable again"

website/admin.py
This PR fixes an issue where the admin achievements overview would crash due to a missing import.
=> [HOT FIX] Adds missing import on admin page

TRANSLATING.md
For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present tense!)
* If this is a UI change: _describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example_
* If this is a language change: _add a few tests showing the difference_
**Checklist**
If you're unsure about any of these, don't hesitate to ask. …
=> [FIX] Set TRANSLATING Discord link to a never expire link

static/js/app.ts, utils.py
This could have been a tad simpler :)
=> Simplify converter

content/adventures/de.yaml, content/adventures/hu.yaml, content/adventures/nl.yaml, content/adventures/pt_BR.yaml, content/adventures/pt_PT.yaml
=> Missed a few headers in #2887

content/parsons/es.yaml, content/parsons/et.yaml
In this PR we manually copy the et Parsons translations that where overwritten by a structure change. We copy them from the old file and store them into the new structure, making sure that no contribution is lost.
**Fixes**
This PR fixes #2921.
Nothing to test
=> et Parsons contribution is correctly translated again

tests/Tester.py, tests/test_snippets/test_adventures.py, tests/test_snippets/test_level_commands.py, tests/test_snippets/test_parsons.py
In this PR we clean-up the Tester code, removing some duplicate functions.
**Fixes**
This PR fixes #2963.
Nothing, GitHub should handle everything.
=> [CLEAN-UP] Removes duplicate tester functions

website/statistics.py
**Address incorrect metrics about program runs and error percentage displayed on the class overview page**
_Changes the consolidation of program run metrics, so that total runs include successful and error runs._
**Fixes #2870 **
* Log in as a admin and navigate to the /admin/classes page. Ensure that locally you have classes and enough program runs to test. Ensure that the weekly and total error percentages never goes above 100%. Generate more program runs and ensure the program run metrics adapt accordingly to the program runs you execute. Check the extremes: a class without any runs, a class with only successful runs and a class with only errors.
=> Fix incorrect program run metrics on the admin class overview page #2870

templates/admin/admin-achievements.html, templates/admin/admin-adventures.html, templates/admin/admin-classes.html, templates/admin/admin-logs.html, templates/admin/admin-stats.html, templates/admin/admin-users.html, website/admin.py
In this PR we make some QoL changes to the admin views. First we make sure the adventures are sorted by `last updated`, to always show the last updated adventure first. We also fix an incorrect column title and improve the styling of all admin view headers.
**Fixes**
This PR fixes #3004.
Verify that the adventures are now sorted by last updated, also verify that the column name is changed from `created` to `last updated`. All other changes are to simplify the styling and shouldn't influence any functionality or UI.
=> [UI IMPROVEMENT] Improves admin views

content/pages/en.yaml, content/pages/nl.yaml
=> Add codeweek podcast

templates/admin/admin-users.html
We fix a small issue where the function call for changing a user mail was broken.
**Fixes**
This PR fixes #3161.
Log in as an admin and verify that you can change a user email on the users page overview.
=> [BUG FIX] Admin functionality to change user mail works again

translations/ar/LC_MESSAGES/messages.po, translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/el/LC_MESSAGES/messages.po, translations/en/LC_MESSAGES/messages.po, translations/eo/LC_MESSAGES/messages.po, translations/es/LC_MESSAGES/messages.po, translations/et/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fr/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/he/LC_MESSAGES/messages.po, translations/hi/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/ja/LC_MESSAGES/messages.po, translations/ko/LC_MESSAGES/messages.po, translations/nb_NO/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sv/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tn/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po
Another try for #3201 now that we have removed the line numbers
=> Restore Access before assign message in all langs

translations/ar/LC_MESSAGES/messages.po, translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/el/LC_MESSAGES/messages.po, translations/en/LC_MESSAGES/messages.po, translations/eo/LC_MESSAGES/messages.po, translations/es/LC_MESSAGES/messages.po, translations/et/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fr/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/he/LC_MESSAGES/messages.po, translations/hi/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/ja/LC_MESSAGES/messages.po, translations/ko/LC_MESSAGES/messages.po, translations/nb_NO/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sv/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tn/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po
=> Remove double ids

templates/admin/admin-classes.html, website/admin.py
Adds 'created at' column to admin classes overview
=> Adds 'created at' column to admin classes overview

templates/signup.html
Fixes #3220
Create an account and observe that programming experience is stored in the database again
=> [BUGFIX] Correctly store programming experience

content/quizzes/en.yaml, content/quizzes/nl.yaml
=> [CONTENT] Remove spaces in nl Quiz

website/auth.py
=> [BUGFIX] changing email address works again 

utils.py
=> [FIX] adds year to version

content/quizzes/nl.yaml
For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present tense!)
* If this is a UI change: _describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example_
* If this is a language change: _add a few tests showing the difference_
**Checklist**
If you're unsure about any of these, don't hesitate to ask. …
=> fixes #3279

app.py, content/pages/en.yaml, content/pages/nl.yaml, hedyweb.py, templates/join.html
To show in the Strangeloop talk :)
=> [CONTENT] Add join route

grammars/level6-Additions.lark, hedy.py, tests/test_level/test_level_06.py
=> [BUGFIX] fixes printing 5 - 5 

content/commands/nl.yaml, hedy_content.py
Fixes #3328 (explanation provided on the issue)
Also fixes a few small issues in the Dutch commands
=> [LOCALE] Show local keywords in quiz when enabled

app.py, website/achievements.py, website/statistics.py
Leftover mistakes from previous refactor
=> [FIX] Fix use of DATABASE in statistics module

hedy_content.py
This PR sorts the research papers by year in descending order. It also puts the year it was published in before the research paper's title.
**Fixes #3365**
* If this is a UI change: 
* Go to http://localhost:8080/learn-more
* Scroll down to the `Hedy Research` section
**Checklist**
=> Sort research papers by year in descending order

templates/incl-adventure-tabs.html, templates/incl-menubar.html, templates/layout.html
Makes sure fonts are displayed properly and also uses full width on smaller devices for adventure texts and example codes. Also keeps the logo nice and round.
Makes sure fonts are displayed properly and also uses full width on smaller devices for adventure texts and example codes. Also keeps the logo nice and round.
There's probably a lot more that can be done, but this should be considered a first step.
**Fixes #3379**
* Use the inspector in your browser and enable mobile view (how to do that depends on the browser). Also you could use a mobile device to view the Hedy version on your computer. For that they need to be on the same network.
The changes are template only, so it …
=> Improves readability on mobile devices

CONTRIBUTING.md
Adds a fix to `CONTRIBUTING.md` pages with an error when running Hedy locally with some IDE's on Windows machines.
Fixes #3301
=> CONTRIBUTING.md add fix to pages with error when running locally

content/adventures/en.yaml
**Fixes**
This PR fixes #3434.
=> Fixes incorrect variable in English turtle example

.github/workflows/unittests.yml, build-tools/github/validate
It does not yet seem to work well (see original PR) 
Reverts Felienne/hedy#3456
=> Revert "[TESTING] Excludes code tests when no changes are made there"

app.py
The implemented fix in #3505 is incorrect and actually breaks our adventures. In this PR we revert the commit.
=> Reverse #3505

WEBLATE.md, content/quizzes/ar.yaml, content/quizzes/bg.yaml, content/quizzes/bn.yaml, content/quizzes/cs.yaml, content/quizzes/de.yaml, content/quizzes/el.yaml, content/quizzes/es.yaml, content/quizzes/fa.yaml, content/quizzes/fy.yaml, content/quizzes/hi.yaml, content/quizzes/hu.yaml, content/quizzes/id.yaml, content/quizzes/it.yaml, content/quizzes/pl.yaml, content/quizzes/pt_BR.yaml, content/quizzes/pt_PT.yaml, content/quizzes/ru.yaml, content/quizzes/sw.yaml, content/quizzes/tr.yaml
#3273 was fixed in Weblate in English, but this does not transfer to other languages automatically
=> [CONTENT] Fix 3273 in other languages

templates/quiz.html
As requested by @MarleenGilsing!
**Fixes**
This PR fixes #3553
=> [QoL fix] Changes location of start quiz button

content/quizzes/en.yaml, templates/quiz.html
cleaned up level 1 to 11 english quizzes
=> clean up level 1 to 11 quiz

TRANSLATING.md
Also add a clarification of who to mention in case of merge conflicts.
=> Fix typos in TRANSLATING.md

build-tools/heroku/on-deploy.sh, translations/pa_Arab_pk/LC_MESSAGES/messages.po
#3594 did not yet solve the Punjabi issue
=> [FIX] Add folder, only make if non existent

templates/incl-menubar.html
We improve the language dropdown UI by splitting the column into two columns, making sure we don't need to scroll to select our relevant language:
**Fixes**
This PR fixes #3601
Verify that the new UI is in place and no languages are missing.
=> [UI IMPROVEMENT] Improves language dropdown UI

content/adventures/en.yaml
Start the name of the PR with one of the relevant prefixed in the title of the PR:
* [LANGUAGE] -> changes related to grammars or the transpiler
* [FIX] -> solving a bug
* [CHORE] -> things unrelated to the code, such as mergify scripts
* [REFACTORING] -> should not change anything, cleanup of code
* [UI] -> improvements and changes of the Hedy user interface
* [TESTING] -> changes made to the test suite
* [BACKEND] -> changes to the internal logic of the Hedy website
Finish the name of the PR with a clear description of the changes and delete the lines above from the description.
_Changes in detail. For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present …
=> Changed the color feature of turtle to level 4

.github/workflows/deploy-to-prod.yml
I copy-pasted something from the internet, which turned out not to work.
According to https://docs.github.com/en/actions/learn-github-actions/contexts#github-context, `actor` is a string and not an object.
Just check against individual usernames instead of roles.
Run the workflow and see if it works.
=> [CHORE] Fix prod deploy workflow

hedy.py, tests/test_level/test_level_04.py, tests/test_level/test_level_10.py
Some example snippets were giving the wrong issue. This fixes #3712.
I added 2 new tests that now pass.
=> [FIX] throw also on "_ " and " _" and in indenter

CONTRIBUTING.md
New contributors find it hard to see what to work on, and sometimes pick up stuff we are still making our minds up about, so let's be a bit more deliberate about this!
=> [DOCS] Update CONTRIBUTING.md

tests/test_level/test_level_07.py
Fixes #3669
The _test_if_pressed_repeat_ test has been modified in level 7.
=> [BUG] Fix Dead level 07 test

templates/admin/admin-users.html, templates/admin/admin.html, tests/cypress.config.js, tests/cypress/e2e/admin_page/user_overview/return_to_admin_page.cy.js, tests/cypress/e2e/admin_page/user_overview/view_all_users.cy.js, tests/cypress/e2e/admin_page/user_overview/visible_attributes_checkboxes.cy.js, tests/cypress/e2e/tools/navigation/nav.js
Added cypress.env variables to make it the code base more maintainable
Added id's to buttons
Added goToAdminUsersPage
Fixes #3705 
Run in the /tests folder:
```
npx cypress run --spec cypress/e2e/admin_page
```
=> [TESTING] Fixed some problems with admin page test, made them more neat

templates/incl-editor-and-output.html
https://github.com/hedyorg/hedy/pull/3602 accidentally reintroduced an error we previously fixed in #3674 (I guess PEP was not happy about the singe/double quotes but they are really needed in this line)
=> Reapply 3674

tests/cypress.config.js
So we can run the Cypress tests in the cloud!
=> [CHORE] connect Cypress tests to Hedy dashboard

templates/for-teachers.html, tests/cypress/e2e/for-teacher_page/class_page/logs_button.cy.js, tests/cypress/e2e/for-teacher_page/class_page/statistics_button.cy.js, tests/cypress/e2e/for-teacher_page/class_page/stats_page/data_buttons.cy.js, tests/cypress/e2e/for-teacher_page/class_page/stats_page/stats_to_class.cy.js, tests/cypress/e2e/for-teacher_page/customize_class_page/ind_adv_button.cy.js, tests/cypress/e2e/for-teacher_page/customize_class_page/opening_dates.cy.js, tests/cypress/e2e/for-teacher_page/customize_class_page/quiz_score.cy.js, tests/cypress/e2e/for-teacher_page/customize_class_page/test_checkboxes.cy.js, tests/cypress/e2e/signup_page/birthyear_create_account.cy.js, tests/cypress/e2e/signup_page/country_create_account.cy.js, tests/cypress/e2e/signup_page/email_create_account.cy.js, tests/cypress/e2e/signup_page/gender_create_account.cy.js, tests/cypress/e2e/signup_page/language_create_account.cy.js, tests/cypress/e2e/signup_page/loginbutton_create_account.cy.js, tests/cypress/e2e/signup_page/newsletter_create_account.cy.js, tests/cypress/e2e/signup_page/password_create_account.cy.js, tests/cypress/e2e/signup_page/privacyterms_create_account.cy.js, tests/cypress/e2e/signup_page/programming_experience_create_account.cy.js, tests/cypress/e2e/signup_page/username_create_account.cy.js, tests/cypress/e2e/teacher_page/Manual/clicking_discord_link.cy.js, tests/cypress/e2e/teacher_page/Manual/clicking_yt_link.cy.js, tests/cypress/e2e/teacher_page/Manual/frequent_mistakes_button.cy.js, tests/cypress/e2e/teacher_page/Manual/frequent_mistakes_levels_button.cy.js, tests/cypress/e2e/teacher_page/Manual/introduction_button.cy.js, tests/cypress/e2e/teacher_page/Manual/preparations_button.cy.js, tests/cypress/e2e/teacher_page/Manual/teaching_button.cy.js
[TESTING, CYPRESS]
As requested in Discord, I have adjusted the incorrect function imports in the front-end tests. Moreover, I have renamed file- and folder names according to the coding agreements.
Fixes #3808 
All tests should still work as before!
=> [TESTING, CYPRESS] 3808 testing fixing import errors in front end tests

tests/test_snippets/test_parsons.py
Oops I left a boolean on (luckily no tests broke in the mean time)
=> [FIX, TESTING] Fix parsons tester

content/keywords/te.yaml
This PR builds upon #3855 where a lot of files are changes where we only have to add the YAML to fix everything. The on-deploy and Weblate will take care of the rest.
=> Adds keywords translations for Telugu

app.py
It's hard to debug server issues (like a request flood) with the current information.
Log some more fields for every request, so we have a better chance of identifying issues.
This change will show up in the server logs after deploying.
=> [CHORE] Log more information about page requester

app.py, templates/explore.html
#3875 improved the performance of /explore but a few small issues remained, there are fixed in this PR:
* Nothing is shown when no programs are found
* The level selector hopped back after search
=> [FIX] Show text is no programs found and fix level selector

.github/workflows/generate-snippet-hashes.yml
Generate hashes each Sunday, see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
=> [CHORE] Create generate-snippet-hashes.yml

content/quizzes/nl.yaml
Removed quotes in quiz level 7: question 8, 9 & 10
**Fixes #3949**
* Removed quote in the answer (question 8)
* Added quote in the question (question 9)
* Removed quote in the question (question 10)
=> [FIX] Removed quotes in quiz level 7: question 8, 9 & 10

templates/incl-menubar.html
A very easy fix:
**Fixes**
This PR fixes #3969
Filter on a language, notice the display difference
=> [UI] Change filtered display of language dropdown

app.py, templates/certificate.html
Certificates page can now be rendered for everyone giving some fun statistics including the highest completed level.
=> Certificates can now be created for every level

hedy.py, tests/test_level/test_level_04.py
Fixes #3991.
Fun example to test in level 9:
```python
print "Lets Draw!"
repeat 30 times
if w is pressed
forward 20
if a is pressed
turn -90
if d is pressed
turn 90
if x is pressed
clear
print "Cleared!"
```
When using the _clear_ keyword it should now also clear the turtle canvas.
=> [LANGUAGE] Add clear to turtle

content/adventures/en.yaml, content/adventures/nl.yaml, hedy_content.py
See https://github.com/hedyorg/hedy/discussions/3930
=> [CONTENT] Make exercises more explicit in level 11

content/adventures/en.yaml, content/adventures/nl.yaml, hedy_content.py
Level 1 2 and 3 have better exercises now in Dutch and English, I still have to finish level 4, 5 and 6.
=> [CONTENT] Improve exercises level 1 to 3 NL and EN

content/adventures/nl.yaml, hedy_content.py
"Hot fix" for Dutch since I am teaching this in 1 hour. Will fix the other languages soon.
=> [CONTENT] Fixes in assignments level 12 and 13

tests/cypress/e2e/for-teacher_page/class_page/create_accounts_page/create_accounts.cy.js
=> [Fix] Flaky Create accounts Cypress test

templates/teacher-manual.html
Als improves the responsiveness in general of this page:
**Fixes**
This PR fixes #4068
Verify that the teacher manual nav bar items never shift, regardless of screen size and language.
=> [UI BUG FIX] Fixes shifting menu item in teacher manual

tests/cypress/e2e/hedy_page/syntax_highlighting.cy.js
The name says it all.
`npm run cypress-gui`, run the new test by hand. Or observe that the GitHub Actions tests pass.
=> [CHORE] Add cypress test of syntax highlighting

CONTRIBUTING.md
OMG this will minimize future conflicts, hoe did not we not think of this before?!
=> [CHORE] Sort keys in pybabel extract

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md
Corrects/clarifies minor things in language and markdown syntax in development documentation
**No related issue**
I made these edits following "the boy-scout rule" while I was reviewing the documentation myself for the first time. This PR can safely be ignored and closed since it is extremely low priority. I am mostly making this PR to establish my PR flow is correct.
Review these documentation changes.
**Checklist**
- [-] Links to an existing issue or discussion
=> [CHORE] Minor development documentation edits

content/quizzes/en.yaml, content/quizzes/nl.yaml
Redo of #4131 (I messed up the merge) updating quizzes in levels 8 to 13. Also fixes https://github.com/hedyorg/hedy/issues/2380
=> [CONTENT] Quizzes fix redo

templates/level-page.html
The title should be self-explanatory, when the current user is not in a class, hide the submit button. Similarly we might want to hide the bar all together when a user is not logged in. But I'm not sure if that is desirable. I did find two new bugs when working on this, still have to make issues on them:
- When logged in and navigating to a join link, you are logged out (this should not be the case!)
- When joining a class the value on `current_user()` is not updated, the user is required to log out / log in again to set this right.
**Fixes**
This PR fixes #4154.
=> [UI] Hide submit button on code page when not in class

content/quizzes/en.yaml
Fixed #4126  in english for: 
Level 1: question 2, 5
Level 2: 6
Level 3: 1
Level 5: 1, 6, 7, 8
Level 7: 4
Level 11: 1
Level 13: 2, 10
The preview didn't work, so I didn't check it with the local host, so I might need to correct some mistakes (next week).
=> #4126 Keyword quiz highlight

templates/incl/adventure-tabs.html
Fixes #4217 (although this also inspired #4221 with more experimentation)
=> [UI] Drop second header

static/js/index.ts
The current contents can be rewritten to be more clear.
=> [CHORE] Update comments in index.ts

templates/quiz/hx-question.html
=> [FIX] converts newlines to br in quiz options

app.py
Adds a new function to render the maximum level reached by the user in a quiz when they access the /hedy path.
**Fixes #4219*
Log in as a one of the students in the database (student1 to student5), and complete a quiz. Then go to the Hedy root and see if the next level is shown!
=> [UI] Adds function to render maximum level

templates/customize-class.html, tests/cypress/e2e/for-teacher_page/customize_class_page/customize_class.cy.js, tests/cypress/support/commands.js
This seems to fix the failing cypress test on my machine.
I'm not sure why, exactly (if it keeps on working on GitHub).
=> [FIX] Cypress test

static/js/app.ts
This code dates from 3 years ago, was a first attempt at code persistence, and isn't very useful anymore. Let's get rid of it.
Fixes #4330.
Everything works exactly the same (but with less confusion reviewing).
=> [FIX] Remove reference to session storage

content/adventures/en.yaml
Start the name of the PR with one of the relevant prefixed in the title of the PR:
* [LANGUAGE] -> changes related to grammars or the transpiler
* [FIX] -> solving a bug
* [CHORE] -> things unrelated to the code, such as mergify scripts
* [REFACTORING] -> should not change anything, cleanup of code
* [UI] -> improvements and changes of the Hedy user interface
* [TESTING] -> changes made to the test suite
* [BACKEND] -> changes to the internal logic of the Hedy website
Finish the name of the PR with a clear description of the changes and delete the lines above from the description.
_Changes in detail. For example: "**Adds** translations of levels 1 to 12 to Polish" (note the use of present …
=> Small fixes in adventures

tools/logs-to-db.py
In #4362 we download all dynamo tables to a local db, this adds the logs from s3 so we can have a more complete view all data
=> [DATA] adds script to add the logs from s3 to a local sqlite db

website/for_teachers.py, website/statistics.py
There's an error both in the customizations and in the new grid page. I'm not sure if this is a case just of spurious data in the alpha environment or if this also happens in production. Either way this bit of defensive programming should do the trick.
=> [FIX] Fix crash in grid page and in class customization

website/statistics.py
Just to check something in the logs! This is temporary and Ill revert this soon!
=> Debug print for programs in the grid page

content/adventures/en.yaml, content/adventures/nl.yaml
Adds a warning to a intentionally not working example code
=> Adds a warning to a intentionally not working example code

tests/test_snippets/test_adventures.py
We used to hard-code all names, but that list is getting too long and this is nicer!
=> [TESTING] Skip all default tabs rather than use a hard-coded list

content/adventures/es.yaml, content/parsons/pt_BR.yaml, grammars/level5-Additions.lark
The last Weblate merge had some open issues, this fixes them all.
=> [CONTENT] Fix snippets

content/adventures/en.yaml, content/adventures/fr.yaml, content/parsons/fr.yaml
=> [CHORE] Fix weblate merge conflicts

hedy.py
=> [BUG] Escape quote in list message

translations/en/LC_MESSAGES/messages.po
@Mark-Giesen wants to test something with Weblate!
=> [CHORE] Add test string to translations files

README.md
Hello, in this PR I am adding links to the existing issue templates in the project, to speed up the issue generation process for future contributors. Also add the logo and edit the content by removing all the html to keep only markdown code, also, add thanks to the contributors of this project in the final part.
Attached screenshot of the start:
Attached screenshot of the end:
=> [DOCS] Readme Update

content/adventures/en.yaml, content/adventures/tr.yaml
@Mark-Giesen  @Felienne 
As we discussed in #4635, the changes are simple and includes only 2 files to test the "needs editing" problem of Weblate.
_Expectation_
- Changes made to English should be reflected to all other languages and they should be marked as "needs editing"
- Changes for other languages, small or big, should be seen by Weblate as "needs editing"
- so that translators can see and react to changes and start proof reading.
For the merge, automatic tests should be enough. But it possibly needs Weblate lock & sync.
for the actual result, these three links must have "needs editing" checkbox active after the sync:
- https://hosted.weblate.org/translate/hedy/adventures/tr/?checksum=3b28260d4fdbc59b
- …
=> [TESTING] Test for the "needs editing" problem of weblate

static/js/app.ts, templates/level-page.html
The problem was an extra space in " en"; https://github.com/hedyorg/hedy/blob/main/templates/level-page.html#L81.
- add previous hash to next url
- remove unintended, extra space #4579
- minor changes
=> [BUG] language switcher

README.md
Added a "Back To Top" button at the end of Readme.md file which will act as a scroll button .When clicked it will redirect us to the top of the file
* [UI] -> improvements and changes of the Hedy user interface👾
=> Added "Back To Top" button

README.md
Inside section "**I have an idea for what you should build or improve**"
Bug - " **For full community guideline, please..**"  should be " **For full community guidelines, please..**"
Enhancement - "**discuss ideas, get in touch..**" -> "**discuss ideas, and get in touch..**"
Screenshot-
=> [DOCS] Update README.md - one fix and enhancement

content/adventures/en.yaml, content/adventures/kmr.yaml, content/adventures/nl.yaml, content/adventures/ro.yaml
=> changes "level 6" to "a previous level" in the level 7 story adventure

content/quizzes/en.yaml
This replaces the old PR about quiz level 16
=> [CONTENT] Quiz level 16 in English

utils.py
Patches #4726, not in a great way, I'd rather use a well-defined regex but I could not get that to work and this is blocking someone, so this will do not for now.
=> [FIX] Email validation

hedy.py, tests/test_level/test_level_06.py
Fixes #4713
I added a new test and I did not break any existing ones :)
=> [LANGUAGE] add exception for is and =

templates/level-page.html
Fixes #4858 
Level 18 was missing in the level_dropdown
=> [BUG] Add missing level18 in level dropdown

tests_e2e.py, website/database.py, website/for_teachers.py, website/public_adventures.py
DynamoDB doesn't support boolean indexes. As a result, we have to convert these to numbers.
=> [BUG] fix adventure public index

app.py, hedy_translation.py
=> 🐞 correctly translate empty string

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/content.md, .github/ISSUE_TEMPLATE/idea-for-the-hedy-interface.md, .github/ISSUE_TEMPLATE/idea-for-the-hedy-language.md, .github/PULL_REQUEST_TEMPLATE.md
Updates bug templates with new emoji system
=> 🧹 update emojis

dodo.py
Currently, the checked-in Tailwind file has been generated with an older version of Tailwind than the version of Tailwind we actually say we depend on. You can tell, because the version number is right there in the generated file.
The reason is because the person generating that CSS file (me) had forgotten to run `npm ci` before running Tailwind. This will now cause the next PR to have unnecessary diffs in their generated CSS file if they accidentally have different versions of Tailwind installed for whatever reason (either they did run `npm ci`, or the last time they ran it Tailwind was at a different version than my version).
Add the running of `npm ci` to the `doit` script, so that this can't happen anymore: it will be run automatically for you if necessary.
Run `doit …
=> 🧹 Keep NPM dependencies updated using doit

app.py, templates/slides.html
Fixes both issues described in #5054
=> 🪲 Fix slides

dodo.py
Run `doit devserver` and it should work now.
=> 🪲 remove env variable passed through doit

.github/workflows/update-javascript-on-main.yml
Used the wrong source of the repository name, and forgot to remove an `if`.
=> 🚚 Fix autoupdate script for push events on main

.github/workflows/update-javascript-on-main.yml
Should recognize `pull_request_target` in addition to `pull_request`.
=> 🚚 Handle pull_request_target event

content/adventures/tn.yaml, static/js/message-translations.ts, translations/nl/LC_MESSAGES/messages.po
Fixes #5239 and resolves a small issue in tn
=> 📜 Remove double quotes

.github/workflows/autoapprove.yml, .github/workflows/resolve-weblate-conflict.yml, .github/workflows/update-javascript-on-main.yml, dodo.py, tools/merge-weblate-resolving-conflicts.sh
Weblate sometimes still creates commits that lead to conflicts. Add a script that will automatically resolve them. If it works, we  can start  running it automatically whenever necessary.
=> 🚚 GitHub workflow to automatically resolve Weblate conflicts

.github/workflows/resolve-weblate-conflict.yml
GitHub Actions won't run otherwise
=> 🚚 Push with the correct token

translations/zh_Hans/LC_MESSAGES/messages.po
This PR merges pending commits from the Weblate repository that are conflicting with changes on `main`, while resolving conflicts in favor of the Weblate side.
=> Translations from Hosted Weblate

.github/workflows/update-weblate.yml
The GH CLI won't work without this token.
=> 🚚 Add missing token to Update Weblate workflow

.github/workflows/unlock-weblate.yml
If not, it won't have access to secrets.
=> 🚚 Unlock Weblate script should run as `pull_request_target`

.github/workflows/resolve-weblate-conflict.yml
If it doesn't, it will fail as soon as it tries to lock the repo.
=> 🚚 Resolve weblate config script should install 'wlc'

app.py, website/programs.py
Also fixes that only modified programs are shown in 'My public profile'
Is it correct that we don't have saved programs in the test database? Then it's a bit difficult to test:
1. Go to programs.py and comment out line 101, 104 and 106
2. Save a few programs, check if they are shown in `/my-programs`
3. Make a few public and see if they are shown in 'My public profile'
=> 🪲 Old programs without 'is_modified' are shown

templates/slides.html
=> 💻 larger margin in slides

static/css/additional.css, templates/quiz/partial-review-question.html
Fixes https://github.com/hedyorg/hedy/issues/5129
**How to test?**
- answer quiz questions (e.g., first 4 questions of level 11)
- make sure that the content of any code blocks is aligned correctly.
=> 🪲 fix quiz answers position

.github/workflows/deploy-to-prod.yml
Allows @jpelay to also deploy (I think, you never know with GitHub actions...)
=> 🧹 Update deploy-to-prod.yml

tests/cypress/e2e/for-teacher_page/class_page/add_student_invite_by_username.cy.js
I added a wait and an intercept, since that's what's causing the issue
=> 🧪 Fix invite student test

content/adventures/pt_BR.yaml
As you can see, all "Draw it" sections are still in English, so I translated them:
I hope this helps a little bit. It's my first PR, a small one to engage myself little by little. If it gets accepted I can create others. Thank you!
=> 📜 Translate some texts to pt_BR

app.py, templates/level-page.html
Fixes #5641 
Go to /adventure/<adventure> and see if the dropdown works
Go to /hedy or other pages that should have the level dropdown and make sure it's there and works
=> 🪲 Fix bug for level dropdown in /adventure

content/adventures/pt_BR.yaml, content/parsons/pt_BR.yaml, content/quizzes/pt_BR.yaml
**Translation to pt_BR**
Translation of entire level 3, except for the quiz which is partially translated.
You can start the server locally ( <code>doit run devserver</code> ) and go through level 3, tab by tab. The quiz is partially translated.
I ran <code>python -m pytest -n autoto</code> and all tests passed:
=> 📜 Translate level 3 to pt_BR (partial translation)

website/auth_pages.py
It was my bad because I forgot to change this in the last PR
=> 🪲 Redirect to hedy page instead of landing page

content/adventures/de.yaml, content/slides/pl.yaml, static/js/message-translations.ts, translations/pl/LC_MESSAGES/messages.po
Corrected Polish slides in attempt to fix #5783
=> 🧹 Weblate fix

.github/workflows/deploy-to-prod.yml
Yesterday we merged #5841 but it didn't actually send the message, looking through the code of the action some parameters cause it to fail, removing them should make it work.
=> 🚚 Fix Discord Webhook

.github/workflows/deploy-to-alpha-manually.yml, .github/workflows/deploy-to-alpha.yml
Fixes #5862
The new github action should actually work and not be skipped. The automatic deployment should work too.
=> 🚚 Add a separate github action for manually deploying to Alpha 

app.py, templates/view-program-page.html
When trying to access a program from a user that's not in a class, the paged failed due to indexing an empty dictionary.
* Go to  http://localhost:8080/hedy/30bd4e4ce84f40bca40b24b9295e1483/view and it should open normally.
=> 🪲 Fix view programs for non students

content/adventures/ca.yaml, content/cheatsheets/es.yaml, content/client-messages/es.yaml, content/pages/es.yaml, content/parsons/es.yaml, content/quizzes/kab.yaml, content/slides/es.yaml, content/tutorials/es.yaml, static/js/message-translations.ts, translations/es/LC_MESSAGES/messages.po
=> 📜 Weblate errors

Procfile
Fixes broken alpha environment
Check if alpha is back up
=> 🚚 Attempt to fix alpha

.github/workflows/deploy-to-alpha-manually.yml, Procfile
Fixes alpha returning 503
Alpha is working
=> 🚚 Fix failing alpha env

.github/workflows/resolve-weblate-conflict.yml, .github/workflows/unlock-weblate.yml, .github/workflows/update-weblate.yml
Remove all references to the Quizzes Weblate component.
Fixes #6102
There is not really a way to test before the merge. After the merge, the scripts should not fail.
=> 📜 Remove quizzes weblate component

content/adventures/cs.yaml, tests/cypress/e2e/public_programs/view_programs.cy.js
Fixes #6145
Automatic tests should pass
=> 📜 Fix daily Weblate errors

.github/workflows/deploy-to-prod.yml
I need to deploy to PRO but it turns out I do not have the rights. I am shamelessly using my superpowers to give myself access.
=> 🚚 Add a new user to the list of users who can deploy to pro

content/adventures/en.yaml
Hi, i am using Weblate to translate parts of Hedy to different language. I saw some possible typos in the original English text. And i hope to fix them correctly with my changes. :)
=> 📜 Fix typos in English adventure

content/adventures/en.yaml
When using Weblate, noticed some tailing space characters and possible some missing ones. Tried to remove or add them. 
* Run Hedy locally and check the changed adventure pages
* Copy and run the changed code examples in the programming field
**Checklist**
=> 📜 Add required space chars; remove tailing space chars

.github/workflows/unlock-weblate.yml, .github/workflows/update-weblate.yml
Temporarily disable automatic Weblate updates 
Fixes #6342
=> 🚚 Temporarily disable automatic Weblate updates 

dodo.py
Adds an option to minimize the javascript, thus reducing its size by about 40%: the full file weighs 5.5Mb while the minified one weighs 3.1. This can reduce load time on slow connections.
* Everything should work as normal.
=> 🚚 Minimize javascript
