grammars/level1.txt, grammars/level2.txt, grammars/level3.txt, grammars/level4.txt, grammars/level5.txt, grammars/level6.txt, tests.py
Updated the grammars for level 1 - 6 to support `\r\n` as well as `\n`, and included a test for it.
Fixes #53 (or at least part of it)
=> Add support for \r\n line endings

grammars/level4.txt, grammars/level5.txt, grammars/level6.txt, grammars/level7.txt, hedy.py, tests.py
Updated grammars for levels 4 - 7 to accept both `foo is bar` and `foo in bar` as conditions for the if-statement. In the latter case `bar` should be a list, because generating lists in place is not supported.
Also the implementation of `ifelse` has been moved so it is closer to the implementation of `if`.
This fixes #41, at least partly. I have opted not to implement `or`, because supporting both `and` and `or` should imo also require support for parentheses.
=> Extend support for if statements; allow in list checks

coursedata/level-defaults/en.yaml, templates/layout.html
The 'body' contains preformatted code blocks, rendered like so:
```
<div>{{start_code}}</div>
```
If `start_code` contains newlines (let's say it's
`"first_line\nsecond_line"`), the template will render as follows:
```
<div>first_line
second_line</div>
```
Which is fine, but if the `indent` filter is used to reindent this
block, the final HTML changes to:
```
<div>first_line
second_line</div>
```
Which means the editor will see the following code:
```
first_line
second_line
```
First of all this looks ugly, but in a whitespace-sensitive language
this is even a syntax error.
It is therefore not safe to reindent generated HTML code willy-nilly.
If you want to pretty-print HTML, you should use JavaScript to inject
the startup code into the editor (as the pretty-printer will not touch
a …
=> fix: remove indentation on 'body' block

app.py, static/js/app.js
Currently we use a GET request to submit a program from the client to the server for parsing (`GET /parse`). GET requests are recommended to not exceed 2048 characters, because of limited support for long URLs on some browsers (such as IE11).
By switching to POST, we can sidestep this problem. It is also somewhat more RESTful to use POST rather than GET for this type of operation, since we're in effect submitting data.
This SO answer has further info on this subject: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
=> Use POST /parse instead of GET /parse to submit programs.

CONTRIBUTING.md, hedy.py, runhedy.py
Added functionality to run your hedy files locally. You can install the dependencies using `pip install -r requirements.txt`.
Then use `python3 hedy.py LEVEL PATH_TO_FILE` to launch your file
=> Added functionality to run hedy files locally

hedy.py, tests.py
Rethrow the original parser exception instead of letting the
best-effort second parse exception escape.
Fixes #137.
=> fix: parsing errors get reported at wrong level

static/js/app.js, templates/code-page.html
- Closes #147 and #160.
- Blocks running the code through the button and also through the keyboard shorcut (ALT+ENTER).
- Also puts global variable `unsaved_programs` into `window.State`, our holder for state global variables in the browser.
=> Disable code running when prompt is being shown

auth.py, tests_e2e.py
- Closes #138
- How to add API key: https://us7.admin.mailchimp.com/account/api/
- Specific API call: https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/
=> Add Mailchimp API call to add emails to subscriber list.

app.py, coursedata/texts/fr.yaml
The `/parse` endpoint code used `requested_lang()`, which looks at the
query string in the URL (or the browser language) to determine the
language.
Instead, `/parse` is POSTed to and the language is in the POST body of
that request. It should be read from there.
Fixes #179.
=> fix: `parse` always uses browser language (instead of selected language)

main/start-en.md
- Set English lang query parameter: useful for when browser has a non-English supported language as default and user changes the language to English.
- Closes #206
=> Set English lang query parameter when going to the Hedy editor

CONTRIBUTING.md, app.py
- Closes #210.
- Exit with message.
- Modify docs.
Todo: Test with pyenv that 3.6 is indeed the minimal version required
=> Block Hedy from running in Python < 3.6; update CONTRIBUTING.md

app.py
Fixes PR #213 . Forgot to change the condition after testing locally the error message yielded by requiring Python 4.
=> Python 3 is required, not 4!

.github/workflows/deploy-to-alpha.yml, .github/workflows/unittests.yml
Right now, the "unit test" workflow and the "deploy to alpha" workflow
run in parallel.
This means that the code will get deployed to alpha, even if it doesn't
pass the tests, which is kinda dangerous (on the other hand, it's
alpha so we might not care).
This change links the two workflows together, so that "deploy to alpha"
only runs if the unit tests on master ran successfully.
Feel free to take or close this if you don't care about this!
Two additional notes:
* The tests also run on the PR build, but that's pre-merge and it's not
necessarily guaranteed that the tests will pass after the merge.
* This has no impact on the "deploy to prod" workflow; it's still
very well possible to deploy a `master` to production that doesn't
pass tests. We need to write the workflows slightly …
=> chore: deploy to 'alpha' only if the unit test workflow succeeds

CONFIGURATION.md, app.py
While testing the A/B testing logic, I noticed that sessions in alpha were constantly regenerated - this rendered session_ids useless for tracking purposes, and also performed inconsistent proxying (some requests were proxied to test, other were not).
After extensive debugging, I figured out that this is not because of the A/B testing logic, and that it also happens in prod (beta).
The reason is that currently we have multiple workers in both alpha and beta, but each sets its own `SECRET_KEY`, so the workers don't recognize each other session cookies. So they're constantly re-setting those cookies and the session_id changes constantly. User requests are sent to multiple workers, so this happens all the time.
This PR uses a single secret from the env (if available) as the `SECRET_KEY` so …
=> Use single secret from environment variable for multiple workers

app.py, templates/version-page.html
Generates a GitHub link which shows the changes that are on
`master` that haven't been deployed to the current page yet.
=> feat: add a page showing version and unreleased changes

coursedata/texts/nl.yaml
Traditionally, untitled documents are called "naamloos" in Dutch.
=> fix: "ongetiteld" -> "naamloos"

app.py, courses.py, docs.py, hedy.py, runhedy.py
Specify utf-8 as the default read encoding for files to avoid problems when Windows defaults to another encoding.
Windows doesn't use utf-8 by default: https://dev.to/methane/python-use-utf-8-mode-on-windows-212i
=> Require utf-8 everywhere for reading files

app.py, auth.py
We aren't currenty setting samesite values for cookies, and that would be a good thing to do (https://flask.palletsprojects.com/en/1.1.x/security/).
This commit sets the cookie values for samesite, httponly, and secure in a central place so we don't need to worry about it if we add more cookie values.
=> add central security settings for cookies

coursedata/level-defaults/nl.yaml
The second for-loop in the start code of level 10 was not indented.
=> fix indentation in nested for-loop on level 10

app.py
Do not use security headers on session cookie when running locally, because it disrupts session variables somehow.
@tibiba this fixes the problem you had yesterday.
=> Do not use security headers on session cookie when running locally

CONTRIBUTING.md, app.py, coursedata/adventures/en.yaml, hedy.py
If you run the following code on level 4:
```
people is mom, dad, Emma, Sophie
dishwasher is people at random
if dishwasher is Sophie print ... too bad I have to do the dishes ... else print 'luckily no dishes because' ... 'is already washing up'
```
The following error appears:
> We can't run your program.
>
> 'list' object has no attribute 'find'
This is because the second return value of `IsValid()`,
which is expected to be a string, is all of a sudden
a list of strings. In particular, it's the following list of
strings:
```
['print without quotes', 'print without quotes']
```
This value is passed to `closest_command`, which explodes because
it was expecting a string and not a list, leading to the **list has no
find** error.
Normalize unexpected list back to a string by just taking the …
=> fix: fix uncaught exception on level 4

app.py, hedy.py, hedyweb.py, utils.py
Instead of creating a Lark parser over and over again
every time we go to parse code, cache and reuse the level
parser to get a speed boost.
Reduces parse time from ~60ms to ~10ms (not the best but still helpful!)
=> refactor: cache Lark parsers

app.py, hedy.py, hedyweb.py, utils.py
Instead of creating a Lark parser over and over again
every time we go to parse code, cache and reuse the level
parser to get a speed boost.
Reduces parse time from ~60ms to ~10ms (not the best but still helpful!)
------
Re-submission of #381, removing the dependence on an implicit Flask context to obtain the debugging configuration: just pass the `app` object we have.
=> refactor: cache Lark parsers, take 2

app.py, hedy.py, templates/auth.html, templates/code-page.html, templates/incl-adventure-tabs.html, templates/incl-menubar.html, templates/layout.html, templates/programs.html, templates/translate-fromto.html, tests/test_utils.py, utils.py
From now on, all static assets referenced via:
```
{{static('images/bla.png')}}
```
Will be automatically cached via CloudFront CDN. CloudFront
has been configured externally to cache hedycode.com.
We use a commit-based URL to make sure that CloudFront can cache
aggresively, because we can always accurately invalidate the URL.
=> feat: add CDN for static assets

auth.py
Well, this is embarassing.
Ever since implementing auth & users, I forgot to set the `max-age` or the `expires` property on all user cookies. As a result, all our cookies have been session cookies, which means that whenever all the tabs of the browser are closed, the cookie is lost.
Not only this created the need for unnecessarily logging in multiple times for users, it also created performance issues to our server because it had to handle more logins than it should!
Anyway, here goes the fix.
=> Set max-age on cookies 

app.py, auth.py, aws_helpers.py, config.py, flask_helpers.py, hedyweb.py, querylog.py, utils.py
This introduces structured request logging, with a way to log
counters, arbitrary values, and timers within each request.
Scopes are automatically opened and closed matching Flask requests,
by using `@app.before_request` and `@app.teardown_request`.
Currently annotates a number of functions such as `db_get()`,
`render_template()`, etc etc with `@querylog.timed` which automatically
records the time taken inside those functions, and how often they are
called. Some counters and values are recorded manually with
`log_counter` and `log_value`.
I'd recommend everyone log as many things as they can that may impact
performance or stability of the app, to help with ease of debugging
later on.
The mechanism to add a log sink are in place, but I'm not sure what
the current preferred log target is (I …
=> feat: add 'query logging', structured logging per request

static/js/translating.js, templates/translate-fromto.html, translating.py
Two mistakes:
- A bug in `apply_change` led to a 500 error
- All elements were transmitted (even the ones not entered), and so a
lot of empty untranslated fields might be added at the end.
=> fix: translating to Hungarian doesn't work

main/for-teachers-en.md
This fixes some typos in https://github.com/Felienne/hedy/blob/master/main/for-teachers-en.md, mainly typographic quotation marks in code, i.e. `’` are now `'`. There still are typographic quotation marks in non-code.
=> fix typos in main/for-teachers-en.md

templates/code-page.html
I was improperly escaping json or strings passed by Python to js via jinja. This broke the js on many levels, depending on the contents of programs. The bug was introduced in https://github.com/Felienne/hedy/pull/372 . Luckily it didn't reach `prod`.
=> Fix improper escapes when passing program data to js via jinja.

main/for-teachers-de.md, main/menu.json
This translates missing, or rather English, menu items to German.
=> translate missing menu items to German

auth.py
When logging in a just signed up user, if the timing was very slow, we would overwrite most of the fields of a freshly created user with just `username` and `last_login`. This happened twice.
The fix also reduces an unnecessary call to DynamoDB.
=> Fix timing issue with signups

app.py
This fixes a weakening of the URL validation that was of my authorship while merging #412 
`/hedy/8foo` would throw a 500 error, now it will return a 404.
=> If the level is invalid, return 404 instead of throwing a 500

app.py
The `@app.errorhandler()` is a normal view function, and must also
indicate the error code when returning a failure. Without an error
code, it would return a `200 SUCCESS` response, which is not
appropriate.
Make it explicitly return a `500` code instead.
Fixes #465.
=> fix: return "Internal Server Error" with 500-code

static/js/tabs.js
Fix loading of program belonging to a level that is not the latest program for that level.
- Fixes a bug that overrode the loaded program for a logged in user if 1) the program belonged to a level and not an adventure; 2) the program was not the latest saved program for that level. In this case, the latest program for the level saved by the user was loaded instead.
- Closes #452
=> Fix loading of program belonging to a level

app.py
We want some basic security headers, and instead of adding a new dependency on something like talisman, we decided the easiest update would be to add them directly to the response.
- The strict transport header will tell the browser that on every request after the first, it should auto-upgrade to https without needing to first connect to our server to receive an explicit redirect. The setting in this commit is for 1 year, and although we don't have any subdomains at the moment, there isn't any reason not to include subdomains.
- The X-Frame deny keeps other sites from spoofing ours by loading it inside an iframe, which is probably not very likely as an attack vector, but no reason not to implement this.
- The XSS-Protection isn't used by a lot of the more modern browsers, but gives us a …
=> add security headers to response

static/js/app.js
The final implementation of the Gradual Feedback Model containing a small fix where a `KeyError` would occur due to a missing variable being passed when using a POST request on the logger.
=> Final implementation of the Gradual Feedback Model

website/querylog.py
As reported by @omedtjeee .
- Avoid using the resource module on querylog.py on Windows to maintain Windows compatibility.
- The solution loses some functionality for Windows, but it should still do most of the logging. Non-windows functionality is untouched.
@rix0rrr do you think it is worth it to explore a Windows supported alternative to `resource`?
=> Avoid using the resource module on querylog.py if using Windows

app.py, tools/download-programs, website/auth.py
About 30% of the total request volume to the server is to retrieve
static error messages to use in the JavaScript (`/error_messages.js` and
`/auth/texts`). Because they are not cached, they are currently loaded
upon every page load (every time a user hits **Next level**).
They could *easily* be cached though, bringing down the total request
volume to the server by a lot.
Add a caching header to make the browser cache these responses for an
hour; we could think about routing them through the CDN as well,
but that's perhaps a bit much for now. Let's just see how this performs.
=> fix: add caching on static content

app.py
#497 introduced a bug where we add 1 to the program count of users even though they may be overwriting an existing program.
This PR fixes that. It also simplifies the logic by merely using the length of the programs already retrieved for the user.
If the count is wrong for a user, it should be fixed the next time the user creates a program.
=> Fix program count for users

app.py, website/querylog.py
Currently, `/space_eu/1%3Flang=en` and `/hedy/1?lang=en?lang=en` trigger 500s. This code fixes both classes of malformed URLs by adding validations.
=> Add validations to prevent 500s with malformed URLs

static/js/app.js
We removed this as a quickfix because we had issues in level 10 a while back, is fixed now!
=> puts back a newline at the end of palette code

app.py, gunicorn.conf.py
On Heroku, we don't use the `if __name__ == '__main__':` block to
initialize our application, but instead run the server through
`gunicorn`.
The new `db_init()` function introduced in #537, that is required to be
called at the start of the process, was not called when loaded via
gunicorn.
Add a new hook to properly call initialization routines in both
scenarios.
=> fix(heroku): new `db_init` method not called on Heroku

website/log_queue.py
`print_exc()` doesn't take arguments: it implicitly already prints
the most recent exception.
The fact that we called this function incorrectly meant an exception
was thrown during exception handling.
=> fix(logging): double exception in log handler

website/aws_helpers.py
The 'boto3.client' method is not thread safe: https://github.com/boto/boto3/issues/1592
Put a lock around initializing an S3 client, so the two threads that
might do this in parallel don't stomp on each other.
=> fix(logging): race condition in S3 logging

static/js/app.js
The `getVoices()` array is populated lazily at *some point* after
page load. On Safari it usually goes quickly, but Chrome or Edge
are much slower.
Keep on trying for a bit after page load to see if the `getVoices()`
array gets populated.
=> fix: fix voice detection on slow browsers

website/querylog.py
In the query log, the resource consumption entries are logged as
`user_ms: [15]` instead of `user_ms: 15` because of a trailing `,`
which makes the values tuples.
=> fix: user_ms and sys_ms are logged as lists

app.py, website/cdn.py
Because `app.js` is loaded from the CDN in prod, if there's an error in
the script the browser hides the details of the error for security
reasons (different domain = you don't get to see the details).
Add a cross-origin header so the browser will treat the external
resources as safe.
=> fix: script errors aren't reported properly in prod

templates/code-page.html
Syntax highlighting was broken because JavaScript files were being
loaded in the wrong order.
=> fix: unbreak syntax highlighting

static/js/app.js, templates/view-program-page.html
`window.State.lang` could be `undefined` (in non-code page where
`app.js` is still loaded), probably `view-program-page`.
Make sure the vars are set but also write the code a bit more
defensively.
=> fix: fix syntax highlighting and speech on share program page

static/js/syntaxModesRules.js
The regexes in the tokenizer will only ever see one line at a time,
without the closing `\n`. As soon as all characters in a line have
been consumed, the tokenizer moves to the next line, remembering
the current state.
This means that consuming 0 characters at the end of line to move
back to the start state is not possible.
Instead, we take advantage of the ability of the tokenizer to capture
multiple groups (characters between `(...)` in the regex) and assign all
of them token classes at once by specifying them in arrays. This allows
us to finish regexes with `(.*)` to consume anything till the end of the
line (if present), so we know that we can move back to the `start` state
after having done so.
=> fix: level 3 syntax highlighting

static/js/app.js
Very relevant information on how to produce a client error
is missing: the page the error occurred on.
Add that in.
=> chore: client exceptions don't contain source page

static/js/syntaxModesRules.js
We recently had 500s, caused by this client error:
```
Uncaught Error: state doesn't exist
```
This is an error thrown by the Ace editor if the syntax
highlighting rules reference a `next` state that doesn't exist.
The state `expression` doesn't exist anymore, but was still referenced.
These days, we recognize most expressions simply from the `start` state.
Remove the invalid references to a state that doesn't exist anymore.
=> fix(highlight): remove invalid states

app.py, coursedata/adventures/en.yaml, static/js/app.js, templates/auth.html, templates/client_messages.js, templates/code-page.html, templates/error_messages.js, templates/view-program-page.html
For ever example we find in the content of tabs, add a button
to it to quickly copy the code into the editor.
Also in this commit: renamed `error_messages.js` to
`client_messages.js`, since sometimes we need UI translations in the
JavaScript as well, and it's a better name.
=> feat: "try example" button on examples

static/js/tabs.js, templates/incl-adventure-tabs.html
Especially when testing, it's very annoying when a page refresh forgets
what tab you were on.
Use the browser `replaceState` API to change the current URL to include
the tab in a `#hash_fragment`, and automatically switch to that tab when
the page is loaded.
=> feat(tabs): remember selected tab upon refresh

requirements.txt
Lark is published both to PyPI under the name `lark` as well as
`lark-parser`. They seem to be the same, so let's just depend
on the version that the docs say we should install.
=> chore: remove duplicate dependency on Lark in requirements.txt

static/js/tabs.js
Made a mistake an in a previous PR's refactor, left
an uninitialized variable in place.
=> fix: ReferenceError: adventureName is not defined

e2e_tests.py, website/dynamo.py
While investigating #613 , it emerged that the `del_many` would throw an error when running on Dynamo (but not when running with the local DB) because of a call to `db.query`. Said call used the `Key` parameter which doesn't seem to be accepted by Dynamo itself.
This fixes `db.query` and, as a consequence, also `del_many`. It is indirectly tested by deleting a user with a program in the E2E tests.
I'm not sure whether the approach I used here is correct. It does work, but it may restrict the generic-ness of the method. @rix0rrr please let me know what you think.
Closes #613
=> Fix for `query` method in Dynamo

coursedata/adventures/en.yaml
I'm getting an error message when running the randomness example from "Story" in Level 2. It says `name 'animal' is not defined`. This seems to be caused by the variable being called `animals` (plural) and being referenced as `animal` (singular). This PR fixes that.
**Sidenote:** I wasn't really sure whether the variable creation should be changed or the reference. The reference as it was looked good because it made the sourcecode read like proper English. But I went with changing the reference to make it match the source for Level 3.
=> Fix typo causing program failure

main/for-teachers-nl.md
I fixed some typos, changed the subheadings under 'algemene lesopbouw', and removed the old info from level 2 so now only the frequently made mistakes are left.
=> Fixed typos, subheadings, removed old info

static/js/app.js, static/js/tabs.js, templates/code-page.html
Fixing the following 2 errors from the log:
**Uncaught TypeError: Cannot read properties of undefined (reading 'loaded_program')**
This happens in:
```js
if (adventures[tabName].loaded_program)
```
If `adventures[tabName]` happens to be undefined.
**SyntaxError: Unexpected token '.'**
This happens on:
```js
window.history?.replaceState(...);
```
Likely the user's browser doesn't understand the `?.` syntax yet, using
an old browser: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
To detect this in the future, log the userAgent.
=> fix: fixing 2 JavaScript errors in `tabs.js`

coursedata/texts/nl.yaml, grammars/level3-Additions.lark, grammars/level6-Additions.lark, hedy.py, tests/tests_level_03.py, tests/tests_level_04.py, tests/tests_level_06.py
Closes #698, also addresses #597 partially: in Dutch and up to level 5 only for now. For En and other langs we need to expand the error message.
=> Updates grammar for better error messages

website/querylog.py
Log memory usage so that we have something to go on when we go to
investigate memory failures.
=> chore: log memory usage

tests/test_utils.py
The pickle test that loads `hu.yaml` compares it to loading
`hu.yaml.pickle`; if there was a `.pickle` file remaining on
disk, it may have different contents than the `.yaml` file.
This will not happen on the server since it gets a clean redeploy
every time, but it may happen on dev machines.
=> fix: load_yaml_pickle test fails if a pickled file is on disk

hedy.py
When I ran this code in level 2:
`ask Wat is je lievelingskleur?`
I got the error message:
`That was correct Hedy code, but not at the right level. You wrote code for level 2 at level 1.`
The message should be:
`That was correct Hedy code, but not at the right level. You wrote code for level 1 at level 2.`
The proposed change should fix that.
=> fix error message for code in wrong level

hedy.py, tests/tests_level_16.py, tests/tests_level_17.py, tests/tests_level_18.py, tests/tests_level_19.py, tests/tests_level_20.py, tests/tests_level_21.py, tests/tests_level_22.py
When we compare strings, python uses lexographic ordering and thus `'3' < '12'` returns false.
This PR fixes #788
=> Ensure comparison is working on numbers

grammars/level1.lark, grammars/level11-Additions.lark, grammars/level14-Additions.lark, grammars/level17-Additions.lark, grammars/level19-Additions.lark, grammars/level2-Additions.lark, grammars/level7-Additions.lark, grammars/level8-1-Additions.lark, grammars/level8-Additions.lark, grammars/level9-Additions.lark
This reduces the risk of a typo in the string contents, makes it easier to rename the symbols (eg translation) and centralizes token definitions a bit.
I also made the grammar more lenient with regards to multiple spaces where previously at most a single space was expected. This eliminates the existence of an error that is not existing in conventional programming languages either, thus avoiding the need for any program repair for them.
=> Move all string literals in the parsers to level1.lark

coursedata/texts/cs.yaml, coursedata/texts/de.yaml, coursedata/texts/el.yaml, coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/hu.yaml, coursedata/texts/it.yaml, coursedata/texts/nl.yaml, coursedata/texts/pt_br.yaml, coursedata/texts/pt_pt.yaml, coursedata/texts/sw.yaml, coursedata/texts/zh.yaml, hedy.py
`original_level` was used to indicate the level for which the code does work, while `working_level` was used for the current level.
Maybe `original_level` should be renamed to `current_level` or something like that to reduce confusion?
=> Fix a mixup between original_level and working_level

grammars/level12-Additions.lark, grammars/level4-Additions.lark, tests/tests_level_04.py, tests/tests_level_12.py
Split out of https://github.com/Felienne/hedy/pull/834.
Level 4 up to level 12 already allowed this, but from level 12 onwards only a single space was allowed previously.
=> Allow multiple spaces inside lists

app.py, coursedata/texts/en.yaml, coursedata/texts/nl.yaml, grammars/level1.lark, hedy.py, tests/tests_level_01.py
The empty program check is now moved to IsValid and will handle programs consisting entirely of newlines without crashing.
Programs consisting entirely of spaces do still give a parse error, but unlike newline only programs previously they don't crash Hedy.
Fixes https://github.com/Felienne/hedy/issues/833
=> Allow empty programs in the grammar

static/js/syntaxModesRules.js
The `is` inside identifiers get incorrectly detected inside variable
names. Make sure to only highlight keywords that are complete words.
Fix #872.
=> fix: syntax highlighting inside 'if' broken

hedy.py
This change fixes a bug for string printing in lvl 13. Even when you tried to print a quoted string, it would still be treated as a variable (if there was a variable with the same name as the string).
**Fix for**
#1126 
Go to lvl 13 and run the following code:
```
fruit is ['banaan', 'appel', 'kers']
eerstefruit is fruit[1]
print('eerstefruit') # should print eersterfruit
```
and then run the next one:
```
fruit is ['banaan', 'appel', 'kers']
eerstefruit is fruit[1]
print(eerstefruit) # should print banaan
```
**Checklist**
=> Fixes string printing for lvl 13

app.py
- Closes #993 
**How to test**:
- Go to http://localhost:5000/hedy/29
- See that the app shows a 404 page with the error "No such Hedy level!".
- Note that the app doesn't crash anymore when that page is requested.
=> Show 404 page when requesting a level that does not exist

app.py, tools/download-logs
We used to be only logging the path in the query log (`/hedy/8`),
but the language is pretty relevant and that is passed in the query
string (`/hedy/8?lang=fr`).
Log the query string as well if passed.
Also add an example query to the download script so I don't have to
look up how to do this every time :).
=> chore: log query string in querylog

hedy.py, tests/test_level_08.py
This PR changes `preprocess_blocks` to ignore empty lines (with or without whitespace). 
Ignores whitespace-only lines accepting more programs as valid.
**Fix for**
Fixes #1197
* Go to level 8
* Paste this code taken from #1197 (make sure to preserve the whitespace in line 4):
```
food is ask 'What do you want?'
if food is 'pizza'
print 'nice!'
else
print 'pizza is better'
```
* Check that no error is raised and an ask modal is displayed
=> Ignore empty lines

app.py
The `nl2br` filter was not working correctly: we need to tell it
that the `<br>` we're inserting is safe and does not need to be
escaped anymore.
In order to be able to do that, we have to also escape potentially
unescaped incoming text.
Fixes #887
=> fix(quiz): newlines show as "<br>" in the quiz

coursedata/adventures/nl.yaml
Dutch text for Vooruitblik at level 9 says level 8 is next, instead of 10.
This PR (accidentally) also removes superfluous spaces. I can separate those changes if desired. The only content change is in line 1867
=> fix number of next level in Vooruitblik bij level 9

tests/test_level_01.py, tests/test_level_09.py
We have added some tests for the parsing of Dutch keywords. Two tests for the print keyword and one for a for-loop (just a safety-check to see if that also works). Parsing other keywords in Dutch should also be right "by construction".
This should resolve issue #1212
=> Adding tests for parsing dutch keyword

coursedata/texts/nl.yaml, hedy.py
**Fix:** Whenever you start a block with 0 spaces, part the error message that occurs in level 7 is: "You used too few spaces in line 2. You used 0 spaces, which is not enough. Start every new block with None spaces more than the line before". 'None'  is changed to '4' to make the sentence grammatically correct. This is also the indent size you learn in level 7. 
**Small discussion:** It is still possible to start a block with more than 0 spaces, but different than 4. For example: whenever you start a block with 3 spaces, every block should start with exactly 3 spaces. There are two changes possible:
1. The text at the top of level 7 should be changed to "start every block with the same number of spaces"
2. The error message should be changed to "Oops! You used 3 spaces instead of 4".
=> #930 Block should start with 4 spaces instead of None

app.py, hedyweb.py, main/start-cs.md, main/start-de.md, main/start-el.md, main/start-id.md, main/start-sw.md, main/start-zh.md, templates/auth.html, templates/code-page.html, templates/incl-editor-and-output.html, templates/level-page.html, templates/login.html, templates/programs.html, templates/view-program-page.html, website/auth.py, website/teacher.py
The "language" parameter should just be a global, automatically
available in every request and template. No need to set and pass
it in every Python handler and every call to `render_template()`
anymore.
Relates to #1179.
=> chore: remove unnecessary `lang` parameters

hedy.py, tests/test_level_01.py
Fixes issue #1258. Since #898 `echo` has incorrect behavior since there is no more space after it. This change fixes this issue by adding a space before the answer. This change also has updated the unit tests for echo to reflect this change
**Fix for**
Fixes  issue #1258
Passes all current unit tests (`$ python -m pytest tests/*.py`):
Sample test behavior on local server:
1. Go to localhost:5000 and click on Hedy
2. Go to level 1, and input the follow text (or any text that involves echo with other statements)
3. Observe intended behavior
**Checklist**
=> Added space after echo and updated unit tests to reflect change

templates/quiz_question.html
The radio button is moved under the option symbol. This makes more space for the option text and eliminates an problem where the radiobutton resizes
The radio button  has been swapped with the option symbol. The tailwind CSS is adjusted with flex-col and justify-center, items-center tags.
**Fix for**
Radio button size changes in Q6 quiz level 7 #1075
Is changed to this, with radiobuttons moved to underneath the option symbol.
=> Radio button size changes in Q6 quiz level 7

doc/CONFIGURATION.md, website/auth.py, website/database.py, website/dynamo.py
Currently, we are using service-specific AWS user keys. What does that
mean?
There is one AWS user who can has full admin access to DynamoDB, and
this user is used by both the alpha as well as the production
environment.
There is a separate AWS user who has full admin access to SES, and this
user is also used by both the alpha as well as the production
environment.
There are multiple things wrong with this setup:
- There are different keys per service we want to use, which is
unnecessarily annoying to configure.
- The keys have unnecessarily broad permissions.
- The keys are not scoped to a single (alpha or prod) environment,
and importantly scoped to the resources that that environment
needs to access.
I've rectified the configuration in AWS itself. The current PR switches
over to just …
=> chore: remove AWS god keys

website/dynamo.py
Right now the in-memory database returns references to
objects that are stored in it, allowing you to corrupt the
contents out-of-band.
Instead, it should be handing out copies of those objects.
=> chore: in-memory database returns object references

tests/test_dynamo.py, website/dynamo.py
It is now possible to use range conditions on sort keys. Only
the `Between` condition has been implemented so far, but it should
be easy enough to implement others as well if necessary.
A `Between` query is used like this:
```py
records = table.get_many({
'id': 'bfdfea7bba174650b6d08d78d40be7ef',
'level': dynamo.Between(3, 5)
})
```
=> feat: dynamo layer supports 'Between' queries

grammars/keywords-en.lark, hedy.py, hedy_translation.py, tests/test_level_01.py, tests/test_level_10.py, tests/test_translation_level_01.py
Added structure for translation of level 1 to Hedy.py, issue #1338 .
Adds a way to translate code from one language to another with a transformer.
Works if the keyword lark file is available for the chosen language and if the "local_keywords_enabled" is set to True.
Adds a "keywords_to_dict" helper function to make a dictionary out of a Lark file.
Does not currently do anything on the Hedy site, only when tests are run.
Adds a test file for the translation of level 1.
Removed one empty line from "keywords-en.lark".
Tests can later be added to the "test_level_01" file, but have but separated initially for ease of use.
Same for the Transformers, which could be put in a new python file.
It is maybe too much for a single pull request bit it seemed better to me if the main functionalities were …
=> Translation structure level 1 setup

grammars/level2-Additions.lark, grammars/level3-Additions.lark, grammars/level4-Additions.lark, grammars/level6-Additions.lark, hedy.py, tests/test_level_04.py, tests/test_level_05.py, tests/test_level_06.py, tests/test_level_08.py, tests/test_level_09.py, tests/test_level_11.py, tests/test_level_12.py, tests/test_level_13.py, tests/test_level_14.py, tests/test_level_15.py, tests/test_level_16.py, tests/test_level_17.py, tests/test_level_18.py
- Change ask command to have the grammar as print after level 6
- Refactor ask command to use f-strings in transpiler
- Fix python concatenation error of ask argument at level 12
**Fix for**
#1351
- Review the changes in the grammar
- At level 12, the following snippet should not cause python error:
```
a is 10
answer is ask 'is your number ' a
```
**Checklist**
=> Change ask command to have the grammar as print after level 6 #1351

app.py, coursedata/texts/en.yaml, coursedata/texts/nl.yaml, templates/programs.html, templates/view-program-page.html
Currently students are able to submit programs and through that process "freezing" the program. However, when sharing the program the program-view page was identical for submitted and non-submitted programs. Giving the teacher no information if the shared program was indeed submitted by the student and therefore not altered later on. In this PR we return additional information on the program-view page if the program is submitted. Returning an additional header with the notification of looking at a submitted program as well as the last-edited timestamp.
**Fix for**
No specific issue, just a forgotten feature of #1374 
View a submitted and a non-submitted program through a shared link and notice the UI difference.
**Checklist**
If you're unsure about any of …
=> [UI] Show submitted program status on program-view page

hedy.py, program_repair.py, tests/test_level_04.py
Adds line and column to the dataclass `InvalidInfo` for invalid nodes. They are not being used yet in this PR, but they will be crucial for [program_repair.py](https://github.com/Felienne/hedy/blob/main/program_repair.py).
Also removes the unnecessary conversion from (line, column) to an index in [program_repair.py](https://github.com/Felienne/hedy/blob/main/program_repair.py) (from #1339).
**Fix for**
Progress for #1225.
`invalid_info` in `is_program_valid` has attributes `line` and `column`, you can view it in debug mode or print it to the terminal (Lark starts counting at 1).
=> More information to InvalidInfo

app.py, website/auth.py
The Hedy code base was operating in a split-brain scenario:
* Some code would inspect the session to find the currently logged
in user. Sessions get cleared when the browser is closed.
* Some code would look at the long-lived login cookie and perform
database lookups on every request to figure out what the currently
logged-in user is.
The user was purposely stored in the session to save database calls
on every request, but if you close and reopen the browser the two
code paths would disagree:
- According to the session, you are now logged out.
- According to the login cookie, you are still logged in.
This PR unifies the behavior. The new behavior is as follows:
- All code will look at the session to determine whether you are logged
in or not.
- The session would be cleared when you close …
=> fix: automatically log users in from long-lived cookies

hedy_translation.py, tests/test_translation_level_06.py, tests/test_translation_level_07.py
Added level 6 and 7 into the translation structure.
-Adds level 6 and 7 to the translation structure.
-Adds tests for translation of levels 6 and 7.
-Adds support for the operators available in level 6.
-Adds support for the 'repeat' and 'times' keywords
Tests available by running the tests
=> Translation levels 6 and 7

exceptions.py, hedy.py, program_repair.py, tests/test_level_04.py
Repairs `UnexpectedCharacters` exceptions by removing that character.
**Fix for**
Progress for #1225, point 3.
For example, on level 4 or higher run the following Hedy code:
`print ,'Hello'`
`fixed_code` will have the `,` removed,  remaining `print 'Hello'`. It is still possible that other errors arise after the repair.
=> Repair for UnexpectedCharacters exceptions

exceptions.py, hedy.py, program_repair.py, tests/Tester.py, tests/test_level_01.py, tests/test_level_02.py, tests/test_level_08.py
For the indentation exceptions (`IndentationException` and `NoIndentationException`), the necessary information to repair the errors were already available in Hedy. With those information, `leading_spaces` and `indent_size`, the error can easily be fixed with some simple math.
`fix_indent` first checks whether the error line has more or less indentations than the intended amount, then deletes or inserts accordingly.
**Fix for**
Progress for #1225.
I added 2 tests for these repairs in level 8:
`test_repair_too_few_indents` tests if the correct amount of indentations are added.
`test_repair_too_many_indents` tests if the correct amount of indentations are deleted.
=> Repairs for too many/few indentations exception

hedy.py, tests/test_level_14.py, tests/test_level_17.py
Fix bug with string literals support in != comparisons
**Fix for**
Fixes #1550
- Tests are added to cover the bug
**Checklist**
=> Fix bug with string literals support in != comparisons #1550

hedy.py, tests/test_level_02.py
Hashes variables used in the `turn` command
**Fix for**
This:
This code now works at level 2:
```
ángulo is 90
girar ángulo
```
=> Hashes variable inside turn command

coursedata/pages/start/en.yaml
In this PR we correctly translate the titles for the main page in English.
**Fix for**
This PR fixed #1568.
Run and navigate to the main page. Notice that the titles and subtitles are now correctly displayed in English.
**Checklist**
=> [BUG FIX] Correctly translated subtitles to English for main page

grammars/level12-Additions.lark, grammars/level16-Additions.lark, grammars/level6-Additions.lark, hedy.py, hedy_translation.py, tests/Tester.py, tests/test_translation_level_06.py
As stated on issue #1579 translation code does not preserve = and `is` converting everything to =. To solve this I split the following rules into 2 rules, one for is, and one for = from level 6 on:
* `ask` 
* `list_access` 
*  `assign` 
* `assign_list`
**Fix for**
Fixes #1579 
The transpiler to Python should behave the same, but translating to English should handle correctly `is` and =. I added a few tests on `tests\test_translation_level_06.py` to test this behavior. 
**Checklist**
=> Split assigment rules from level 6 on

hedy.py
Remove TODOs from hedy.py
Remove "# TODO: list_access, list_access_var and repeat_list types can be inferred but for now use 'any'" because it does not add any useful information to the implementation.
Transformed "# TODO: we should not just take the first match, take into account var reassignment" into https://github.com/Felienne/hedy/issues/1631 
Addresses #1632
=> Transform TODO statements into github issues #1632

app.py, website/achievements.py
Currently we use a global variable `achievements` to store the user progress and achievements. However, when multiple users are logged in at the same time they share this variable as well as the values. Resulting in the undesirable behavior that users where unable to achieve achievements (because another user already got them) or they received random pop-ups of other users their achievements. As pointed out by @rix0rrr we can solve this by storing all user-related data in a session.
In this PR the achievements implementation is re-written to store all user-related data in a session and compare the achievements against this data. Resulting in users no longer interfering with each other.
Use Hedy with multiple users at the same time and notice that they no …
=> [BUG FIX] Achievements related data is stored in session

templates/quiz_question.html
In this PR we perform a clean-up of the quiz question code. Some redundant html code is removed, a small bug were the wrong answers would be indented is solved and the whole answer box is set as clickable to select an answer. This way the quiz is more user-friendly for table and phone users. In the future I would like to remove the radio button all together and use the answer box itself with changing border colors as an indicator of the select answer. However, for know this is an easy and functional improvement.
**Fix for**
This PR fixes #1648.
When answering a question in the quiz, notice that now you're able to click the whole answer box to select an answer instead of only being able to click the radio button.
=> [IMPROVEMENT] Changed clickable area of quiz answer to whole answer box

website/database.py
Currently we return all public programs to the user when visiting the `explore` page. This is undesirable as this amount will increase resulting in a very slow webpage. In this PR we implement a quick fix to limit this amount to `50` programs. This is only a temporary fix, the goal is to implement `Public` as a partition key on the db to enable us to use the new `filter()` function to retrieve the desired amount of programs.
**Fix for**
This has no related issue, just a (very) quick fix to prevent webpages from crashing
Navigate to the explore page and notice that the amount of shown programs is limited to 50.
=> [FIX] limits shown programs on explore page

templates/translate-fromto.html
Describe your changes in detail. Please use present tense without a subject to describe your PR, for example: "Fix**es** issue 123" or "Adds translations of levels 1 to 12 for Polish"
**Fix for**
Link in https://www.hedycode.com/translate/en/de to the Github repository currently does not work due to a double quote being inserted. It links to https://github.com/Felienne/hedy/%22 instead of https://github.com/Felienne/hedy/
**Checklist**
=> fix link syntax for the github repo

coursedata/pages/pages.json, templates/class-overview.html, website/statistics.py, website/teacher.py
Currently the class statistics page has no corresponding page title and no set current page. In this PR we fix both by adding them to the `render_template` as well as adding the correct title to `pages.json`.
**Fix for**
This PR fixes #1782.
Navigate to the class statistics and notice there is now a correct page title.
=> [BUG FIX] Adds missing stats page title

coursedata/texts/el.yaml, coursedata/texts/en.yaml, coursedata/texts/es.yaml, coursedata/texts/fr.yaml, coursedata/texts/it.yaml, coursedata/texts/sw.yaml, coursedata/texts/zh.yaml
spell "meantime" as one word without space.
replaces "mean time" by "meantime" in an error message and its (untranslated) translations
**Checklist**
- Is that required? I didn't see anything about that in the [contributing guidelines](https://github.com/Felienne/hedy/blob/025068018d0bdfea0ddcd16962e8ef3a4fcba36b/CONTRIBUTING.md).
- (though I'm not sure how useful its content is)
=> spell "meantime" as one word without space

app.py, templates/stats-shared.html, website/statistics.py
- Fix styling of the select element in log search form in Safari 
- Fix bug with log searching of empty classes
**Fix for**
#1773 
Locally:
- Log in as admin and go to /admin/stats page. Check that the log search form contains an input(text) for the username and that it is styled correctly in Safari
- Log in as a teacher and go to the /stats/class/$class_id page. Check that the log search form contains a select element that lets you select only the students from the current class. Check that the select is correctly styled in Safari.
On alpha:
- Check that the log search form does not yield errors when the class is empty. Ensure no data is returned.
=> Log Search from fixes #1773

coursedata/level-defaults/en.yaml
fixes #1825
Fixes Issue #1825 for English by replacing the contraction "what's" by spelled out "what is", so that the quoting character `'` doesn't occur in the string.
**Fix for**
#1825
In both affected sections of [level 5](https://www.hedycode.com/hedy/5), on the first tab ("Level 5"):
- Example Hedy Code
- Tip
respectively, do the following:
1. click the "Try" button (⇥) to copy the example code there into the code area
2. click the green "Run code" button below the code area
3. check whether the program has printed anything to the output area (it shouldn't have)
4. check whether the program asks `what is your name?` in the output area, with an input field for entering the name
**Checklist**
If you're unsure about any of these, don't hesitate to ask. …
=> fix quoting in example code in level 5

coursedata/pages/learn-more/cs.yaml, coursedata/pages/learn-more/de.yaml, coursedata/pages/learn-more/en.yaml, coursedata/pages/learn-more/es.yaml, coursedata/pages/learn-more/fr.yaml, coursedata/pages/learn-more/id.yaml, coursedata/pages/learn-more/nl.yaml, coursedata/pages/learn-more/pt_br.yaml, coursedata/pages/learn-more/zh.yaml
fixes #1846 
Changes (for all languages, where this occurs) the destination URL of the "Let us know on GitHub" link in the "Found a bug?" section of the Hedy website from https://github.com/Felienne/hedy/issues/new to https://github.com/Felienne/hedy/issues/new/choose, so that reporters can choose the type of issue they want to file and get the issue content pre-filled with the appropriate template.
**Fix for**
#1846 
1. On the Hedy website, click "Learn more" in the top navigation.
2. Click the "Let us know on GitHub" link in the "Found a bug?" section.
3. Check that you get a selection of issue types to choose from.
**Checklist**
=> let bug reporters choose issue type

templates/admin-users.html
In this PR we re-implement an accidentally deleted e-mail changing function on the admin page. We also fix a bug where the programs page re-direct from the admin table was incorrect.
**Fix for**
No issue created
Navigate to admin page, verify that the mail column values are clickable, resulting in a pop-up to change the mail address of a user. Verify that this is indeed working.
=> [FIX] Re-implements e-mail changing support from admin page

app.py
All our usernames are stored using lowercase letters. When navigating to a public profile using uppercase letters this results in an error (as the username doesn't exist). We thought to have handled this using the `lower()` function, but the implementation was wrong. WE fix this in this PR.
**Fix for**
No related issue
Make sure you are logged in a navigate to a public profile, notice that it still works when replacing some letters with their uppercase letter.
=> [BUG FIX] Public profiles also work with uppercase letters

coursedata/README.md, utils.py, website/cdn.py
Replaces the spellings "MarkDown" and "markdown" with "Markdown" in documentation and in code comments. (Excluding occurrences in comments of `build-tools/heroku/tailwind/styles.css`, as that seems to be part of a "vendored" 3rd-party dependency.)
**Fix for**
(no issue filed)
(shouldn't require any testing, I hope)
**Checklist**
- (well, kind off … )
=> spell "Markdown" without CamelCase and with capital first letter

tsconfig.json
To make the following import work:
```ts
import DOMPurify from 'dompurify';
```
The `esModuleInterop` feature needs to be enabled in TypeScript.
Don't ask me why, I don't understand it either.
=> chore: make "dompurify" import work

website/dynamo.py
Fix Dynamo issue which results in errors when either customizing a class or retrieving customizations for a class.
=> [BUG FIX] Replace iterkeys() with keys()

templates/incl-editor-and-output.html
It seems #1864 introduced an issue where levels would be closed for users not in classes since the next level would not be in their levels since that list would be empty. I think this fixes it but I would need confirmation from @TiBiBa (and I need to test a bit more)
=> Check if there are customizations for this user

License.txt
Re-formats `License.txt` and removes some gratuitous opening quotation marks in it by replacing the file with the plaintext English one available at https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12 as "EN" "TXT-80": [`EUPL-1.2 EN.txt`](https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/2020-03/EUPL-1.2%20EN.txt). Except for those quotation marks (which didn't belong there) and the title/header section (which is being slightly re-arranged by this change), this doesn't change the textual or semantic content of the license, as can be checked by `git show --word-diff faf87fe91603466e956292af5a896debc53c7421`: Only the line breaks are placed differently within the prose (i.e., the text has been re-flown w.r.t. our previous version) and ASCII's …
=> reformat license & remove gratuitous quotation marks

coursedata/level-defaults/de.yaml
- Fixes the grammar in the German Level 4 intro text.
- Brings the German Level 4 intro closer in meaning to the current English Level 4 intro.
**Fix for**
(none filed)
1. Set Hedy to German (with the top right language chooser when not logged in or in your profile settings when logged in)
2. Read first tab of [Level 4](https://www.hedycode.com/hedy/4)
**Checklist**
- well, kinda
=> fix grammar in German Level 4 intro & bring its text closer to the English version

templates/level-page.html
In the discussion about removing the palette, I've added some ideas. This PR is the result of the last [idea](https://github.com/Felienne/hedy/discussions/1835#discussioncomment-2132503). 
Should show all the commands available per level, when hovering the "🤔" button.
=> Added small new button containing list of commands per level

templates/class-overview.html, website/teacher.py
< Remove whitelisting for teachers' access to the class stats page >
< Remove whitelisting for teachers' access to the class stats page > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"
**Fixes < #1950  >**
- Run Hedy locally and log in a teacher. Ensure that you do not have a BETA_TEACHERS environment variable set.
- Go to /for-teachers and select one of the existing classes
- Ensure that the /for-teachers/class/$class-id page contains a show class statistics …
=> Remove whitelisting for teachers accessing class stats #1950

content/adventures/de.yaml, content/adventures/en.yaml, content/adventures/nl.yaml
Fixes issue #1986 by replacing assignment operator by keyword 'is'
**Fix for**
Fixes #1986
Check out branch, open level 5, adventure "rock, papers, scissors". Sample code now show keyword is in line 1
**Checklist**
=> Make use of keyword is instead of '='

.github/workflows/unittests.yml, requirements.txt
Jinja2 has a dependency on the `MarkupSafe` library. With the recent update of this library to `2.1.0` the `soft_unicode` function is no longer supported: but required by Jinja2. We solve this by temporary downgrading the MarkupSafe library until Jinja2 has come up with a solution. The following error occurred when running unittests:
`ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)`
**Fix for**
This PR fixes #2027 
This is a back-end bug fix, it works when the unittests work again.
**Checklist**
=> [BUG FIX] Downgrades MarkupSafe from 2.1.0 to 2.0.1 to prevent unittest failing

templates/feedback.html, templates/quiz.html, templates/quiz_question.html
In this PR we fix an issue where newlines where not correctly displayed when showing the correct quiz answer. This was solved by adding the `nl2br` function to the `jinja2` variable. We also slightly improved some quiz styling by removing redundant empty(?) `div` elements, removing `<br>` elements as we can style this with dedicated elements and margins as well as decreased the size of the correct quiz answer. We also fix another small bug where the strings `Vraag`, `Poging` and `Hint?` where hard-coded instead of the (already existing) yaml keywords.
**Fixes**
This PR fixes #1291 and fixes #2069.
Navigate to a quiz where the answer contains multiple lines. For example, level 8 question 1 in Dutch. Verify that the answer now correctly displays with the …
=> [BUG FIX] Correctly displays newlines on quiz answers

website/auth.py
In this PR we fix an issue which resulted in the website crashing when signing up due to an incorrect settings of the `email` value which is required for the "newsletter" and "request teacher" process.
**Fixes**
This PR fixes #2123.
We can't test this locally as we need the server functionality for mailing stuff. Deploy to alpha and verify that all checkboxes are working on signup.
**Checklist**
* If you're unsure about any of these, don't hesitate to ask. We're here to help!
=> [BUG FIX] Signup no longer crashes on newsletter / teacher checkbox

website/auth.py
In this PR we fix an issue where the e-mail template function would crash due to an incorrect concat function.
**Fixes**
Can only test on Alpha, deploy and verify that signup is working correctly again.
**Checklist**
* If you're unsure about any of these, don't hesitate to ask. We're here to help!
=> [BUG FIX] Email template no longer crashes due to incorrect concatenation

grammars/level18-Additions.lark, grammars/level5-Additions.lark, hedy.py, hedy_translation.py, tests/test_level_05.py, tests/test_level_06.py, tests/test_translation_level_05.py
Fixes #2116 
It is a bit of a hack (it always was!) but this disallows the use of if/else in strings allowing us to fix #2116. We now do so in the grammar of level 5 for all languages, at one point we might want put this in each language because otherwise legal programs become problematic for no good reason because there can be many words for if/else in all languages. But this will do for now. Left in the extra test too.
=> Exclude if/else in all supported languages

coursedata/adventures/en.yaml, coursedata/pages/for-teachers/en.yaml, coursedata/texts/en.yaml
last empty strings are now filled in en.yaml files. Since all languages have empty strings as translations, these additions will show up as "fuzzy" or "needs edit" in Weblate. 
From now on, empty strings should be avoided.
=> fill last empty strings for translation

tests_e2e.py, website/auth.py
In this PR we add some additional tests for language and keyword language changes. These were not already implemented within the `profile_modify` function as they are mandatory and should be handled separately to test.
**Fixes**
This PR fixes ##2229
This is only a validation chore run by the server, if it passes it works.
=> [CHORE] Adds extra e2e tests for language and keyword language changes

SEMANTICS.md
< Provide a one line summary of your changes in the Title of the PR >
< In level 1, `turn` could be used with `left` or `right` and then an integer, or with nothing, and if I remember correctly also with just an integer. Now, in level 1, `turn` can only be just with only `left`, `right`, or nothing. So not yet with integers (this changes in level 2 already, when `left` and `right` are not used anymore and `turn` is used with nothing or only an integer). This pull request is to update the semantics. > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"
**Fixes < n.a. >**
< Always link the number of the issue or of the discussion that your …
=> semantics change level 1 turn

translations/tr/LC_MESSAGES/messages.po
#2110 caused Webalte to be sad about all the missing texts yamls. This should make it back in order!
=> Fix Weblate texts issues

grammars/level6-Additions.lark, tests/test_level_06.py
This PR will allow for users to have spaces in their string assignments in levels 6 through 11.
Adds `textwithspace` to the assignment in the `grammars/Level6-Additions.lark` file
**Fixes #2073**
Added a unit test to `tests/test_level_06.py` called `test_space_in_string_assignment` that checks for spaces in string assignments with and without quotes both using `is` and `=`. The unit test does not pass without the change in `grammars/Level6-Additions.lark`, and the test uses `multi_level_tester` to assess levels 6 through 11.
=> Space In String Assignment Fix for levels 6 to 11

website/programs.py
Due to a type mismatch of the `Public` value program saving was no longer possible. This is due to Dynamo expecting a number as index key, but we store the `public` value as a boolean. We fix this in this PR.
**Fixes**
This can only be tested on Alpha as the local db file doesn't care about type mismatching. Deploy to Alpha and verify that storing programs is working once again.
=> [BUG FIX] Saving programs works again

grammars/level12-Additions.lark, grammars/level5-Additions.lark
< Refactor the error_invalid grammar rule >
< Change a comment in level 5 which clarifies the error_invalid changes; Remove a redefinition of the error_invalid rule in level 12 > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"
**Fixes < TODO for #1632  >**
< See the comment change in level 5. Is it clear? >
< If this is a language change, add a few tests showing the difference >
**Checklist**
* If you're …
=> Refactor the error_invalid grammar rule #1632

coursedata/level-defaults/ar.yaml
In this PR we fix Arabic level 1. It was broken due to keywords being surrounded by curly brackets but without using the placeholder values. So the translated values where already in the strings, resulting in a key error when parsing the translated keywords.
**Fixes**
Verify that level 1 of Hedy is loading without an error in Arabic. All other levels should already be working as the error does not exist there.
=> [BUG FIX] Arabic level 1 works again

coursedata/adventures/en.yaml, coursedata/adventures/nl.yaml, coursedata/level-defaults/en.yaml, coursedata/level-defaults/nl.yaml
In this PR we localize the left/right **and** random keywords in both the English and dutch version. As the translations are all using English as a starting point we hope that this fixes ambiguity when translating. The curly brackets should clarify that the keywords should not be translated.
**Fixes**
This PR fixes #2335
Small clean-up, doesn't have to be tested.
=> [CONTENT FIX] Localizes left/right keyword

hedy.py, hedy_translation.py
In this PR we add Norwegian to supported keyword languages. This was already added in the translation file but not yet in the dict on which we base the front-end options. I assume this was an error which make sense as it doesn't make sense to keep track of two identical dictionaries. Therefore in this PR we also remove one of them to include the other one.
**Fixes**
Verify that Norsk is now a keyword language option on profile creation and updating. Verify that Norks only works if your profile language is actually set at Norks. Verify that it is all working correctly and all placeholders are correctly parsed.
=> Adds Norwegian to supported keyword languages

CONTRIBUTING.md, app.py, coursedata/achievements/ar.yaml, coursedata/achievements/bg.yaml, coursedata/achievements/bn.yaml, coursedata/achievements/cs.yaml, coursedata/achievements/de.yaml, coursedata/achievements/el.yaml, coursedata/achievements/en.yaml, coursedata/achievements/es.yaml, coursedata/achievements/fr.yaml, coursedata/achievements/hi.yaml, coursedata/achievements/hu.yaml, coursedata/achievements/id.yaml, coursedata/achievements/it.yaml, coursedata/achievements/nb_NO.yaml, coursedata/achievements/pl.yaml, coursedata/achievements/pt_BR.yaml, coursedata/achievements/pt_PT.yaml, coursedata/achievements/sw.yaml, coursedata/achievements/tr.yaml, coursedata/achievements/zh_Hans.yaml, coursedata/pages/achievements/en.yaml, templates/achievements.html, templates/public-page.html
This reverts commit e676f0d1dd34e7701f9e4ef56e35383f18bc6117.
In this PR we reverse the achievements re-structuring as it broke a lot of functionality we didn't take into account (such as the achievements pop-ups). We should first discuss an efficient way to tackle this problem before trying to fix it again.
=> [REVERT FIX] Reverts achievements re-structure

content/level-defaults/nl.yaml
The title describes the fix.
**Fixes**
This PR fixes #2447
=> Fix issue #2447: Add a missing quotation mark in hedy level 4 NL

app.py, templates/incl-menubar.html, templates/layout.html, templates/profile.html, translations/ar/LC_MESSAGES/messages.po, translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/el/LC_MESSAGES/messages.po, translations/en/LC_MESSAGES/messages.po, translations/es/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fr/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/hi/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/nb_NO/LC_MESSAGES/messages.po, translations/nl/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po
In this PR we make some small fix to improve performance overall. We remove the `@app.context_processor` db calls. These calls where made at each template render to make sure the data was available, however in most cases this data was redundant. We now only make these db calls when rendering the actual relevant pages. We also remove some redundant Babel explanation as that is already mentioned (and improved) in CONTRIBUTING.md. Lastly we remove the "set a preferred language" header, which has become redundant as it's already over 6 months shown to users without a set language. We still catch the possible errors, so this is no longer an issue. And we remove the "Statistics" header on the profile page as it is not really relevant.
**Fixes**
This PR fixes #2445
**How to …
=> [IMPROVEMENT] Reduces db calls by simplifying user data retrieval

templates/code-page.html, templates/view-program-page.html
In this PR we fix a small issue where the error messages on the program view page weren't working due to a missing include. The actual issue isn't the bug, but the weird structure we use with `window.State` to pass relevant info such as the current level. It would be nice of we perform some clean-up on the `{% block scripts %}` elements to ensure these bugs don't happen again.
**Fixes**
This PR fixes #2463.
Make sure there is a shared incorrect program. Navigate to the share link and verify that the error message is shown correctly when trying to run on the program view page.
=> [BUG FIX] Error messages work again on program view page

grammars/level5-Additions.lark, grammars/level6-Additions.lark, hedy.py, tests/test_level/test_level_05.py, tests/test_level/test_level_06.py
< Remove grammar ambiguity with consecutive if-statements at levels 5-7; Refactor tests for if and if-else statements >
< Remove grammar ambiguity with consecutive if-statements at levels 5-7; Refactor tests for if and if-else statements > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"
**Fixes < #2471  >**
< All changes are covered with tests. The tests are refactored, so that the same test has the same name across multiple levels. Examine the tests and …
=> Remove grammar ambiguity in if-statements at levels 5-7 #2471

website/database.py
In this PR we reverse a fix made in #2479 that depends on two index keys and a sort key to automatically retrieve all user programs for a specific level. This works fine with the local database, but does seem impossible to work around with the actual Dynamo db. Therefore we reverse this and use a list comprehension to filter the correct programs.
**Fixes**
Locally everything should work exactly the same. Verify that on alpha the `/hedy` page is working again after merging this PR.
=> [REVERSE FIX] Removes double Dynamo index key dependency

grammars/level6-Additions.lark, tests/test_level/test_level_06.py
Fix incorrect parsing of ask in level 6
In the grammar level 6 creating lists had priority over the ask command. As a result, an ask statement with quoted commas would be parsed as a list assignment instead.
**Fixes #2497**
Run Hedy locally, go to level 6 and run the following code:
```
naam is Hedy
gang is something
eten is ask naam ', Wat wil jij bestellen als ' gang '?'
print eten
```
Ensure there are no errors and that the ask statement actually asks you for input that is printed afterwards.
**Checklist**
=> Fix incorrect parsing of ask in level 6 #2497

translations/nl/LC_MESSAGES/messages.po, website/auth.py
In this PR we fix the password reset where an invalid link was created as well as an invalid mail template. This might be introduced due to the mail template clean-up, but should work again. We should merge this to Alpha with some priority to verify that it is all working as well as currently users that forgot their password are stuck.
**Fixes**
This PR fixes #2574
Merge to Alpha and test the password reset. The mail template (in Dutch) should be current again with a valid link.
=> [BUG FIX] Fixes faulty link creation for password reset

build-tools/heroku/on-deploy.sh
Removing the fuzzy compiling of Babel results in some languages not being compiled at all. This is unexpected and undesirable behavior. We reverse this change in this PR.
=> [REVERSE FIX] Enables fuzzy compiling of Babel again

app.py
In this PR we improve the error handling when a non-logged in user tries to start the tutorial. Instead of the currently empty error page that is returned we redirect the user to the login page.
**Fixes**
This PR fixes #2791
Make sure you are not logged in and visit the `/tutorial` page. Verify that you are being re-directed to the login page.
=> [IMPROVEMENT] Redirects user to login when trying to visit /tutorial

hedy.py, tests/test_level/test_level_06.py
Level 6 was failing to print single digits in a print statement due to
the fact that check_var_usage was considering numerical strings as
candidates for variables.
This commit will also filter out numerical values from the arguments to
be processed for print statements.
Fixes #2794
Print a single digit in level 6.
=> [BUG] Skip numerical values in check_var_usage

templates/quiz/feedback.html, templates/quiz/quiz_question.html, website/quiz.py
Question 2 of level 6 of the quiz contained some one character answers. Due to using the `|commonmark` parser on the front-end the options are parsed into HTML from the Markdown format. However, for some reason single mathematical symbols are in this case replaced by a black dot marker. To prevent this we create a bit of a bucket-workaround-fix, if and only if the option is only one character: don't use common mark but show as plain text instead. This solves our bug.
**Fixes**
This PR fixes #2807.
Navigate to level 6 -> quiz -> question 2. Verify that the mathematical symbols are shown as expected.
=> [BUG FIX] Fixes quiz lvl 6 question 2

app.py
In this PR we fix an issue where not all keywords where correctly localized on the `/explore` page. This was due to some programs being partly with English and partly with non-english keywords. As we only parsed the code once to the set user keyword language this introduced bugs. We fix this by parsing twice if the user set keyword language is non-english. First to English, then to the selected user language. This is the only way we can guarantee that all keywords are translated, see the following example:
A dutch user might create a program containing both dutch and English keywords. In the original situation we didn't parse the program if our profile was also set to dutch. As the program language is the same as our keyword language. So, the following program would be …
=> [BUG FIX] Keywords are always correctly localized on /explore page

CONTRIBUTING.md, TRANSLATING.md
We add the newly created Discord channel link to `CONTRIBUTING.md` to enable external contributors to get in touch with us.
**Fixes**
Nothing to test.
=> Adds Discord link to CONTRIBUTING.md

CONTRIBUTING.md
In this PR we update `CONTRIBUTING.md` to add an explanation to use localhost in the case that 0.0.0.0 is not working as address. The cause is unknown, but this bug seems to appear on several Windows machines.
**Fixes**
This PR fixes #2815.
Nothing to test, verify that CONTRIBUTING.md is updated.
=> Adds explanation on localhost

templates/quiz.html, tests_e2e.py
In this PR we fix an issue where the tutorial would crash due to a missing variable that was expected by the .html template. However, this mistake should never have been merged in the first place. This is our own mistake by not updating the e2e tests to also verify that the `/tutorial` route is still valid in all languages. To prevent this we also fix the e2e tests for the tutorial.
**Fixes**
This PR fixes #2840.
Login and navigate to `/tutorial`. Verify that it is working again.
=> [BUG FIX] Tutorial works again and improve e2e tests

app.py, templates/view-program-page.html, utils.py, website/admin.py, website/teacher.py
In this PR we replace all currently manually formatted date times into formats suggested by Babel. The Babel library automatically selects the expected format corresponding to the current language. The new function `localized_date_format()` takes a date object as well as a `short_format` boolean as we store some values in ms and some in s. In the first case we have to remove the last three characters before parsing to a date object, in the second case we can directly parse.
**Fixes**
This PR fixes #2868.
The formatting is changed in several spots, verify that it is shown as expected in all places:
- The submitted program page
- The class overview page (last login as well as invites)
- Admin page (created, last login)
=> [UI IMPROVEMENT] Replaces all datetimes with localized versions

app.py, templates/highscores.html, website/database.py
In this PR we make a nice QoL fix where we always show the current user in the highscore, even if not ranked top 50. This is nice when deploying to production as we have 50+ users with a public profile. When not in the top 50 the user is still shown in the list with their own ranking. So for example:
```
1. user1 
2. user2
...
49. user49
50. user50
124. <current_user>
```
**Fixes**
This PR fixes #2969.
Can't be tested. Validate that the code seems logical and deploy to production, there we can validate that it works.
=> [FEATURE] Always shows user in highscores, also when not ranked

messages.pot, templates/highscores.html, translations/ar/LC_MESSAGES/messages.po, translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/el/LC_MESSAGES/messages.po, translations/en/LC_MESSAGES/messages.po, translations/eo/LC_MESSAGES/messages.po, translations/es/LC_MESSAGES/messages.po, translations/et/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fr/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/hi/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/ja/LC_MESSAGES/messages.po, translations/nb_NO/LC_MESSAGES/messages.po, translations/nl/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po, website/database.py
In this PR we fix the highscores counter filtering. For unknown reasons there seems to be usernames that return a none value when requesting the user data. This shouldn't be possible, but it makes the page crash. We surround this by a try-except to catch the error. We also improve the code a bit and change a table header to make more sense.
**Possible issue**
The only possible issue I can think of is that a user removed their profile but their public profile remained. This shouldn't be possible, but we have to dive into this later on.
Can't be tested, deploy to beta and verify that it works (Alpha the error didn't happen).
=> [BUG FIX] Highscores country filtering no longer crashes

templates/base_email.html
Sign-up was broken due to a Babel key within the mail template, crashing on the `format()` function. This is fixed.
**Fixes**
This PR fixes #3012.
Create an account, verify that you are correctly logged in and redirected to the landing-page.
=> [BUG FIX] Signup works again

templates/login.html, templates/profile.html, templates/recover.html, templates/reset.html, templates/signup.html
In this PR we fix an app breaking issue where are forms would no longer work as expected. This was due to our front-end template clean-up where we removed the `js-validated-form` class from all forms. This class is essential for some value matching we do before sending the package to the back-end. This is vulnerable and should be removed in the near future, but to fix all functionality we reverse this removal.
This bug was my mistake by not taking the dependency of the `js-validated-form` class in account. But, this should not have been possible in the first place. We already perform all validation on the back-end and should not rely on the front-end to also perform some form validation. All input fields are already validated by the HTML attributes themselves as well. …
=> [BUG FIX] All forms work again as expected

grammars/level16-Additions.lark, tests/test_level/test_level_16.py
Changes the grammar for lists in level 15 to allow both empty lists and lists containing a single element in it. Since starting from this level we ask users to use brackets around lists, we now can allow them to create this types of lists.
**Fixes #3050*
I added a couple of tests to showcase this behavior.
=> [LANGUAGE] Adds support for empty lists starting from level 15

hedy.py, tests/test_level/test_level_05.py
Changes de functions that process the `list_access_var` rule to be able to parse correctly lists access using indices.
**Fixes #3110 **
I added a test on level 5 to test this behavior.
=> [BUGFIX] Fixes list access using indices on level 5+

grammars/level5-Additions.lark
It is still a mystery to me why on earth this suddenly fails (we seem to have merged the last change in Russian 2 months ago!) but this is a hotfix and I think we have an issue open for the root cause (but I still would like to understand why it can just pop up like this?!)
=> [LANGUAGE] Fix for else in Russian in level 5

utils.py
Test requests are used for e2e tests, which run against local
debug instances. They should not be allowed on Heroku (neither
staging nor the production environment).
=> [FIX] disable test requests on Heroku

templates/layout.html
In this PR we fix an issue where Edge would automatically translate English keywords to Dutch in some cases. This is undesirable as we want to decide in what language the keywords are shown and not our browser. We prevent this by manually adding the `class="notranslate"` to our layout template, which should work.
**Fixes**
This PR fixes #3208.
Make sure you are using Edge on a non-english language (for example Dutch). Verify that the browser no longer translates the keywords when they are set in English and therefore should be shown in English.
=> [BUG FIX] Prevents Edge from auto translating page

templates/admin/admin-classes.html, templates/class-overview.html, templates/customize-class.html, website/teacher.py
In this PR we enable the admin to view the class overview as well as the class customizations of each class. We change the UI a bit when the admin views these specific pages to make sure it is clear that no alterations can be made. These would still be caught by the server as the admin is not the teacher of the class, but still. 
**Fixes**
This PR fixes #3194.
Make sure you are admin and there are classes for which you are not the teacher. Verify that you can visit these as well as the customizations but the buttons are hidden.
=> Enables admin to view class overview

website/database.py
`get_many(..., sort_key=)` was still being passed in a couple of places.
Remove them.
=> [FIX] Admin classes page throws 500

website/database.py
The users admin page was loading as many users as it could -- change it to 500 users so the page loads faster.
=> [FEAT] Limit the admin users page to 500 per page

website/auth.py
In this PR we fix a specific bug where the signup flow would be broken when selecting one language of the programming experience options. This was due to one item automatically being sent to the back-end as a string where we expect a list. We now typecast if we find a string and keep the rest of the validation the same.
**Fixes**
This PR fixes #3320
Create an account and select programming experience 'yes' and select only one language. Verify that you can signup successfully.
=> [BUG FIX] Able to create account with one programming experience again

translations/bg/LC_MESSAGES/messages.po, translations/bn/LC_MESSAGES/messages.po, translations/cs/LC_MESSAGES/messages.po, translations/de/LC_MESSAGES/messages.po, translations/fa/LC_MESSAGES/messages.po, translations/fy/LC_MESSAGES/messages.po, translations/hu/LC_MESSAGES/messages.po, translations/id/LC_MESSAGES/messages.po, translations/it/LC_MESSAGES/messages.po, translations/pl/LC_MESSAGES/messages.po, translations/pt_BR/LC_MESSAGES/messages.po, translations/pt_PT/LC_MESSAGES/messages.po, translations/ru/LC_MESSAGES/messages.po, translations/sw/LC_MESSAGES/messages.po, translations/tr/LC_MESSAGES/messages.po, translations/zh_Hans/LC_MESSAGES/messages.po
Merging #3271 caused duplicate strings. This fixes it.
=> [WEBLATE] remove duplicate strings

.github/workflows/update-javascript-on-main.yml, build-tools/heroku/generate-grammars-and-js, build-tools/heroku/on-deploy.sh
We currently only update the grammars on deploy but do not merge them back to main, leading to confusing situations! f.e. Hebrew currently exists in the site:
But not in the files:
Superconfusing!! Just spent 15 mins thinking haha. Let's safe other people brain cycles by generating it all when we merge
=> [CHORE] update grammars back to main on merge

.github/workflows/update-javascript-on-main.yml
Workflows that run in the context of forks cannot use secrets.
By changing `pull_request` to `pull_request_target`, the workflow will run in the context of the `Felienne/hedy` repository, and will therefore have access to the permissions of that repository (GitHub tokens to make commits on behalf of Felienne, for example).
To make sure drive-by contributors can't steal the secrets, this also causes the workflow file from `main` to always be used (instead of the workflow file on the PR branch itself).
=> [FIX] Give the "Update JavaScript" workflow correct permissions

templates/customize-class.html, templates/level-page.html
We partly re-implement the code deleted in #3327 where we decided to remove the language switcher from the code editor. We now re-introduce a "hide keyword switcher" but instead aim on the menubar dropdown keyword switcher. The back-end code can remain the same, we only had to make some adjustments to the front-end.
This PR fixes #3354.
Make sure you are in a class and have a keyword-supported-non-english profile language. Verify that you can see and use the keyword switcher dropdown from the menubar. When hidden using the class customizations the button should been gone.
=> [FEATURE] Allows teachers to hide/show keyword switcher in menu bar

templates/incl-menubar.html, website/admin.py
This PR adds a menubar item for the /admin page in the menubar. Personally I don't like having to manually navigate to /admin each time I log in as an admin: this PR saves us one step.
**Fixes**
Log in as an admin, verify the new menubar item. Also verify that it is not there when not logged in as admin.
=> [FEATURE] Adds admin menubar item if admin

grammars/level2-Additions.lark, grammars/level3-Additions.lark, tests/test_level/test_level_02.py, tests/test_level/test_level_04.py, tests/test_level/test_level_12.py, tests/test_level/test_level_18.py
Comments are already working in level 1 and in levels 5 and up. This fixes it for the remaining levels and adds some tests. The fix is a grammar update so the # is not part of text, and there are updated tests too.
**Fixes #3286 **
The code below is basically what's used to report the issue and doesn't work correctly in levels 2-4 (Note the single quotes to get correct statements for level 4). You can use this to verify that the issue does not exist on the feature branch.
```
print 'hello world!' # with a comment
print 'hello world!' # with a comment
print 'hello world!' # with a comment
print 'hello world!' # with a comment
print 'hello world!' # with a comment
```
The code …
=> Adds support for comments in levels 2-4

website/admin.py, website/auth.py
We usually use the language of the current user when sending emails, but that is not suitable in all cases. Specifically if an admin needs to email a user, this should be done in the language of the user.
This fixes the issue when an admin marks a user as teacher, and also when an admin changes the email address of a user.
**Fixes #3289 **
As stated in the issue, this is hard to test locally because sending emails does not work locally. This would need to be tested on alpha.
**Checklist**
=> Allows sending emails in other languages

CONTRIBUTING.md, Dockerfile
Update the Dockerfile to no longer copy the project files into the container during `docker build`, and update the documentation in CONTRIBUTING.md with instructions to use bind mounts instead. This should eliminate the need to rebuild the docker image after each change to the code!
I tested the updated `docker run` command on my Linux installation and everything seems to work there, but it would be nice if people could test this command on other platforms (Windows+Powershell comes to mind...), so I know whether I need to add additional instructions for those other platforms.
Fixes #3412 
(Re)build the docker image (possibly with the `--no-cache` option) and use the updated `docker run` command from CONTRIBUTING.md to launch the new version of the …
=> (3412) No longer copy files to Docker container during docker build, use bind mount instead

CONTRIBUTING.md
Turns the mention of `TRANSLATING.md` in `CONTRIBUTING.md` a link instead of just a text mention.
This is just a minor documentation edit.
=> Fix TRANSLATING.md link in CONTRIBUTING.md

app.py, exceptions.py, hedy.py, hedy_translation.py, tests/test_translation_error.py, translations/en/LC_MESSAGES/messages.po, translations/nl/LC_MESSAGES/messages.po
Fixes #2907 in a very extensive way, all languages can now add {} around keywords in exceptions and tips and these will be localized when a user language is set in a user's profile.
This does not yet work when using the switcher but I will make a separate issue for that since it is all front-end magic beyond my comprehension :) 
Note that I have now only made the textual change in en and nl, this is to prevent Weblate conflicts, after we are stable there I will make some more changes to existing languages!
=> [LANGUAGE] Localize commands in error message

requirements.txt
`awscli 1.*` and `pylint >= 2.14.3` have an unresolvable dependency conflict on `colorama`, on Windows.
* `awscli` requires `colorama < 0.4.5`
* `pylint` requires `colorama >= 0.4.5`
Not sure what colorama did to cause this split, but there you have it.
`awscli 1` is not going to change their version in a million years, since they've deprecated the CLI v1 and are putting all development effort into CLI v2, which installs completely differently, no longer via PIP.
We can consider dropping the `awscli` (I think would mostly impact ops scripts) but for now let's downgrade `pylint`  a little to pre-conflict days.
=> [FIX] Python requirements no longer install on Windows

app.py
In #3410 we introduced a little issue that stopped error counts from being logged correctly, leading to "nice" stats this week haha:
This was due to an uninitialised variable which this PR fixes.
=> [FIX] Log error program count again

app.py
_The request handler for single adventure was not handling the `keyword_language` parameter. In turn the language to be passed to `load_adventures_per_level` function was always the language in app context `g`. At the same time, in `load_adventures_per_level` function the language argument was not to use as key for `ADVENTURES`.
Fixes for code style._
**Fixes https://github.com/Felienne/hedy/issues/3485 **
It probably has some impact on https://github.com/Felienne/hedy/issues/3433 as well. In the top-right corner I don't see the language switcher though, only my username, so not able to test that.
Run locally, and browse to single adventure. Use the translation button to switch language
=> Fix language handling when loading adventure

.mergify.yml
With the old config, all PRs are squash-merged, which is great for history but confuses Weblate.
Except Weblate PRs to make them be regular-merged instead.
=> [FIX] Make Mergify regular-merge Weblate PRs

.mergify.yml
The advantage of using the merge queue is that Mergify will only ever try to merge 1 PR at once, and will automatically keep it up-to-date with `main` if that is necessary.
Also make Mergify post a nice comment when it's taking over, to let people know they need to stop clicking buttons.
=> [CHORE] Use Mergify "merge queue" feature

hedy.py
Adds 'input' to the list of reserved words, as it's a Python method that our generated code can call.
**Fixes issues/3454**
Fixes https://github.com/Felienne/hedy/issues/3454 (I think and hope)
This program fails on level 11 before the change but should succeed after it:
```
input = "some string"
x = ask "question"
```
If we want, I can try to add a unit-test for this, but I'm not sure where to put it. `test_level_02.py` since the the issue can be reproduced from that level onward? (Or perhaps it's a bit overkill to test every reserved keyword? I'm flexible on the matter.)
**Checklist**
=> Extend list of reserved words

.mergify.yml
Currently, Mergify happily claims "Choo choo" on a PR even if it has **Changes requested** reviews attached -- even though GitHub won't actually allow those PRs to be merged.
Change the rules to take those into account as well.
=> [CHORE] Mergify ignores changes requested reviews

grammars/level12-Additions.lark, tests/test_level/test_level_12.py
Adds a generalize grammar rule for `print_expression`
[3516](https://github.com/hedyorg/hedy/issues/3516)
Open a level higher or equal than 12 and issue a `print <float>`
=> [BUGFIX] Allow for printing floats from level 12

grammars/level1.lark, tests/test_level/test_level_01.py
This small grammar change makes Hedy ignore also those comments that have zero length.
Such comments are allowed in Python, but yield errors in Hedy, until this patch is applied.
=> [GRAMMAR] Allow empty comments

templates/level-page.html
In #3570 I forgot to rename two instances of `get_trimmed_code()` breaking the ability to save programs. Oops!
=> [FIX] rename get_active_and_trimmed_code() missed in #3570

app.py, hedy_content.py, translations/tn/LC_MESSAGES/messages.po, utils.py
In this PR we fix the support for Tswana that is not natively supported by Babel. We use the same work-around as we used in #3599 for adding support for `pa_PK`. Simply re-direct Babel to another language when the non-supported language is called but **do not** overwrite the locale parser -> keep this to the original "unsupported" language.
**Fixes**
This PR fixes #3600.
Verify that Tswana is listed in the language dropdown selector. Also verify that the translations are wrapped correctly by both changing some stuff in the `tn.yaml` files in `/content` and the .po files in `/translations`. In the second case don't forget to compile the translations.
=> [FIX] Manually adds support for Tswana

tests/test_snippets/test_adventures.py
#3583 accidentally commented out some tests using the filters. No problem because they do run but let's restore them!
=> [FIX] run all tests again, disable filters

.github/workflows/unittests.yml
In #3623  we accidentally allowed changes to `app.py` to trigger all tests, which shouldn't be the case. In this PR we remove it from that section of github actions.
=> [TESTING] Remove app.py from triggering language related tests

.github/workflows/deploy-to-prod.yml
Make sure only people with sufficient permissions, *configured on the repository*, get to run the "deploy to prod" workflow.
After merging: run the workflow. It should work. Let me run the workflow. It should not.
=> [CHORE] Prevent "deploy to prod" workflow from being accidentally run

.github/workflows/unittests.yml, build-tools/github/validate, build-tools/github/validate-tests
In this PR we expand our Github actions file to only run the snippet tests when a PR comes from Weblate. As we know this PR can only contain content changes we should be fine by only validating the code snippets. This highly speeds up the process of testing. We do have to keep in mind that, if for some reason, the Weblate translations break the front-end we don't test this any longer.
**Fixes**
This PR fixes #3652.
Merge this PR, re-run the jobs for a weblate PR and verify that only the snippets are tested.
=> [TESTING] Only test snippets when PR comes from Weblate

templates/incl-editor-and-output.html
In this PR we fix an issue with the `runit()` function that was broken in French. This was due to the default error message `already_programming_running` containing an `'` character. As the placeholder was also surrounded by `' '` to clarify as a string for Typescript the function broke. We fix this by using the Jinja2 function `|tojson` to always safely escape html special characters.
**Fixes**
This PR fixes #3661
Verify that Hedy works again in French.
=> [FIX] Fixes issue with french front-end error when running program

.github/workflows/update-javascript-on-main.yml
This script historically never needed Python, so didn't do `pip install`. 
It now does, so we need to add `pip install` as well.
After merging, the Update JavaScript action will run successfully, even if `import regex` appears in a Python script.
=> [CHORE] Install Python and dependencies in JavaScript action

.github/workflows/update-javascript-on-main.yml
Used the wrong context field to try and get the branch name.
Merge and wait for nothing to fail.
=> [CHORE] Fix GitHub ref name

.github/workflows/update-javascript-on-main.yml
We need to check out the source with a push-enabled token, otherwise the commit action later on will fail. Never mind that we pass that the correct token, it will not overwrite the token in the git checkout.
Run more workflows and see if they fail.
=> [CHORE] JavaScript flow: use push token on checkout

templates/incl-editor-and-output.html, tests/cypress/e2e/hedy_page/programmers_mode_switch.cy.js, tests/cypress/e2e/hedy_page/run_code_button.cy.js, tests/cypress/e2e/tools/navigation/nav.js
[CYPRESS, TESTING]
With these front-end tests the 'Run code' and programmers mode switch on the `/hedy` page are tested. I created id's in the HTML file to select the buttons and I implemented a function which navigates to the `/hedy` page that can be used for these tests but also for future tests.
Fixes #3692 
Run
`export ADMIN_USER=admin_user; python app.py` in your virtual environment. This ensures that there is an active admin_user and Hedy is running.
Then you can go to the /tests folder and run:
`npx cypress run --spec cypress/e2e/hedy_page/`
=> [TESTING, CYPRESS] 3692 front-end test for the run code button and programmers mode switch

templates/signup.html, tests/cypress/e2e/signup_page/birthyear_create_account.cy.js, tests/cypress/e2e/signup_page/country_create_account.cy.js, tests/cypress/e2e/signup_page/email_create_account.cy.js, tests/cypress/e2e/signup_page/gender_create_account.cy.js, tests/cypress/e2e/signup_page/language_create_account.cy.js, tests/cypress/e2e/signup_page/newsletter_create_account.cy.js, tests/cypress/e2e/signup_page/password_create_account.cy.js, tests/cypress/e2e/signup_page/privacyterms_create_account.cy.js, tests/cypress/e2e/signup_page/programming_experience_create_account.cy.js, tests/cypress/e2e/signup_page/username_create_account.cy.js
This includes the tests for the fields of the sign-up page
Fixes #3729 
Run 
`export ADMIN_USER=admin_user; python app.py` in your virtual environment. This ensures that there is an active admin_user and Hedy is running.
Then you can go to the /tests folder and run: 
`npx cypress run --spec cypress/e2e/signup_page`
=> [TESTING, CYPRESS] Tests for fields on create account page

CONTRIBUTING.md
As noted in #3732 pybabel must be ran before Cypress tests
=> [DOCS] Update CONTRIBUTING.md

.github/workflows/unittests.yml
Somehow #3744 did not stick on main: 
Trying again (and I will now bypass mergify manually, maybe that was the cause?)
=> [CHORE, TESTING] Updating the action tester, again

utils.py
Fixes #3793. it sets the audio drivers for PyGame to _disk_ (essentially a dummy driver). 
Found on: https://stackoverflow.com/questions/72311056/alsa-not-found-github-actions-unit-testing-setting-env-envvars-correctly
=> [BUG] GitHub Actions Error "ALSA lib ..."

content/adventures/en.yaml
[Fix] Now there are short intros for pressed in level 5 and 8. No other big changes are introduced to pressed.
Fixes issue #3548
=> added pressed intro to level 5 and 8

.pre-commit-config.yaml
This PR updates the .pre-commit-config.yaml file to apply autopep8 autoformatting before doing a final check using flake8. 
**Fixes #3377 **
Install the pre-commit locally using `pre-commit install`, or better yet: let's set up pre-commit.ci to automatically do it for us :)
=> [CHORE] Update pre-commit config to include autopep8 before flake8 linting

.github/workflows/unittests.yml
Since #3873 we do not need to check for changed files, the hashes take care of that!
=> [CHORE, TESTING] Remove checking for changed files

templates/code-page.html, templates/incl-adventure-tabs.html
On non-Safari browsers, scroll bars take up horizontal and vertical space.
Remove two causes of unnecessary space between elements.
=> [FIX] Design: remove scroll bars

content/quizzes/en.yaml
Fix typo in level 4 quiz -- `Bayer` instead of `Bayern`.
* Just go to question 9 in the level 4 quiz and see the question and answers.
**Checklist**
Done? Check if you have it all in place using this list:
I'm also not sure if `Munchen` should be spelled `München`?
=> [FIX] typo in level 4 quiz

.github/workflows/generate-snippet-hashes.yml
We now save hashes for test runner speed (see #3873) But... Every week is not really enough to prevent looooong waits... why not every day (it is free, after all!)
=> [CHORE] Run hashes every day

templates/incl-editor-and-output.html
A different fix for the code editor scrollbar, one that is compatible with the *programmer's mode* toggle.
Right now, it works by putting fixed heights (`22rem` and `36rem`) on the elements.
http://localhost:8080/hedy/7
```
repeat 30 times print 'Hedy is fun!'
```
See a scrollbar. Toggle programmmer's mode.
Fixes #https://github.com/hedyorg/hedy/issues/3982.
=> [FIX] Design: output height

grammars/level3-Additions.lark, hedy.py, tests/test_level/test_level_03.py
Fixes #4010. It now prints a space after a random but I guess that is ok for now (of course in level 4 this will be fixed anyway)
=> [FIX, LANGUAGE] Allow punctuation after random

templates/incl-menubar.html
A picture is worth a thousand words...
=> [FIX] Design: Language dropdown shows white underbar overlaying menu

templates/incl/menubar.html
If you are looking for a language, you previously needed to click the language dropdown, then the input, and only then could you start typing.
Focus the language input immediately on opening the dropdown so you can start typing right away.
Click the Language dropdown, start typing.
=> [FEAT] UI: focus language input on opening dropdown

templates/incl/menubar.html, templates/level-page.html
Slide toggle hide a dropdown when the button is pressed again instead of the hacky re-slide open we currently have.
**Fixes**
This PR fixes #4066
Verify that the language dropdown, user profile dropdown and both the cheatsheet and language switcher dropdown all close when the button is pressed again. This makes the animation a lot more smooth than what currently happens when we press the button twice.
=> [UI IMPROVEMENT] Smoothen dropdown menus

grammars/level12-Additions.lark, grammars/level14-Additions.lark, tests/test_level/test_level_12.py
Fixes #4103 and fixes #4103
We might want to either disallow or fix this though, as it seems like reasonable thing that could work:
```
bord = '.', '.', '.', '.', '.', '.', '.', '.', '.'
bord at random = 'x'
```
=> [LANG] Allow assigning to a list element by index

hedy_content.py
Fixing the language gap between weblate and babel by manually overwriting the Kurdish language key.
**Fixes**
This PR fixes #4119
Check that no placeholders are shown for Kurdish.
=> Fix kurdish translations

app.py, utils.py, website/auth.py, website/profile.py
Previously, when you log out, you would be shown a JSON error message (because the browser will send `Accept: */*`, which includes JSON, and that's what we feature tested for). The goal was to respond with JSON to the Ajax requests. Fix by feature testing for yes JSON, but not HTML.
Also, the previous PR made it so that if you log out, you stay on the same page. But if this page is now a "my profile" page or "programs" page, it shows you a very big unfriendly "you are not logged in message".
Add a new `@requires_login_redirect` decorator, which redirects you back to the front page if you end up not logged in on certain pages.
Log in, go to your profile page, then log out. You end up back at the front page.
=> [FIX] Improve logout experience

website/dynamo.py
The new program storing logic was assuming that `update` would return the updated state of the record.
This is an option in DynamoDB, but it is not the default.
Switch it on.
(can only be tested on alpha) Sharing a program will no longer throw an error.
=> [FIX] Return newest state of record on update

app.py
The old code was assuming that all built-in adventures that appear in the `ordered_adventures` actually still exist.
However, this list can also change and items can be removed from it, so deal with that by ignoring them.
Search for a class in the database that uses the `pressit` adventure, and log in as a student in that class.
=> [FIX] Student page can deal with builtin adventure being missing

website/programs.py
In the new autosave system, switching away from a tab automatically saves your current program.
Some students are experiencing that (for some reason we don't understand yet), their previous programs aren't automatically loaded, and then the autosave overwrites their old program with a blank one.
This can only happen because we have a legacy bit of code in there, which says that if you don't include a program id, it's going to overwrite an old program with the same name. Since no one ever changes the default save name, this is most likely the culprit of the old program being overwritten (new empty program has the same name as the old saved program, and is therefore clobbered).
Disable this behavior, as we don't need it any more and it in fact behaves poorly in combination with autosave. …
=> [FIX] Do not overwrite programs with the same name

static/js/app.ts, static/js/types.ts
Fixing two bugs around local storage saving:
- In an attempt to account for saving local storage programs to the server, *every* program would be stored to the server, even if the student is just flipping through the tabs without actually changing the code.
- The code from local storage wouldn't even be loaded if the user is logged in -- which is besides the point, the point was that the code SHOULD be loaded if you are logged in, so that a program you wrote anonymously could still be saved to your account after login.
Solution:
- Check for local storage programs always.
- Keep track of whether a program is loaded from local storage, and save to the server only if it was in fact loaded from local storage.
(Regenerate JS locally, I did not check it in and the PR build …
=> [FIX] Remove unnecessary saves, load from local storage even if logged in

app.py, website/database.py, website/types.py
Programs are saved with the adventure they were associated with. For built-in adventures, this is the symbolic short name.  For teacher adventures, we used to store them with the long display name, but somewhere along the way this was changed to the adventure id.
The current code only uses the adventure id to select programs into a tab, but the result of that is that programs that were saved before the new standard cannot be loaded anymore.
Upon loading the student page, also identify programs by adventure name if no programs can be found by adventure id.
Find a student in a class with custom adventures that were saved before the attribute name was changed. Log in as that student, observe that the program is loaded onto the customer adventure tab.
=> [FIX] Restore loading old saved programs on teacher adventures

static/js/parsons.ts
The fisherYatesShuffle did it's work already; the shuffle_code_lines function returned an array with numeric keys, which was nicely shuffled, but retained the numeric sortorder, which was the correct order.
**Fixes #3475**
Go to any level, open the parsons tab, observe sort order; refresh and observe again.
**Checklist**
=> [FIX] Parsons puzzles were not randomized

templates/preview-quiz.html
Wait for DOM to be loaded before loading quiz question.
**Fixes #4196 **
Going to the preview route (http://0.0.0.0:8080/quiz/preview-question/1/1) now gives the appropriate page.
=> [FIX] Broken quiz preview

templates/class-live-popup.html, templates/class-live-stats.html, templates/macros/stats-shared.html, website/statistics.py
The card with common errors/misconceptions now has clickable elements (apart from the reolve which will be a separate issue). 
Relevant technical choices:
- The popup has its own html file which extends the live-page
- it creates a transparent overlay with a slight top margin so the navbar is still clickable but the other elements are not
- macro was changed to include the parameter used in the href link
Test instructions:
- Run hedy locally, login as teacher or admin, navigate to for_teachers/class1/live-dashboard
- Click on any of the three items in the 'Students who are struggling' card
- A page should open looking like this:
=> [RU] Implemented clickable popup windows for the common errors section of the dashboard

app.py, website/programs.py
We were not logging user-attributable information for all HTTP requests, only for a couple. This makes it very hard to debug things going wrong.
Make sure we log user-related information with every request (session and username), and emit a couple more bits of information whenever we end up saving a program so it'll be easier to debug weird saving issues.
Nothing to test.
=> [FIX] Log session and user info for all HTTP requests

translations/hu/LC_MESSAGES/messages.po
Adds Hungarian translations for:
* error messages about program attempted to run
* page titles
* messages about class organization & user registration
* other navigational messages
=> [TRANSLATION] Add Hungarian message translations

templates/quiz/hx-question.html
Reverts hedyorg/hedy#4259 (because it causes a new issue (see: https://github.com/hedyorg/hedy/issues/4258#issuecomment-1522259690)
=> Revert "[FIX] converts newlines to br in quiz options"

templates/layout.html
Removes the body background color when displayed in raw modus. This is useful when embedding the editor, for example for the slides.
**Fixes**
Verify that no background color is shown when navigating to a raw adventure, for example:
`http://localhost:8080/adventure/story/1/raw`
=> [UI FIX] Removes background color from UI when displayed raw

website/for_teachers.py
In the server log, I've seen this exception:
```
<ERROR>: Exception on /for-teachers/get-customization-level [GET]
Traceback (most recent call last):
.....
File "/app/website/for_teachers.py", line 225, in change_dropdown_level
customizations, adventure_names, availableadventures,  = self.get_class_info(user, session['class_id'])
File "/app/website/for_teachers.py", line 347, in get_class_info
available_adventures = self.get_unused_adventures(customizations, teacher_adventures)
File "/app/website/for_teachers.py", line 398, in get_unused_adventures
customizations['sorted_adventures'][adventure['level']]:
KeyError: 1
```
The issue seems to be that `adventure['level']` is the integer `1` and it is not in the `sorted_adventures` dictionary.
I'm not sure how we guarantee that …
=> [FIX] Attempt to fix a 500 server error

build-tools/github/validate, build-tools/github/validate-pofiles
For reasons we're not quite sure of, sometimes translations get lost while generating `.po` files. A situation that happens sometimes is that we end up with the following in a file:
```
msgid "mandatory_mode"
msgstr ""
(...a lot further down...)
\#~ msgid "mandatory_mode"
\#~ msgstr "Mandatory Developer's Mode
```
For some reason the correct translation is commented out and replaced with an empty string one.
This PR adds a script that will detect this situation and fail the build on the PR that tries to accidentally introduce this situation.
The build on this PR will currently fail, as the `main` branch is currently in this broken state.
Once the main branch is fixed and merged into this PR, the build will start passing.
=> [CHORE] Detect .po file problems during the PR build

templates/incl/editor-and-output.html
In https://github.com/hedyorg/hedy/pull/4215, the `height: 22rem` style attribute was removed from the program output, which stops it from restricting its height and makes it grow with the output.
Revert that.
=> [FIX] The output window grows with all output

CONTRIBUTING.md
When Weblate writes `.po` files, it will always use wrapping.
When we then recommend to disable wrapping, we trigger an endless fight between ourselves and Weblate where we will unwrap a line and Weblate will wrap it and then we will unwrap it and so forth...
=> [CHORE] Remove `--no-wrap` from recommended `pybabel` command

templates/incl/editor-and-output.html
The programmer's mode has a "gap":
This shows I should stay out of the css :D 
This PR fixes it :)
=> [FIX] Removes the gap in the programmer's mode

templates/quiz/hx-question.html
The quiz has an `output` field that gets rendered to show the output of a hypothetical program. The output was being rendered as black text on a dark blue background, and barely readable.
Make it readable and treat the text as `<pre>`formatted.
Also change the width of code and output containers to look slightly nicer.
http://localhost:8080/quiz/preview-question/9/5 will show the difference.
Before:
After:
=> [UI] Fix unreadable quiz output

templates/incl/editor-and-output.html
This bug has a fun backstory :) 
#4215 introduced an issue where code now expands the output box, then #4302 fixed that, but caused a new issue (a gap in the programmer's mode) which #4317 fixes, but that again caused the output expansion to resurface. This reverts the original change that was not even needed since we have the if in the raw already.
Lesson learned: I should not touch the front-end without adult supervision :)
=> [FIX] Reset height fix

website/statistics.py
Classes with old programs were failing because some of them did not have the field `adventure_name`. This PR adds an if when retrieving programs that have this characteristic. It also deletes the debug prints that were added in #4416.
=> [FIX] Grid page failing

website/statistics.py
The Grid page fails when it tries to load customizations for a class that doesn't have any, of course this causes an error because it's then trying to access a field that isn't there. This PR fixes that mistake by creating a new default customizations object in case there ins't one. 
You can run `./feed_dev_database` and then delete the only customizations object in the database. Access the Grid for that class and it should work
=> [FIX] Grid not working when there are no customizations

app.py, website/achievements.py, website/quiz.py
We have gotten the following reports from the quiz module:
- Some student has gotten Python exceptions while doing the quiz, caused by a `list index out of range` error.
- Another student has gotten `400` errors saying `No such question`.
Trying to address the first issue by assuming the error was caused by the achievement handling code at the end of a quiz: that code was a little waffly about the return type of `add_single_achievement`; write code that can deal with either return value.
For the other issue (and also in case we get the first issue wrong), start logging more details about the quiz state and 
Start the server, click around in the Quiz. Observe that fields like `level` and `question` are logged to the console in the giant dictionary:
=> [FIX] Try to fix and log quiz issues better

static/css/additional.css, templates/incl/editor-and-output.html, tests/cypress/e2e/hedy_page/editor_box.cy.js
There's a bug right now in Hedy were the keywords in the errors are not being highlighted:
This is due to a syntax error in `additional.css`. Now is back to normal:
=> [FIX] Highlighted commands are shown in errors again

app.py, website/cdn.py
When looking at the server statistics, there is a disproportionate amount of 304 responses being served by the Hedy website.
The reason is that since migrating to Flask 2.0, the defaults for caching changed. In Flask 1.x, static file caching was enabled by default, in Flask 2.x it no longer is.
For the CDN, we still up the caching lifetime to a day, but the caching directive still contains `no-cache`, which leads to a confusing HTTP response header:
```
$ curl -vv https://hedycode.com/static-c845eac78bba21798d23a3ea3134639ad0194d35/css/additional.css -o /dev/null
...
< Cache-Control: no-cache, max-age=86400
...
```
This response says: "don't cache me, but you can do that for up to a day".
The upshot is that our CDN doesn't cache, hits the upstream server every time, and gets served a `304 …
=> [FIX] Re-enable caching after Flask 2 migration

tests/cypress/e2e/hedy_page/editor_box.cy.js
In #4468 we merged a few cypress tests that had to do with the editor; they executed correctly in that PR, but after that they started failing consistently. So, in this PR I'm removing them from the test suite, leaving a comment stating that we need to come back to it, and also noting it in #4455.
=> [FIX] Remove failing tests

static/js/app.ts
Changes the static root from `'/'` to `'' ` when we are in a dev enviroment. The problem was that when we didn't point to a CDN and the contents were delivered from the server the paths looked like this: `//vendor/`  this caused Skulpt not to find those extensions and fail. 
**Fixes #4524**
Try the `clear` or pygame comands.
=> [FIX] Fixes Skulpt extensions not working on dev and Alpha

website/for_teachers.py
When storing the customizations settings we where using the same variable for both the levels in the live statistics module, and for the class customizations. Changing that to a use a new variable name fixes the problem.
1. Go to class customizations.
2. Select a few levels and unlock them.
3. Recharge the page
The levels shown should be the ones you selected.
=> [FIX] Fix levels in customizations not being set properly

hedy.py
Since about a week, the page load times in Hedy have gone up by a lot. My best guess is that the cause is disabling the parser caching in https://github.com/hedyorg/hedy/pull/4504.
This re-enables the parser cache to see if this fixes the load times.
Merge, and eyeball the page load times in Heroku.
=> [FIX] Re-enable parser caching

app.py, website/achievements.py, website/programs.py
Hedy seems to have gotten slower after the deployment of revision `f626e4b1` (previous revision before that: `40ea2878`). There are too many changes in the diff to easily figure out what would have caused that slowdown.
I thought it would be #4504 (which was reverted in #4543) but that didn't clear it up.
Looking into the statistics, it seems that the `/parse` endpoint seems most affected, but the time is NOT spent in transpiling according to the statistics:
```
transpile_ms   duration_ms   method   path
------------   -----------   ------   ------
2143           8769          POST     /parse
1101           5389          POST     /parse
1136           5343          POST     /parse
814            4834          POST     /parse
1045           4820          POST     /parse
2012           4804 …
```
=> [CHORE] Record more timings for `/parse` API

.github/workflows/generate-snippet-hashes.yml, tests/Tester.py
Before this change we ran the snippet generation daily. This resulted in commits even when there was no activity. As the snippets file is a bit big and has binary contents, the history of the repository grew a lot.
Now we switch to only updating the hash generation when one of the files that invalidates the entire cache is updated.
We do not do this on PRs as we can not/ do not want to push commits to forked repositories.
After we merge a PR to main, and it had one of the files affecting snippet generating updated, we make a separate commit that updates the snippet hashes file.
Fixes #4546 .
This is a bit sub-optimal, but you can only test this change with quite some effort (creating a fork etc). However, I did some of …
=> [CHORE] run snippet generation on changes

hedy.py, hedy_translation.py
Implement a disk based caching system for the parsers. They take about
0.5 seconds to be constructed which leads to delays and high CPU usage.
We used to cache to RAM but now needed multiple GBs of RAM for all the
parsers. The servers don't like this.
With this PR we cache to disk, by pickling the parsers.
NOTE: this PR contains a commit which belongs in #4574 but was needed for this change too. If it gets merged the commit can be dropped from this PR.
Discussed this in PR #4576 .
- See all CI tests succeeding
- Run the entire pytest suite without this fix locally and observe a +/- 1.5GB memory footprint.
- Run with this patch and see that it should only uses about 400MB, while being roughly as fast to execute
- After deployment to production there should be less out of memory issues. …
=> [FIX] reduce production memory usage by caching parsers to disk

.github/workflows/generate-snippet-hashes.yml
After my attempt to make the snippet generation change-based in #4573 there's good news and bad news. The good is that the trigger works, and a PR that had a new `hedy.py` file triggered the snippet generation. The bad news is that the automatic commit action failed due to a permission issue.
https://github.com/hedyorg/hedy/actions/runs/6409135403/job/17399693158
Reading the workflow logic this does not make sense to me and feels like a bug in the git-auto-commit-action but it is what it is :shrug: . As we had no simple way of testing this we decided to merge anyway and solve problems as we go along. This fixes the issue.
- merge this and see if the next change to grammars and/or hedy.py manages to commit the snippet hashes correctly.
**Checklist**
If …
=> [FIX] fix the github workflow for generating snippet hashes

.pre-commit-config.yaml
Weblate's YAML formatter is fighting with the YAML formatter, and it's an endless standoff.
See #4572.
Disable our YAML formatter for now.
=> [FIX] Disable YAML autoformatter on precommit

.pre-commit-config.yaml
Reverts hedyorg/hedy#4593. 
We are now thinking that the precommit formatter doesn't necessarily cause Weblate to keep re-pushing. Re-enable to see what happens.
=> [FIX] Re-enable YAML autoformatter on precommit

hedy.py
In French, it is common to have quotes in messages, this commit generalizes the correction that has been done at level 1 but that was also present at level 16.
If you tried the following code at level 16, you had the same error as the one reported by the issue #4610 instead of having a nice error message
```
fruit = []
fruit[1] = "pomme"
```
**Adds** I created the function `translate_index_error` responsible for translating a possible IndexError exception and escaping all possible quotes in the error message.
Being new to Hedy, I did not really know where to put that utilities function. Please give me any instruction in the comments.
**Fixes #4610**
Run the following code in French, at level 16 : 
```
fruits = []
fruits[1] = "pomme"
```
The reported error …
=> [FIX] Generalize the fix for quotes in french exception messages

translations/en/LC_MESSAGES/messages.po
PR #4613 was created last week. This contained just a teststring in the Englisch po file to see how Weblate handled the automatich filling of other languages and squashing those changes into one commit.
This worked fine, hence this PR removes the teststring again.
=> [CHORE] Reverting teststring

static/js/app.ts
Switching the keyword language produced "converting circular JSON" error message.
The reason was that we were trying to post the entire editor object as JSON to the server, instead of just the code from the editor (bug introduced in the following refactoring #4341).
Log in, set your language to non-English and your preferred keyword language to non-English.
Then use the language switcher on a code page.
=> [FIX] Fix inline keyword language switcher

templates/embedded-editor.html
This is a small improvement to the embedded editor to listen to messages from the host page. In this case allow to dynamically toggle the readonly state of the editor. Something that can be useful for several use-cases.
=> Allow embedding host to toggle readonly mode

static/js/app.ts, static/js/skulpt_debugger.js, tests/cypress/e2e/hedy_page/debugger.cy.js
After merging #4465 some Cypress tests were failing. This was because an ad-hoc calcutation I did to figure out the current debugging line. It worked fine locally and even in the tests in the PR, but for some reason failed later on, this PR deabilates that check and I will work on it later this week.
Also, after testing in Alpha I found out I wasn't showing the error messages when an error ocurred during execution. 
How to test?
Go to level 3 and write this code:
```
l is 1, 2
print l at 3
```
Then debug it and when you reach the second line this error should be shown:
=> [FIX] Fix error messages in debugger, and temporary fix for cypress tests

app.py, website/database.py, website/for_teachers.py
In #4644, the call signature of `filtered_programs_for_user` was changed to replace the function `public_programs_for_user`. The goal was to be able to supply the query `get_many({ "username": "henk", "public": 1 })`, with the goal to retrieve all public programs by user `henk`.
Unfortunately, there is no index on the pair `(username, public)`. Instead, we have indexes on `(username)` and on `(public, date)`.
The first is used to retrieve all programs by a single user, the second is used to retrieve all public programs (for the "Explore" page). To get the public programs for a single user, instead what we do is retrieve all programs for a single user, and filter them down in Python.
Because of a bug in the database layer, trying to retrieve programs by `{ "username": "henk", "public": 1 …
=> [FIX] Fix the `filtered_programs_for_user` call

tests/cypress/e2e/for-teacher_page/class_page/customize_class_button.cy.js, tests/cypress/e2e/for-teacher_page/class_page/go_back_to_teacher_page_button.cy.js, tests/cypress/e2e/for-teacher_page/class_page/second_teachers_invites.cy.js, tests/cypress/e2e/for-teacher_page/customize_class_page/customize_class.cy.js, tests/cypress/e2e/tools/classes/class.js
Fixes the issues of not finding an element because of hte survey modal.
=> [FIX] hide survey modal whenever navigating to a class

tests/cypress/e2e/for-teacher_page/class_page/second_teachers_invites.cy.js
The first test in the file `second_teacher_invites` was failing because the survey was getting on the way. This PR fixes it by creating a new class before all the tests are executed, and since this new class doesn't have any students we guarantee that the survey is not shown. This approach should be applied to all the other tests, I think, but this one is a bit more urgent since it's not letting us merge PRs
=> [FIX, TESTING] Fixes failing teacher test

templates/level-page.html
=> [BUG] Hidden dropdown

static/css/additional.css, static/js/index.ts, templates/incl/editor-and-output.html, templates/incl/parsons.html
Fixes #4441 
Enhanced the overall ui of exercises.  
- Better header;  
- Clear background and font weight on the currently selected exercise 
- Also, users now can click to navigate through existing exercises 
- Next button doesn't show currenlty. 
- Hiding it always is fine, since navigation is possible using the headers. 
- see #4441 or simply view the puzzles..
=> [BUG] Allow users to navigate between exercises using header

.gitignore, hedy.py, tests/test_level/test_level_05.py, tests/test_level/test_level_07.py
Fixes #4863.
After #4838, the processing of the string was done after setting the input string on the source map.
This led to 2 tests failing.
This PR first uses process_input_string before setting the input on the source map. Fixing the failing tests.
=> [BUG] Fix broken tests

hedy.py, tests/test_level/test_level_04.py
Oops, I misplaced a try-catch in #4836!
This fixes #4879
=> [LANGUAGE] Repairs undefined var exception

tests/cypress.config.js
Cypress tests fail due to memory problems. The added flags do two things:
- does not store any test in memory within github actions
- and uses a new memory management recormmended by cypress for Chromium-based browsers.
This will hopefully solve the memory problem we are having lately.
=> [BUG] fix cypress memory overusage

templates/embedded-editor.html
This PR fixes a bug where there would be whitespace add the bottom of the embedded editor when on readonly and disabled run mode. This because we calculated the height of the editor based on the height of the run button. But if it's not there, no need to take this space!
The following test link should no longer have whitespace at the bottom:
http://127.0.0.1:8080/embedded/1/?lang=nl&run=false&readOnly=true&program=cHJpbnQgZGl0IGlzIGVlbiB0ZXN0IQplY2hvIHdhYXJvbSBrbG9wdCBkaXQgbmlldD8KdGVzdCB0ZXN0CnRlc3QgdGVzdA%3D%3D
=> [BUG FIX] Fix embedded editor when in read only mode

app.py, templates/customize-class.html
Fixes #4937 
Now students can see all levels if the teacher disabled the quiz feature. Otherwise, the quiz threshold and their scores will determine whether they can see it or not.
=> 🪲 only check threshold if quiz is enabled

dodo.py
While updating the [Hedy development wiki](https://github.com/hedyorg/hedy/wiki/Hedy-Development-Process) to match the newest ways to run scripts using `doit`, I noticed that there are still some elaborate instructions around running scripts and setting environment variables etc in there.
Those can be encoded using `doit` as well, so that running a local copy of the server can be as simple as:
```
doit run devserver
```
This will take care of recompiling Babel files when necessary, so that those instructions can be removed. It sets the environment variables that some parts of the code require (`BASE_URL` and `ADMIN_USER`) so that those instructions can be removed as well.
Run:
```
doit run devdb frontend devserver
```
Observe that Babel files are regenerated, before the …
=> 🚚 add `doit run devserver` command

dodo.py
`ON_HEROKU` was a variable we needed to set ourselves, but `DYNO` is automatically set by Heroku.
That means we can't forget to configure it on new environments
Deploy to alpha and prod. It succeeds.
=> 🚚 Detect Heroku without setting additional environment variables

templates/for-teachers.html
Fixes #4645 
Go to the `/for-teachers` page and remove all classes and adventures. The class info or adventure info is now visible. If you add a class or adventure, the info is not visible.
=> 💻 If no classes or adventures, show info

templates/quiz/partial-question.html
Fixes #4743 
Go to, for example, level 3 - question 7. The command 'add' is now rendered as an command.
=> 🪲 Render command in quiz title

hedy.py, tests/Tester.py, tests/test_level/test_level_12.py
- Fixes #2689
- Addresses a hedy type error when an input from an ask statement with concatenated with a literal string
- There are unit tests for the change. Please check whether they correctly cover the change.
- Run hedy locally and go to level 12. Check that the following code does not produce a type error. Instead, the program should execute and prompt the user for input.
```
answer is ask 'Yes or No?'
print 'The answer is ' + answer
```
- Pay special attention to the tiny change in the tests/Tester.py because it affects the whole test suite. I am confident the change is needed based on the history of the file.
=> 🪲 Fix type error when concatinating ask input and a literal string

content/adventures/sq.yaml, hedy.py, highlighting/lezer-grammars/level10.grammar, highlighting/lezer-grammars/level11.grammar, highlighting/lezer-grammars/level12.grammar, highlighting/lezer-grammars/level13.grammar, highlighting/lezer-grammars/level6.grammar, highlighting/lezer-grammars/level7.grammar, highlighting/lezer-grammars/level8.grammar, highlighting/lezer-grammars/level9.grammar, tests/cypress/e2e/lezer-tests/level_05.cy.js, tests/cypress/e2e/lezer-tests/level_06.cy.js, tests/cypress/e2e/lezer-tests/level_08.cy.js, tests/cypress/e2e/lezer-tests/level_12.cy.js, tests/test_level/test_level_12.py, tests/test_level/test_level_16.py
Fixes #5083
- Fix incorrect result when checking whether a number is in/not-in a list starting from level 12
- Fix highlighting of left-hand-side arguments of in/not-in operators starting from level 6
- Fix broken tic-tac-toe adventure snippet in Shqip in level 14. It seems that one of the letters in the variable name was a Cyrillic 'e' instead of a Latin 'e'. This caused the program to not work correctly at runtime.
To test the corrected transpiling of the in/not-in operators:
- Ensure that the unit tests cover convert the left-hand-side argument of the operators, so that the original type is preserved.
- Run Hedy locally and navigate to level 12. Execute the following snippet and ensure that the output is 'Found' instead of 'Not found'
```
numbers = 1, 2, 3
if 1 in …
```
=> 🪲 Fix incorrect transpiling with in/not-in checks for lists with numbers

hedy.py, tests/Tester.py, tests/test_level/test_level_07.py, tests/test_level/test_level_08.py, tests/test_level/test_level_12.py
Fixes #2790
- Start hedy locally and navigate to level 7. Execute the following snippet and supply a non-numeric value as input. Ensure that there is a nice error translated correctly.
```
hoeveel is ask 'hoeveel?'
repeat hoeveel times print 'times'
```
- Repeat the same for level 8 and the following snippet:
```
hoeveel is ask 'hoeveel?'
repeat hoeveel times
print 'times'
```
=> 🖊️ Show translated error when text input is passed to repeat command

app.py, hedy_content.py
Adds the teacher adventure's names to the `adventure_names` dictionary, preventing a bug that was causing the `/programs`  page to crash. Also adds a bit of defensive programming around the use of that dictionary, in case in the future we have a problem in the content or in the adventures from the DB.
* Log in as a student that has a program saved which comes from a teacher adventure and go to My programs page. Check that the page works correctly and doesn't crash.
=> 🪲 Correctly filter teacher adventures in programs page

app.py, templates/htmx-program.html
Same thing happened to us back in #4417. Some old programs don't have the field `adventure_name` in them, and thus our systems fails. I also improve a bit the filtering of programs, by not using the program name, but rather the adventure name.
I also have a question, what to do with programs that might have an id that's neither in the DB or our own contents? Right now, Im resorting to just show the id, but perhaps we should skip them? What do you think?
Go to My Programs page, it should be working. 
If you want to see a program with a non-existing adventure linked, copy an existing `program` record in the dev_dabase.json and change the `adventure_name` field to something that's not present in the database.
=> 🪲 Fix old programs in program page, improve filtering teacher programs

.github/workflows/update-javascript-on-main.yml
Make the following changes:
- Generates all files that need to be updated instead of just JavaScript files.
- This is done via a `doit` command, `doit run _autopr`.
- Make it use the `pull_request_target` event, so that it can run with access to the Personal Access Token which allows pushing to forks (necessary to update Weblate PRs, which are created from a fork).
=> 🚚 Update JavaScript autocommit workflow

dodo.py, tests/test_snippets/snippet_tester.py
These slipped in during a refactoring of the Weblate PR handling.
Remove them, they make precommit fail.
=> 🚚 Get rid of some precommit warnings after refactoring

.github/workflows/update-javascript-on-main.yml, .gitignore, requirements.txt, tests/Tester.py, tests/test_snippets/snippet_tester.py
The problem was that the script would write to a `.txt` file, which would subsequently get committed and trigger another update which would post again, etc.
Fixed by writing to `.md.tmp` files, and gitignoring `.tmp` files. While we're at it, make the comment a bit nicer to read as well by outputting MarkDown instead of plain text.
=> 🚚 Prevent the endless update train when fix script reports errors

.github/workflows/resolve-weblate-conflict.yml
We weren't using version 6, and needed to set the correct base branch.
=> 🚚 Fix parameters to "create PR action" in Weblate merge conflict workflow

.github/workflows/update-javascript-on-main.yml
By using the user-supplied branch name in a shell script, commands could be injected if the branch name contains a `"`.
=> 🚚 Prevent shell injection using branch names

.github/workflows/resolve-weblate-conflict.yml
It doesn't have the executable bit set, so run it via the right interpreter directly.
=> 🚚 Have to run merge script through bash

.github/workflows/resolve-weblate-conflict.yml, .github/workflows/update-javascript-on-main.yml
Otherwise, it looks a bit confusing.
=> 🚚 Make HedyBot perform automated commits, instead of Felienne

build-tools/github/restore-po-header.py, dodo.py
Our plans to finagle Weblate into committing only once per day to reduce conflicts, allowing us to heavily normalize the translation files, has failed. Weblate is going to commit constantly, and it will have created files with the headers, wrapping, and key ordering that it has decided on its end. Any of our attempts to reformat those files will just lead to merge conflicts.
Instead: turn off YAML and POfile formatting; instead what we do to minimize the chances of conflicts is to stop PyBabel from updating PO file headers. Only Weblate is allowed to update those headers.
=> 🚚 Stop normalizing YAML and PO files

content/slides/sl.yaml, tests/test_snippets/snippet_tester.py, tests/test_snippets/test_slides.py
We were not reverting broken snippets found in Slides files yet. Add those as well.
=> 🚚 Extend the snippet reverting logic to Slides

.github/workflows/unittests.yml, build-tools/github/validate, build-tools/github/validate-tests, tests/test_level/test_level_12.py
There used to be 3 modes of running the tests:
* Normal
* With `--all` flag (only on non-Weblate PRs)
* With `--weblate` (only on Weblate PRs)
The result was that that the test suites:
tests/test_highlighting
tests/test_level
tests/test_translation_level
Would not be run on Weblate PRs, and not locally.
Simplify the logic a bit by dividing the tests into 2 classes:
- Normal tests, always run
- Slow tests, run on Weblate PRs
=> 🚚 Simplify test partitioning

.github/workflows/update-weblate.yml
After we have told Weblate to push all of its pending commits, it should forget about them.
The reason is that we may revert some code samples, and when the translations PR finally squash-merges its way onto `main` and gets back to Weblate, it will see a conflict with its own pending changes.
By resetting, it will forget about its own pending changes, and consume the changes when they finally come in from the upstream repo.
This probably leads to an inconsistency window in which it looks for about ~1hr like the changes have disappeared. Fear not, they haven't, they will come back once the PR is in and Weblate syncs from the main repo.
=> Trigger a Weblate reset after pushing translations

templates/customize-class/partial-sortable-adventures.html
Fixes #5263 
The problem was that we didn't pass the class_id argument to the function that allows teachers to go back to their class.
=> 🪲 fix go-back to class undefined

tests/test_dynamo.py, website/dynamo.py
As discovered in #5350 by @jpelay, the Dynamo emulation layer has a bug that can lead to accidental data sharing between different requests, because the DB layer hands out references to long-lived objects. If those get mutated in-place by a reader, those mutations accidentally affect the stored in-memory copy of the database.
How I did this:
- Write the tests first to encode the contract that mutations to retrieved (or inserted) objects shouldn't persist to objects retrieved in other queries.
- Replace `copy.copy()` with `copy.deepcopy()` everywhere 😳 oops!
Follow the steps in #5350.
=> 🪲 Fix accidental object sharing in Dynamo layer

prefixes/normal.py, static/js/pythonPrefixes.ts, tests/test_python_prefixes.py
Fixes  #5341 
The prefix function convert_numerals now has support for empty strings and None values.
Run Hedy locally and navigate to level 12 and run:
```
for i in range 1 to 3
form = ask "What form?"
color = ask "What color?"
if form is 'test'
print 'test'
```
Once the program is running do the following:
1. Supply any value to the first input, e.g. `a`
2. Supply any color to the second input, e.g. `red`
3. Cancel the program by clicking the 'Stop program' red button
4. Start the program again
5. Supply any value to the first input, e.g. `b`
6. Supply any color to the second input, e.g. `red`
7. Check that there is no 'string index out of range' error
=> 🪲 Add support for empty strings to convert_numerals prefix function

website/statistics.py
Adds a sort of profiling to this page by placing some timers in some key function where I think the slowdown happens. Why is it so hacky? I tried for several hours to use werkzeug's `ProfilerMiddleware` but I think there's a bug with the implementation, as several people have reported in some other tools: https://github.com/jazzband/django-debug-toolbar/issues/1875, https://github.com/jazzband/django-silk/issues/682
I thought that since we didn't need the full-fledged tool and didn't want to spend more time on this, this approach would suffice.
=> 🧪 Profile live statistics page

tests/cypress/e2e/public_programs/programs_page.cy.js
Adds an intercept for the public profile call, which I think is the cause behind the flakiness.
=> 🧪 🪲 Fix flaky public program test

.github/workflows/update-weblate.yml
If an open Weblate/translations PR still exists, we shouldn't tell Weblate to push again.  Because we ended our previous push with a 'reset', Weblate would otherwise force-push new changes over the unmerged old changes, causing them to lost.
After merging:
* Reopen an old Weblate PR
* Run the "update weblate" workflow on-demand
* Observe that it errors out and doesn't overwrite the old PR with new changes.
=> 🚚 Prevent Weblate Update workflow from overwriting existing PR

.gitignore, static/js/app.ts, templates/embedded-editor.html, templates/incl/editor-and-output.html
Fixes #5396 
1. Check this code:
```
repeat 10 times
forward 100
hoek is ask 'Hoe ver moet ik draaien?'
repeat 5 times
forward 10
turn hoek
```
2. Check if other ask modals and turtle output still looks as it should.
https://github.com/hedyorg/hedy/assets/48122190/eaef727c-b280-4bba-993b-d3f368f45979
=> 💻 Show turtle with ask modal

content/adventures/en.yaml
Fixes #5267 
Go to level 12 - draw it
=> 📜 Fix image and example code in draw it level 12

grammars/level5-Additions.lark, grammars/terminals.lark, tests/test_level/test_level_09.py, tests/test_level/test_level_12.py, tests/test_level/test_level_18.py
Fixes #5395
In a specific case, an end block (`#ENDBLOCK`) is parsed as a comment. This PR excludes end blocks from the definition of comments. Note comments are ignored in the parse tree, while end blocks are not. To ensure we will not leak an end block in an parse error message, I altered the textwithoutspaces to include a potential end block.
How to test
- Ensure that the following program does not produce an error in level 9
```
repeat 3 times
print 3
repeat 5 times
print 5
print 1
```
- Ensure that the following program does not show an error message which leaks a character from the endblock. It should mention that the unexpected character is a new line and not `#`:
```
for i in range 1 to 10
print i
```
=> 🪲 Exclude end blocks from comments

tools/merge-weblate-resolving-conflicts.sh
The Weblate merge conflict resolution script begins with normalizing the YAML files on Weblate's branch before merging `main` (which is always normalized).
However, because we left out `--allow-empty`, it would fail if there was nothing to normalize.
Allow creating an empty commit if there's nothing to normalize, the empty commit will be squashed away anyway.
=> 🚚 Fix Weblate merge conflict resolution script

content/adventures/zh_Hans.yaml, content/slides/ar.yaml, content/slides/hu.yaml, content/slides/ja.yaml, content/slides/kmr.yaml, content/slides/pa_PK.yaml, content/slides/sq.yaml, content/slides/uk.yaml, content/slides/zh_Hans.yaml
This PR merges pending commits from the Weblate repository that are conflicting with changes on `main`, while resolving conflicts in favor of the Weblate side.
=> Translations from Hosted Weblate

.github/workflows/resolve-weblate-conflict.yml, .github/workflows/unlock-weblate.yml, .github/workflows/update-weblate.yml
We're still sometimes seeing merge conflicts in Weblate because people are submitting translations in the ~1-2hr window it takes us to merge the update PR.
To completely avoid these, we're going to take rough measures: lock the Weblate repo when we start the merge process, and only unlock it after the PR is merged.
Because merging a PR is an asynchronous process, this lock/unlock behavior is split over 2 different workflows (`update-weblate.yml` to lock, `unlock-weblate.yml` to unlock).
For the cases where there are still conflicts due to manual editing in translated YAMLs, we do the same for the "Resolve conflicts" script: make it work the same as the regular daily update script (lock + make Weblate forget about changes it had that are now in a normalized PR).
As always, …
=> 🚚 Prevent Weblate conflicts by locking/unlocking

.github/workflows/unlock-weblate.yml, .github/workflows/update-weblate.yml
The Weblate UI allows locking/unlocking the entire project at once, but using the API we have to lock/unlock every component individually.
Do that, using a for loop.
=> 🚚 Fix automatic Weblate locking/unlocking

.github/workflows/resolve-weblate-conflict.yml
The "lock" command was correct for the daily Weblate job, but I forgot to update it for the on-demand "resolve conflicts" job.
=> 🚚 Resolve Weblate conflicts script doesn't lock properly

templates/htmx-adventures-table.html, tests/cypress/e2e/tools/adventures/adventure.js
Related to https://github.com/hedyorg/hedy/issues/5383
Removing an adventure from the adventures table isn't working correctly (check alpha/beta)
**How to test?**
- go to for-teachers
- remove an adventure,
- the table should still be visible and the adventure removed
=> 🪲 correctly remove adventure from adventrues table

static/js/app.ts, static/js/debugging.ts, templates/incl/editor-and-output.html
The variable view was acting a little wanky, showing and hiding seemingly at random. After some digging, I found that this area was being hidden and shown by several pieces of code, so I tried to simplify the logic a bit; also instead of just hiding and showing the box, I added a little bit of animation by using JQuery's `slideToggle`.
Fixes #5553
Go to the code page, debug a program, and verify that the variable view is updated with each step, and that it can be hidden and shown without issues.
=> 🪲 Fix showing and hiding of variable view

app.py
Same error as in  #5561
Fixes #5563 
Log in as a user, teacher1 for example, and set some programs to public. Then go to the Public profile and try using the filters.
=> 🪲 Fix filtering of programs in public profile page

build-tools/github/validate-yaml, content/achievements/achievements.schema.json, content/parsons/parsons.schema.json, content/quizzes/quizzes.schema.json, package-lock.json, package.json, requirements.txt
We were using a JSON Schema validator that was last updated 7 years ago, using a dependency called `deasync` that started causing problems building on Windows.
Replace with a different JSON Schema validator written in Python (`check-jsonschema`). An obvious alternative in NPM would have been `ajv-cli` which was last updated 3 years ago and also had vulnerable NPM dependencies. This removes all NPM vulnerability warnings and removes `deasync` from our dependency path.
=> 🧹 Replace 'pajv' dependency with 'ajv-cli'

app.py, hedy.py, static/js/app.ts
Fixes #5399 
In https://github.com/hedyorg/hedy/pull/5277 we introduced a sleep prompt, but accidentally we now now longer detect sleeps in levels below 7, causing them to quickly stop (annoying!) Maybe that was even the reason people were reporting #5399 but I upped the limits a bit too.
=> 🪲 Improve long program warning for sleep programs and increase time

hedy.py, tests/test_level/test_level_04.py, tests/test_level/test_level_15.py, tests/test_level/test_level_17.py
Fixes #5597
The color command fails with an unknown variable error because colors are not transpiled to literal colors but to variables.
- In level 4, the following command `color red` should work and make the turtle red. There should be no errors.
=> 🪲 Fix color command error

tests/test_dynamo.py, website/dynamo.py
`#` is not allowed in a name in key expressions, so we need to remove it from the symbolic names.
Before:
```
KeyExpression = "#id#level = :id#level AND #week BETWEEN :week_min AND :week_max"
```
After:
```
KeyExpression = "#id_level = :id_level AND ..."
```
Also taking this opportunity to make the handling of conditions consistent.
This didn't use to work, but now should work:
```python
data = PROGRAM_STATS.get_many({'id#level': id + '#' + str(level), "week": dynamo.Between(start_week, end_week)})
```
=> 🪲 DynamoDB queries fail on field with `#` in name

templates/incl/menubar.html, tests/cypress/e2e/home_page/language_search/language_choices_exist.cy.js
Fixes #5622 
https://github.com/hedyorg/hedy/assets/48122190/7ba6f801-2f9b-427d-b50f-00449324bddd
=> 💻 Small redesign language menu bar

static/js/teachers.ts
fixing:
https://github.com/hedyorg/hedy/assets/20051470/fb007c32-43fc-4fc6-a04f-c8e5e2be5214
**How to test?**
- deselect all levels of an adventure,
- an alert about not selecting any level should appear
=> 🪲 fix level dropdown in custom-adventure page

content/adventures/pt_BR.yaml, content/quizzes/pt_BR.yaml, translations/pt_BR/LC_MESSAGES/messages.po
I noticed some spots inside level 1 were still in English. I translated all of them to pt_BR.
You can start the server locally ( <code>doit run devserver</code> ) and go through level one, tab by tab including the quiz. Here is one screenshot of one of those texts that were in English and now is in Portuguese.
All tests passed, so everything is good:
=> 📜 Translate level 1 to pt_BR

static/js/app.ts, static/js/debugging.ts, templates/incl/editor-and-output.html, tests/cypress/e2e/hedy_page/debugger.cy.js, tests/cypress/e2e/hedy_page/run_code_button.cy.js
Fixes several bugs for the debugger, including:
* Now the debugger disables the continue button, so the only possibility to continue executing the program is when there are no instructions being executed.
* Fixed the problem when the debugger did not show the turtle canvas.
* Overlays the variable box on top of the output window, so now there's space for it when the turtle also shows in the program.
fixes #5672
fixes #5671
fixes #5670
fixes #4775  
* Copy and paste this program in level 2:
```
print I will draw a plus
angle is 90
forward 20
sleep 1
turn -90
color blue
forward 20
sleep 1
turn 90
color red
forward 20
sleep 1
turn -90
color black
forward 20
sleep 1
turn -90
color blue
forward 20
sleep 1
turn 90
color red
forward 20
sleep 1
turn -90
color black
forward 20 …
```
=> 🪲 Fixes for the debugger

static/js/parsons.ts
Fixes #5430
In puzzles, sometime the second exercise is not validated correctly because hidden elements get in the way of the correctness check.
Open the puzzle of level 5 and do the first exercise. Go to the second exercise and try to submit a correct answer.
=> 🪲 Fix incorrect parson validation

.github/workflows/unlock-weblate.yml
We have seen evidence of the `wlc unlock` command not unlocking anything. Add more debugging to see what's going on, so that we can create a bug report to Weblate.
The `wlc --debug` flag also prints out the API key, so we have to make sure to mask the API key out again so it doesn't end up in the logs.
=> 🧹 Add extra logging when unlocking Weblate

.github/workflows/update-weblate.yml
It seems that `wlc commit` followed by `wlc push` doesn't always create a PR (WeblateOrg/weblate#12400). This is the cause of the Weblate repository sometimes being locked without ever getting unlocked: unlocking happens on the PR-close workflow, but the PR never gets created.
In fact, since we also run a `wlc reset` to avoid future merge conflicts, the `wlc reset` destroys all pending translator changes, which has happened to some contributors and now their work is gone.
Add some sleeps to get a (presumably) async commit process to finish, and do an additional check for the `push` flag to reduce chances of data loss.
This is hard to test in isolation. We'll just have to monitor the GitHub Workflow runs over the next couple of days.
=> 🚚 Add sleeps to daily Weblate Update script

.mergify.yml
The mergify script is not working properly and we might think it can be related to this:
> Oops! In hindsight, I think we shouldn't have removed this part:
> ```
> queue:
>   name: default_queue
> ```
> That's probably the command to enqueue the PR for actual merging.
> 
> Noticing this after noticing that the Weblate PR didn't merge itself.
Original comment made by Rico in: https://github.com/hedyorg/hedy/pull/5738/files#r1742077765
=> 🚚 Add queue name to `pull_request_rules`

dodo.py
I noticed that when I added new tailwind classes in HTML files in the `templates` directory, the dodo task didn't compile them, and therefore didn't work. When I added the classes in files inside subfolders, the task was completed succesfully. Therefore in this PR I'm including a new glob pattern for files directly inside the  `templates` directory.
=> 🚚 Include files in template directory in tailwind task

.github/workflows/update-weblate.yml
We used to use `wlc repo` to try and see if Weblate flushed its changes to a PR.
Weblate always shows `needs_push: True`, even if it *did* create a PR, so that is not a reliable check.
Instead, we use the GitHub CLI to check for a PR with the title that Weblate always creates. We already check for the absence of such a PR at the start of the script, so if a PR exists at the end of it, it must be because Weblate created it, and we can safely reset.
Context: WeblateOrg/weblate#12400
=> 🚚 Use a different method to check for daily Weblate updates

static/vendor/skulpt-stdlib-extensions.js
This PR addresses the following issues:
- When the body of an if-pressed command contains more than one turtle functions, only the first one will be executed.
- When the body of an if-pressed command contains time.sleep(), the execution would terminate when reaching this line.
Fixes  #5729 #5681
Run locally, go to level 15 and run the following scenarios:
1. Check that the code below outputs all items in the list. Note that they should not appear at once, but with a tiny delay in between:
```
lijstje is "1", "2", "3", "4", "5"
if x is pressed
for dier in lijstje
print dier
else
print 'onbekend dier'
```
2. Check that when pressing x, all statements are executed. Note that the waiting-for-key-press modal should appear and then disappear while the action is being executed. …
=> 🪲 Fix bug in custom Skulpt module extensions

.github/workflows/deploy-to-prod.yml
Send a message to Discord once we deploy to production. 
Fixes #5742
* We have to accept and deploy, and then will see if this does send the message.
=> 🚚 Send message to Discord when deploying to hedy.org

.github/workflows/deploy-to-alpha.yml
Fixes #5862
Double-check that this is a correct syntax. After it is merged check that the action is executed automatically but could also be executed manually.
=> 🚚 Allow the deploy to alpha github action to be triggered manually

.mergify.yml
Fixes a small issue with https://github.com/hedyorg/hedy/pull/5852
Jinja template adds a new line after each iteration, this makes Github only recognize the last co-author. This error can be seen here: https://github.com/hedyorg/hedy/commit/d1109b1c8bf8834682b41d95ea5b985680402aaf
Adding `-%` to the template removes this extra newlines
=> 🚚 Fix extra newlines in co-authors

grammars/level16-Additions.lark, tests/test_level/test_level_16.py
This PR allows in level 16 to assign a list element another list element, e.g. `a[1] = b[2]`
Fixes #5758
Go to level 16 and try the following code:
```
kassa_munten = [1,1,1,1,1,1]
random_aantal_muntjes = [2,3,4,5, 6]
kassa_munten[1] = random_aantal_muntjes[random]
print kassa_munten[1]
```
Ensure that it works without errors
=> 🖊️ Allow assigning list access to list access 

content/adventures/en.yaml
This PR removes 5 nodes from the adventures yaml content with empty values, so that they do not show up for translation in Weblate.
Fixes #5890 
The Draw It! adventures should load correctly for levels 1, 2, 3, 7 and 8 and without an example code snippet.
=> 📜 Remove empty content from adventures

grammars/level2-Additions.lark, grammars/level3-Additions.lark, grammars/level5-Additions.lark, grammars/level6-Additions.lark, tests/Tester.py, tests/test_level/test_level_02.py, tests/test_level/test_level_03.py, tests/test_level/test_level_04.py, tests/test_level/test_level_06.py, tests/test_level/test_level_08.py, tests/test_level/test_level_12.py
With this PR we explicitly trim leading and trailing spaces in assignments in levels 2-11. Note that in these levels the assignment and list assignment statements do not quotes. The program `a is three spaces   ` used to be transpiled to `a = 'three spaces   '` but is now transpiled to `a = 'three spaces'`. Similarly, the list `a is  cat , dog ,  chicken ` is now transpiled to `a = ['cat', 'dog', 'chicken']`.
Fixes #5684
Ensure that the following snippet yields `[4]` twice in level 9. Ensure that there is no grammar ambiguity. 
```
i = 4   # met comment
print '[' i ']'
if 1 = 1
j = 4    # met comment
print '[' j ']'
```
=> 🖊️ Trim leading and trailing spaces in assignments

requirements.txt
This dependency is causing some dependency installation problems on Windows, so get rid of it.
Hopefully this unblocks the Hedy Offline build when the next release comes around. If not, we'll dig deeper again with the error log that we have at that point.
=> 🧹 Remove the `awscli` dependency

website/for_teachers.py
Fixes the problem of the class overview page crashing when teacher adventures had HTML tags inside of them, by instead of calling `pre.contents[0]` using `pre.text`. This is mostly a fix for legacy adventures, since currently it is impossible to add an HTML tag inside a code snippet when creating a teacher adventure.
Fixes #5314 
Follow these steps to verify this PR works as intended:
* Check that the class overview page works normally, even when students have programs from teacher adventures.
=> 🪲 Don't use `contents` when obtaining the contents of teacher adventures

tests/test_dynamo.py, website/dynamo.py
This is a DynamoDB change that should have been in the previous PR, but failed to get committed.
It makes sure that in the one case where we have a table with only a PK, but no SK, the test that makes sure you only use `Condition`s on SKs works properly.
No need, it's been unit tested.
=> 🧹 Fix the if statement that prevents using conditions on Partition Keys

app.py
Right now the programs page and my profile page is failing in Alpha. When looking at the logs this is what comes up:
```
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'programs_page' with values ['page']. Did you mean 'app.programs_page' instead?
```
Investigating a bit, this might be caused because the url is not registered yet, like [here](https://stackoverflow.com/questions/51234212/werkzeug-routing-builderror-could-not-build-url-for-endpoint)
=> 🪲 Fix programs page redirect

app.py, templates/explore.html, tests/python_html/fixtures/given.py, tests/python_html/test_explore.py, tests/python_html/test_login.py, tests/python_html/test_programs.py, website/for_teachers.py
The pagination links in various pages were using `url_for('programs_page')`, which builds a URL to a route on the global `app` object.
Since #6052 we don't have a global app object anymore. Instead, we use a global Blueprint called `app` instead.
In this PR, make all `url_for` calls in the same `app.py` file Blueprint-relative by prepending a period: `url_for('.programs_page')`, and make the `url_for` in the teachers page that points to a user's programs page (probably legacy and unused?) absolute by prepending the full Blueprint name: `url_for('app.programs_page')`.
Add tests to make sure that the page renders successfully.
Automatic tests have been added, so if they pass we should be good.
=> 🪲 Fix pagination links

tests/python_html/fixtures/given.py, tests/python_html/test_explore.py, tests/python_html/test_login.py, tests/python_html/test_programs.py, tests/python_html/test_public_adventures.py, website/database.py, website/public_adventures.py
When an adventure with a two different people as `author` (original author) and `creator` (owner), we copied the owner into the original author field.
That's wrong -- the original author is the original author! 😉
Fix it, and add a unit test for it. Also document the values better.
=> 🪲 Cloned public adventure should retain original author

app.py, static/js/app.ts
The feature for automatic saving and loading of programs is a bit too aggressive and loads a locally stored program even when we open the code page (/hedy or /tryit) to see a concrete user program. The proposed solution is to turn off the auto-loading when the code page (/hedy or /tryit) requested with a specific program id.
As a summary, if the code page is opened like this /hedy/1, the auto-saving should work as expected. If the code page is opened via /hedy/1/0dc61ace147b46ecbd2c71f1c3fc6c88 (logged as teacher 1), the auto-saving will be disabled. Note that it will be disabled also when moving to other adventure tabs. It will be enabled once we move away from this URL.
Fixes #6043
- Run Hedy locally and log in as teacher 1
- Navigate to /hedy/1 and in the introduction …
=> 🪲 Disable autosave on the code page when viewing a program

content/adventures/en.yaml
I believe i found some more typos and tried to fix them. Also added some missing command highlighting (like quotes and brackets) for easier translations. Let me know if something should be differently or better fixed.
=> 📜 Fix typos and command highlighting in english adventure

content/adventures/nl.yaml, hedy_content.py
I forgot a ' in an example code. Fixed it. 
Also switched the order of 1 adventure in level 6, so it made more sense.
=> 📜 tiny content fix NL

requirements.txt
`docopt`, `pydantic`, and `lazy` were added for `batchhedy` feature in
455037d061e7182230d8eea0084f36d59146ebbc, which had been unused and was
removed in c752db7365e5353488efca7d42760d53e585fafe
Issue: #3670
=> 🧹 Remove unused batchhedy deps

app.py, hedy_content.py, requirements.txt, templates/profile.html, templates/signup.html
Fixes #6227 
* Sorts countries by their English names, with some heuristics to account for country names that are mostly in latin characters. Previously countries were effectively sorted by their country codes, which was confusing since the country codes often didn't match the spoken name.
* Adds a new exported `FRIENDLY_SORTED_COUNTRIES` constant to `hedy_content.py` which contains the statically sorted list of countries.
* Adds [Unidecode](https://pypi.org/project/Unidecode/) ([GitHub project](https://github.com/avian2/unidecode)) as a new dependency in `requirements.txt`. This allows better sorting of names that have unicode characters or characters with diacritics.
* Changes `signup.html` and `profile.html` to use `all_countries()` instead of `all_countries().items()`, since it is now …
=> 🪲 Fix sorting of countries in signup and profile form
